### ISSUE TITLE
PageRowBounds统计总数为null?

### ISSUE THREAD

**Issue by haozileung** [pagehelper/Mybatis-PageHelper#10]
> 

        val p = PageRowBounds(0, 10)
        val users = userDao.pageSearch(p)
        users.forEach { println(it.username) }
        println(p)
        val total = p.total
        if (total == null) {
            println(0)
        } else {
            println(total)
        }
        println("+++++++++++++++++++++++++++++")

输出如下
>
test1395990298
test-181769175
com.github.pagehelper.PageRowBounds@232bdc3d
0
+++++++++++++++++++++++++++++

why?

**Comment by abel533** [comment]
输出的 SQL 什么样？确定是物理分页的？

**Comment by haozileung** [comment]
@abel533
sql是select * from users limit 10

**Comment by abel533** [comment]
在 `AbstractHelperDialect` 中的 afterCount 方法断点，找找原因！

**Comment by haozileung** [comment]
@abel533 
调试发现是要设置rowBoundsWithCount=true，才有total数据。

可是文档内是讲

rowBoundsWithCount：默认值为false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为true时，使用 RowBounds 分页会进行 count 查询（使用 PageRowBounds 时一定会进行 count 查询，不受该参数影响）。

所以？

**Comment by abel533** [comment]
文档错误。。这个实际上只在 `AbstractRowBoundsDialect` 的实现中是这样。。

文档已经修改。需要设置 rowBoundsWithCount。
