### ISSUE TITLE
SqlServerParser问题

### ISSUE THREAD

**Issue by yujie8409** [pagehelper/Mybatis-PageHelper#103]
你好，我用了最新的pagehelper-5.1.0-beta和jsqlparser-0.9.5，但是在SqlServerParser实例化时，报
java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.Top.setExpression(Lnet/sf/jsqlparser/expression/Expression;)V

我看了下源码，发现SqlServerParser有个静态代码块：
static {
        TOP100_PERCENT = new Top();
        TOP100_PERCENT.setExpression(new LongValue(100));
        TOP100_PERCENT.setPercentage(true);
        TOP100_PERCENT.setPercentage(true);
    }
但是在Top类中没有setExpression方法，而且为什么要setPercentage做两次？求解，谢谢

**Comment by abel533** [comment]
set两次是上次更新出的问题，不过不影响用。

怎么关闭了？问题解决了？
