### ISSUE TITLE
spring boot继承mybatis-pageHelper

### ISSUE THREAD

**Issue by a601942905git** [pagehelper/Mybatis-PageHelper#105]
boot项目中集成了分页插件,但是service中有些方法不想使用分页插件,想自己写分页,但是发现查询count的sql会执行2遍,一遍是分页插件执行,一遍是自己写的。是不是集成了分页插件,会拦截所有的sql

**Comment by a601942905git** [comment]
但是我的查询count和list都是自己写的,压根就没有调用PageHelper.startPage()方法,但是我的count方法会执行2次,一次是我自己写的,一次是PageHelper拦截的。当我把PageHelper依赖的包都删除之后,count方法就只执行一次。

**Comment by abel533** [comment]
换最新版本试试，5.0.2 之前的如果遇到指定参数会自动分页。
