### ISSUE TITLE
关于PageInfo响应为json的问题请教

### ISSUE THREAD

**Issue by wh469012917** [pagehelper/Mybatis-PageHelper#11]
我在开发API的时候，需要给客户端返回json，而且要包括分页信息，但是PageInfo类的信息太多了，我并不想全部给客户端显示，而Page类又无法被转化为json，有没有什么办法解决下？还是说我只能重新写一个类来包装一下

**Comment by abel533** [comment]
PageInfo 只是用来参考的，建议自己实现。

**Comment by gs-liut** [comment]
new ArrayList<>(page.getResult())
如果getResult能直接返回List而不是Page就好了，感觉getResult还是返回Page完全没意义

**Comment by abel533** [comment]
@gs-liut Page 和 ArrayList 没什么区别，没必要这么转换。
