### ISSUE TITLE
sqlserver分页时 使用的语句性能很差

### ISSUE THREAD

**Issue by richwxd** [pagehelper/Mybatis-PageHelper#111]
通过druid打印的sql，3万条数据，查询竟然20多秒，太不靠谱了。
执行的类似这样的语句。
select top 20 * from (select row_number()over(order by YearNum DESC,JournalID ASC) as rowid,sJCR.* from searchJCR as sJCR)where rowid not in(select top 20*queryPage  rowid from (select row_number()over(order by YearNum DESC,JournalID ASC) as rowid,sJCR1.* from searchJCR as sJCR1) where 1=1 and ...) and 1=1 and... order by YearNumDESC,JournalID ASC

实际上希望的语句是：
with t_rowtable   
as
(
    select row_number()over(order by YearNum DESC,JournalID ASC) as row_number,* from [JournalDB].[dbo].[searchJCR] where 1=1 

)
select * from t_rowtable where row_number>100
 and row_number <= 60000

我也是看到相同问题，http://blog.csdn.net/danzhang1010/article/details/8909059
我的配置
 <bean class="com.github.pagehelper.PageInterceptor">
                    <property name="properties">
                        <value>
                            helperDialect=sqlserver2012
                            reasonable=true
                            rowBoundsWithCount=true
                            autoRuntimeDialect=true
                        </value>
                    </property>
                </bean>

**Comment by abel533** [comment]
用的分页插件是什么版本？

sqlserver 分页是 `OFFSET ? ROWS FETCH NEXT ? ROWS ONLY`

你发的SQL是针对 2008，2005的。

**Comment by richwxd** [comment]
最新的版本，但是找不到针对sqlserver 2012以后的。 在druid 的stat filter里看到的， 30000条数据，分页查询要20秒。是sqlserver本身分页性能不好吗，感觉以前用oracle, mysql, postgresql都没这个情况呢。
实际情况是确实像那篇博客写的那样，select top性能不给力。

**Comment by abel533** [comment]
你在 `SqlServerDialect` 和 `SqlServer2012Dialect` 中分页SQL的地方断点看看执行的哪个。

**Comment by richwxd** [comment]
又看了一下，这回很奇怪，应该使用的不是offset fetch next only 这样的语句吗，为什么会select top去了. 会不会是这两个互斥
**helperDialect**=sqlserver2012
reasonable=true
rowBoundsWithCount=true
**autoRuntimeDialect**=true

**Comment by abel533** [comment]
会，autoRuntimeDialect 主要是针对多数据源并且是不同类型的数据库时。。

去掉试试。
