### ISSUE TITLE
希望能添加一个getSmartCountSql的开关配置

### ISSUE THREAD

**Issue by MrLiuAAA** [pagehelper/Mybatis-PageHelper#112]
getSimpleCountSql
我在进行分页的时候，如果执行了getSmartCountSql 会把我的order by去除掉，但是这样会给我带来一个问题。我的查询数据就会不准确了。
我的查询中，使用了order by 和 group by 来取最新的一条数据，但是经过了getSmartCountSql 方法以后，我的order by 没有了，group by取到到数据就有问题了。

**Comment by MrLiuAAA** [comment]
getSmartCountSql方法里面的去除order by的方法 不应该采用递归的方式，而应该只出去最外层的order by 。因为去除了 里面order by 很有可能会影响到最终的查询结果。

**Comment by abel533** [comment]
可以在sql中增加注释 `/*keep orderby*/`，发现这个注释就会保留排序。
