### ISSUE TITLE
关于分页查询逻辑问题

### ISSUE THREAD

**Issue by BruceAKABear** [pagehelper/Mybatis-PageHelper#113]
初学者,没怎么阅读源码.
在做分页查询的时候调用静态方法:
`:PageHelper.startPage(page, rows);`
,然后文档说对紧接着的一条查询语句进行分页查询,
1.这样的逻辑是什么?我这条查询语句可以是任意的吗?
2.  List<User> users = userMapper.select(null);  紧跟着分页查询方法的这条语句,从表面上看是查询全部,实际上是进行了分页查询!这里逻辑很绕,要怎么正确理解
3.PageInfo<User> pageInfo = new PageInfo<User>(users); 在这里也不是很明白,既然users,作为分页查询后的分页数据参数传入,那么再次使用pageinfo获取信息时,却能从pageinfo获取数据库中所有数据的条数.逻辑上不直观

**Comment by abel533** [comment]
用的静态ThreadLocal 实现的静态方法调用。
本来返回值是 List，现在成了 Page (extends ArrayList).
可以手动((Page)list).getTotal()，也可以参考 PageInfo 实现个自己的分页类。
