### ISSUE TITLE
PageHelper has a bug when autoDialect

### ISSUE THREAD

**Issue by huicaier** [pagehelper/Mybatis-PageHelper#116]
![227](https://user-images.githubusercontent.com/4612061/30154533-c9507c6e-93ec-11e7-9707-1a0ec4b65ae2.png)
在多线程并发的情况下，autoDialect做为一个全局变量会被设置为不同的值，
1.此时当一个线程改变此变量值，另一个线程还保有原始值就会出现重新获取dialect的可能
2.如果其中一个线程，执行到getDialect()方法的时候，另一个线程可能会直接跳过锁定块哪去dialect，而此时dialect可能为空
问题版本在：4.1.1  
我看作者已经在5.1.1的版本抛弃了SqlUtil的使用方式

**Comment by caishibin** [comment]
原代码中先给autoDialect = false，再调用getDialect()，再高并发会导致空指针异常。应该需要调换代码的顺序。并且autoDialect最好添加volatile修饰。

**Comment by abel533** [comment]
大家可以看看新版本中有没有问题。
