### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by eimsteim** [pagehelper/Mybatis-PageHelper#118]
Liuzh，你好
非常感谢你设计了这么优秀的分页框架，用起来还是十分方便的。不过我在使用中还是有稍许的不便，这里提出两个小建议：
1）pageNum起始值不可定制。pageHelper默认pageNum是从1开始，而我的设计中pageNum是从0开始，如果不可定制的话，意味着我所有的接口方法和C端代码都要修改。
2）count参数定制不太合理。在我的设计中，分页参数（包括：pageNum, pageSize, orderBy等）都是封装在Page对象中，而pageHelper则将其一并放在params中（包含Object对象属性和Page分页属性），这意味着我无法直接使用Object对象作为查询的入参，否则我需要在Object模型中加入相关的分页属性，这样的设计实在是很尴尬。
上面两个问题，可能你已经有了解决方案，但遗憾的是我在文档中似乎没有发现，如果方便的话，请在回复中告知我，非常感谢！

**Comment by abel533** [comment]
0和1的问题你可以封装自己的静态方法，自己转换0和1.

分页插件能从大部分类型中直接获取所有支持的参数值，你可以看看文档中的 `params` 参数。
