### ISSUE TITLE
无法获得最终结果

### ISSUE THREAD

**Issue by jiqimaogou** [pagehelper/Mybatis-PageHelper#119]
PageInfo<Project> projects = PageHelper.startPage(pageNum, pageSize).doSelectPageInfo(
            () -> projectService.findAllProjects(userId, appId));

如果projectService.findAllProjects调用了两个mapper，那么只会把第一次调用mapper返回的数据塞入pageinfo。

**Comment by abel533** [comment]
`doSelectPageInfo`里面的方法应该是dao调用，而不是service，并且只对第一个查询方法进行分页和转换值。
