### ISSUE TITLE
排序移除了，那新的排序插件在哪里？怎么从4.X升级到5.0，还能继续使用排序？

### ISSUE THREAD

**Issue by towangle** [pagehelper/Mybatis-PageHelper#12]

**Comment by njbble** [comment]
@abel533

**Comment by abel533** [comment]
暂时无法用排序。等提供排序插件后在换吧，但是需要注意的是，排序插件不是通过 PageHelper 调用的。

**Comment by njbble** [comment]
你好，请问有计划表吗？目前就差这个排序

**Comment by njbble** [comment]
@abel533

**Comment by abel533** [comment]
本来打算直播的时候写这个插件，由于最近找不到直接能用的直播平台，所以放弃直播，直接开写，这个插件最快在年前能出来。

**Comment by abel533** [comment]
@njbble 新的排序项目：https://github.com/abel533/OrderByHelper
目前就简单功能。

**Comment by QiuMing** [comment]
群主啊，真心觉得移除排序呢功能是个不明智的决定呀，建议群主在考虑一下，整合到分页插件中。如果可以的话，群主可以在群里发个群投票，我相信很多人还是支持两者在一起的。

**Comment by abel533** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/issues/38
