### ISSUE TITLE
数据紊乱

### ISSUE THREAD

**Issue by dingmengyang** [pagehelper/Mybatis-PageHelper#120]
我用了pagehelper和自己写的动态替换表名的拦截器，能够根据传入的id从不同的表中分页查询数据，现在问题是：比如传入id=1，查询1表结果正常，id=2时，返回的list数据正常，但是total和pages还是id=1时的数据，请问怎么在执行一次分页查询后对total，pages进行清理

**Comment by abel533** [comment]
查询方法配置清缓存就行。

**Comment by dingmengyang** [comment]
PageHelper.startPage(1, 10);
    try{
        list = countryMapper.selectAll();
    } finally {
        PageHelper.clearPage();
    }
请问是这样吗，但是没有效果

**Comment by abel533** [comment]
不是这个，是mybatis的`flushCache="true"`

**Comment by dingmengyang** [comment]
我发现问题所在了，pagehelper在我的拦截器替换表名之前就查出了total和pages，我修改原始查询sql的表名后也证实了total和pages和我写在sql的表是一致的，但是拦截器顺序是我的拦截器在前。。。
