### ISSUE TITLE
sqlserver2014 分页出错

### ISSUE THREAD

**Issue by liunewshine** [pagehelper/Mybatis-PageHelper#121]
生成的语句是
`SELECT id,username,password,name,phone,status,profilePhoto FROM UserInfo OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY`
但是OFFSET分页方法要求必须加order by才行,我要手动加入order by?

**Comment by abel533** [comment]
可以直接在sql加排序。。或者分页插件也支持排序，但是需要自己保证排序字段的准确性。

**Comment by liunewshine** [comment]
好的
