### ISSUE TITLE
使用pagehelper5.1.2无效，但是使用4.1.6分页有效

### ISSUE THREAD

**Issue by chanxiaohui** [pagehelper/Mybatis-PageHelper#122]
相关依赖如下
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper</artifactId>
            <version>4.1.6</version>
        </dependency>

**Comment by abel533** [comment]
5.1.1可以直接用对应的starter，如果手动配置，注意看拦截器，和原来的不一样了。
https://github.com/pagehelper/pagehelper-spring-boot

**Comment by xhuichen** [comment]
尝试了5.1.1的starter也是无法生效。
只有手动配置的4.1.6是生效的。
