### ISSUE TITLE
查询mybatis，我传递的是一个map,能否在map中支持分页？

### ISSUE THREAD

**Issue by hubiao1** [pagehelper/Mybatis-PageHelper#123]
queryByPage(Map<String, Object> paramMap);

我在paramMap中给pageNum和pageSize，

我希望能做两个事，
 1：在map时注入总数量
  2：根据map中的给pageNum和pageSize  来支持分页

**Comment by abel533** [comment]
第二个通过`params`参数可以实现，第1个不行。
