### ISSUE TITLE
插件不支持java 8的LocalDateTime啊

### ISSUE THREAD

**Issue by d9577** [pagehelper/Mybatis-PageHelper#124]
当有model中的属性是java 8的LocalDateTime的时候，项目就启动不起来
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.pagehelper.autoconfigure.MapperAutoConfiguration': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: No typehandler found for property created`
使用的版本是5.1.2

**Comment by abel533** [comment]
添加官方日期时间依赖了？

**Comment by d9577** [comment]
不用添加依赖的吧？这是java8新增的时间库，只要jdk是8然后ide的环境也设置成java 8 就可以用了的吧

**Comment by abel533** [comment]
你可能不知道有这个：
https://github.com/mybatis/typehandlers-jsr310

**Comment by d9577** [comment]
原来是这样，感谢！
