### ISSUE TITLE
sqlsever分页查询很慢大约3分钟，但里面的数据sql只需要7s。

### ISSUE THREAD

**Issue by liuyb4016** [pagehelper/Mybatis-PageHelper#125]
sqlserver 数据库。
整个sql如下：
`SELECT
	TOP 10 ORDERS_ID,
	CODE
FROM
	(
		**SELECT DISTINCT
			ROW_NUMBER () OVER (ORDER BY o.CREATE_DATE DESC) PAGE_ROW_NUMBER,
			o.ORDERS_ID,
			CODE
		FROM
			orders o
		LEFT JOIN (
			SELECT DISTINCT
				orders_id
			FROM
				orderitems
			WHERE
				is_valid = 0
			AND oper_id IS NULL
		) oi ON o.orders_id = oi.orders_id
		LEFT JOIN member_user u ON u.id = o.USERS_ID
		WHERE
			o.STATUS = 7
		AND o.IS_PRINT = 0
		AND (
			o.orders_id IN (
				SELECT DISTINCT
					oi1.orders_id
				FROM
					orderitems oi1
				LEFT JOIN show_group sg ON sg.id = oi1.showgroupid
				WHERE
					oi1.is_valid = 0
				AND oi1.oper_id IS NULL
				AND (
					SELECT
						dbo.Label_Search (2122, sg.appoint_agent, ',')
				) > 0
			)
			OR (o.agent_Id = 2122)
		)
		AND TICKET_WAY = 1
		AND oi.orders_id IS NOT NULL**
	) AS PAGE_TABLE_ALIAS
WHERE
	PAGE_ROW_NUMBER > 0
ORDER BY
	PAGE_ROW_NUMBER`

执行下来大概要3分钟。但from里面的执行下来只需要7s。主表数据大约10w条。其他数据很小.

from里面的sql
  ` SELECT DISTINCT ROW_NUMBER () OVER (ORDER BY o.CREATE_DATE DESC) PAGE_ROW_NUMBER, o.ORDERS_ID, CODE FROM orders o LEFT JOIN ( SELECT DISTINCT orders_id FROM orderitems WHERE is_valid = 0 AND oper_id IS NULL ) oi ON o.orders_id = oi.orders_id LEFT JOIN member_user u ON u.id = o.USERS_ID WHERE o.STATUS = 7 AND o.IS_PRINT = 0 AND ( o.orders_id IN ( SELECT DISTINCT oi1.orders_id FROM orderitems oi1 LEFT JOIN show_group sg ON sg.id = oi1.showgroupid WHERE oi1.is_valid = 0 AND oi1.oper_id IS NULL AND ( SELECT dbo.Label_Search (2122, sg.appoint_agent, ',') ) > 0 ) OR (o.agent_Id = 2122) ) AND TICKET_WAY = 1 AND oi.orders_id IS NOT NULL`

有点奇怪哦。请帮我分析一下。谢谢

**Comment by liuyb4016** [comment]
from 里面的sql ` SELECT DISTINCT ROW_NUMBER () OVER (ORDER BY o.CREATE_DATE DESC) PAGE_ROW_NUMBER, o.ORDERS_ID, CODE FROM orders o LEFT JOIN ( SELECT DISTINCT orders_id FROM orderitems WHERE is_valid = 0 AND oper_id IS NULL ) oi ON o.orders_id = oi.orders_id LEFT JOIN member_user u ON u.id = o.USERS_ID WHERE o.STATUS = 7 AND o.IS_PRINT = 0 AND ( o.orders_id IN ( SELECT DISTINCT oi1.orders_id FROM orderitems oi1 LEFT JOIN show_group sg ON sg.id = oi1.showgroupid WHERE oi1.is_valid = 0 AND oi1.oper_id IS NULL AND ( SELECT dbo.Label_Search (2122, sg.appoint_agent, ',') ) > 0 ) OR (o.agent_Id = 2122) ) AND TICKET_WAY = 1 AND oi.orders_id IS NOT NULL`

**Comment by liuyb4016** [comment]
版本是3.7.3。请作者大大帮我分析一下

**Comment by liuyb4016** [comment]
用的是sqlserver2012.    我按照offset fecth next 也很慢、

**Comment by sombre** [comment]
可读性这么差的sql,你是怎么维护的..- -.10W条数据量查询下来要7S..赶紧优化吧.
