### ISSUE TITLE
pageInfo 传入普通list<T>进行分页，全部页数等于1？

### ISSUE THREAD

**Issue by zhuyx808** [pagehelper/Mybatis-PageHelper#126]
pageInfo代码中126行 128行 
`this.pageSize = list.size(); this.pages = this.pageSize > 0 ? 1 : 0;`
每页数量为传入的list的容量。
如果每页数量大于0，则总页数为1？

项目中统一使用了这个pageInfo对象进行包装，普通list对象也要进行相应转换，从代码来看这个地方是有点问题的吧。。。

**Comment by abel533** [comment]
对普通的List就是做了个简单处理。

建议根据自己需要设计自己的 `PageInfo` 类，分页插件提供的是用于参考的。
