### ISSUE TITLE
反射方式调用mapper,用PageHelper.start()开启之后,只执行select count方法

### ISSUE THREAD

**Issue by MiniPa** [pagehelper/Mybatis-PageHelper#127]
反射方式调用mapper,用PageHelper.start()开启之后,只执行select count方法,
代码：

    SqlSession sqlSession = MybatisHelper.getSqlSession();
    Class mapper_clz = Class.forName(mapper的class);
    Mapper mapper = (Mapper) sqlSession.getMapper(mapper_clz);
   /*得到mapperProxy代理对象*/

    Method mapper_method = mapper.getClass().getMethod("users", new Class[]{Map.class});
    PageHelper.startPage(1, 10);
    return (List<Object>) mapper_method.invoke(mapper, params);

Mapper：
  List<Map<String,String>> users(Map<String,String> params);

XML:
  <select id="users" parameterType="Map" resultType="map">
    SELECT
    <include refid="Base_Column_List"/>
    FROM u_user u
    WHERE 1=1
    <if test="username != null">
      AND u.username = #{username}
    </if>
  </select>

执行sql：
Preparing: SELECT count(0) FROM u_user u WHERE 1 = 1 AND u.username = ? 

疑问? 这里普通方式可以完成分页插件,反射就不行了,有空的话麻烦指点下,
项目github 代码:
https://github.com/MiniPa/cjs_ssms/blob/master/cjs_ssms_web/src/main/java/com/chengjs/cjsssmsweb/service/common/ISelectService.java

**Comment by abel533** [comment]
我找时间写个反射调用的测试试试。

**Comment by zhoujimmy** [comment]
![image](https://user-images.githubusercontent.com/43661888/113386540-111ac080-93bd-11eb-8043-4f5b49e6a281.png)
`    private Object dynamicInvoke(String targetMethod, Method method, Object mapper, Object target) throws InvocationTargetException, IllegalAccessException {
        PageHelper.startPage(1,20);
        switch (targetMethod){
            case INSERT_METHOD:
            case UPDATE_METHOD:
            case DELETE_METHOD:
                return method.invoke(mapper, target);
            case GET_METHOD:
                return method.invoke(mapper, genWrapper(target));
            case SELECT_METHOD:
                return new PageInfo((List)method.invoke(mapper, genWrapper(target)));
        }
        return null;
    }`

我刚才也碰到了类似的情况，以上的代码就可以解决问题
原因是PageHelper的PageNo和PageSize是放在threadlocal里面的
执行完select count之后会从threadlocal里面获取分页的信息，进行下一步操作
因为没有从threadlocal获取到，所以导致了sql执行直接跳过，返回空数组的问题。

但是为什么没有从threadlocal获取到这一点我也不太清楚，怀疑可能是

还有Mapper通过SpringIOC进行获取，不要自己反射生成

**Comment by DJ-KONG** [comment]
我在5.3.0版本开始出现类似的情况，但我没用反射，而是直接调用通用mapper.seletc(T)的方法，结果只执行select cont(0),后面的就不执行了。导致数据返回空。mybaties 3.5.9，mapper4.2.1
