### ISSUE TITLE
junit可以使用，但是tomcat启动不行

### ISSUE THREAD

**Issue by Paul0523** [pagehelper/Mybatis-PageHelper#128]
使用的插件是5.1.2，使用junit测试的时候没有什么问题，但是使用tomcat启动的时候报org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoClassDefFoundError: com/github/pagehelper/PageHelper，请问下这个怎么解决？

**Comment by abel533** [comment]
找不到类，看项目Lib下面有没有jar包。

**Comment by Paul0523** [comment]
@abel533 打包试了下没问题，应该是idea配置有点问题，我看下，谢谢了。
