### ISSUE TITLE
自己重封装对象后total等信息丢失，是查询的List为Page对象的原因、是不是可以做些优化

### ISSUE THREAD

**Issue by chenghm123** [pagehelper/Mybatis-PageHelper#131]
new PageInfo的时候只要是当前线程、就能构建分页信息？

**Comment by abel533** [comment]
得到Page后，自己处理数据返回。。和PageInfo没关系。

**Comment by 937447974** [comment]
@abel533 物理分页，没有其他要求，推荐使用哪种方案呢，需要保证线程安全？

**Comment by abel533** [comment]
@937447974 如果不能保证PageHelper静态方法正确调用就用参数方式，还可以用RowBounds参数（PageRowBounds）。
Pagehelper 也提供了安全的静态方法，参考更新日志中的`ISelect`。

**Comment by 937447974** [comment]
@abel533 你好，我想像你一样发布一个项目到 http://mvnrepository.com。网上搜索不到这方面的资料，能推荐一下文章吗？谢谢！

**Comment by abel533** [comment]
@937447974 https://my.oschina.net/huangyong/blog/226738

**Comment by 937447974** [comment]
@abel533 你好，我打包的时候发现了这样一个错误。
gpg: signing failed: Inappropriate ioctl for device
gpg的钥匙串我已经生成了，但是怎么和maven关联起来不是很明白。能说一下吗？谢谢

**Comment by abel533** [comment]
试试纯命令方式：
mvn clean deploy -P release -Dgpg.passphrase=密码

**Comment by 937447974** [comment]
明白了，原来我是通过 brew 装的gpg。实际它需要gpg2的命令，因为我的插件使用的是最新版。我去官网下了一个gpg2的命令就可以了。
