### ISSUE TITLE
PageInterceptor 在进行分页查询执行count时会有问题

### ISSUE THREAD

**Issue by wywanchongshan** [pagehelper/Mybatis-PageHelper#134]
在PageInterceptor 拦截器中，如果需要执行count时，生成的count countMsId时代码如下所示：
```java
//判断是否需要进行 count 查询
                if (dialect.beforeCount(ms, parameter, rowBounds)) {
                    String countMsId = msId + countSuffix;
                     .........
                }
```
而countSuffix 的值的定义是：  private String countSuffix = "_COUNT";
当进入count sql查询时，还会进入PageInterceptor 拦截器，这时会执行：
```java
          //调用方法判断是否需要进行分页，如果不需要，直接返回结果
            if (!dialect.skip(ms, parameter, rowBounds)) {........}
dialect我会用的是默认的  private String default_dialect_class = "com.github.pagehelper.PageHelper";
```
这时，我们看到PageHelper的skip的实现发现：
```java
@Override
    public boolean skip(MappedStatement ms, Object parameterObject, RowBounds rowBounds) {
        if(ms.getId().endsWith(MSUtils.COUNT)){
            throw new RuntimeException("在系统中发现了多个分页插件，请检查系统配置!");
        }
        Page page = pageParams.getPage(parameterObject, rowBounds);
        if (page == null) {
            return true;
        } else {
            //设置默认的 count 列
            if(StringUtil.isEmpty(page.getCountColumn())){
                page.setCountColumn(pageParams.getCountColumn());
            }
            autoDialect.initDelegateDialect(ms);
            return false;
        }
    }
```
第一句就是这个判断 ： `ms.getId().endsWith(MSUtils.COUNT)；`  而MSUtils.COUNT的值是 “_COUNT”，而count语句生成的countMsId 的值的后缀也是“_COUNT”,所以在PageHelper里面就会抛出异常："在系统中发现了多个分页插件，请检查系统配置!"

**Comment by wywanchongshan** [comment]
我使用的是PageHelper 5.1.2版本，mave中最新的版本，我看5.1.2-beta里面也是这种写法

**Comment by JustZzzxf** [comment]
+1

**Comment by abel533** [comment]
分页插件的中执行count查询时，不会再次进入拦截器中。除非你配置了多个重复的分页拦截器。

**Comment by wywanchongshan** [comment]
我没有重复配置的，我使用的是spring boot，仅仅在application.properties里面加入如下配置，具体配置如下所示：
`
############################################### 
## 分页插件配置 PageHelperAutoConfiguration 类使用 
###############################################
# 默认的分页处理类
pagehelper.dialect = com.github.pagehelper.PageHelper
# 分页count执行时的，Mappre.xml后缀
pagehelper.countSuffix = Count 
#该参数默认为false 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用 和startPage中的pageNum效果一样
pagehelper.offsetAsPageNum = true 
# 该参数默认为false 设置为true时，使用RowBounds分页会进行count查询
pagehelper.rowBoundsWithCount = true 
# 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果 （相当于没有执行分页查询，但是返回结果仍然是Page类型）
pagehelper.pageSizeZero = false 
# 3.3.0版本可用 - 分页参数合理化，默认false禁用 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
pagehelper.reasonable = true
`

sql mapper config中没有增加分页插件，仅仅使用PageHelper与spring boot集成时，通过对PageHelperAutoConfiguration 类的配置让PageHelper分页插件生效

**Comment by abel533** [comment]
能不能简化个DEMO发一下？

**Comment by wywanchongshan** [comment]
由于自建的项目是慢慢改进的，中间过程已经忘记是什么样的了。有可能那段时间是正在看那老的文档4X版本的，那时配置插件时还是在 Mybatis-Configu.xml 中 
`<plugin interceptor="com.github.pagehelper.PageHelper">`
这种方式配置。

       而现在该类已经变成dialect,拦截器  com.github.pagehelper.PageInterceptor，新的配置了。有可能在改进的过程中，同时使用了Mybatis-configu.xml这种xml文件的配置和spring boot 属性文件的配置，当时将Mybatis-configu.xml这种xml文件的配置插件的代码注释掉时，有可能重启项目时，新的修改配置没有载入进去，还是老的Mybatis-configu.xml，可能导致了出现两次配置。

     现在我用最新的项目中配置信息，把下面这个配置注释掉
`# 分页count执行时的，Mappre.xml后缀
pagehelper.countSuffix = Count`
已经复现不出来了。

      我跟踪代码时发现，查执行分页查询时，在进入PageInterceptor的intercept 方法时，ibatis.executor 的执行类是代理类，拦截器会生效，所以会进入intercept里面来。面后面在执行分页查询的count方法时，是直接
`Executor executor = (Executor) invocation.getTarget();`
用这个执行类处理的，这样处理后获取的ibatis.executor 的执行sql时，是实际的执行类对象，没有代理处理。而后缀的count方法执行时，也是在该执行类上执行的，理论上应该是不会再进入PageInterceptor的intercept 方法的，所以现在我复现不出来我的问题了
