### ISSUE TITLE
Oracle分页时伪列bug

### ISSUE THREAD

**Issue by SunTowJ** [pagehelper/Mybatis-PageHelper#135]
Oracle分页时是在数据集的基础上添加了虚拟表，如下
![1](https://user-images.githubusercontent.com/8315662/32259374-070e2518-befb-11e7-9afe-dcefbe9c55ab.png)
当我查询第一页数据时，
![2](https://user-images.githubusercontent.com/8315662/32259604-9c392290-befc-11e7-83b7-e5d5ce8b0455.png)
,但是结果集应该是
![3](https://user-images.githubusercontent.com/8315662/32259609-a101dd76-befc-11e7-8efe-7b64a74a4b90.png)

注意框出来的id排序，出现数据错乱与丢失状况

**Comment by SunTowJ** [comment]
偶现 ，大概3个月遇到两次。另外，不是数据丢失 而是数据混乱

**Comment by abel533** [comment]
建议再增加排序条件试试。

**Comment by SunTowJ** [comment]
@abel533 排序条件是业务需要无法添加，另外我添加了一个试了下还是乱的。应该跟伪列有关。还有就是如果加上ROWNUM > 0 则顺序保持一致。

**Comment by abel533** [comment]
@SunTowJ 套两层是正常的？一层的有问题？

**Comment by SunTowJ** [comment]
@abel533 其实都有问题，但是在如果条件修改为 ROWNUM > 0 AND ROWNUM<=20 这样的话 就都不存在问题。

**Comment by SunTowJ** [comment]
@abel533  套两层就不存在问题了。我发现这个情况就是我第20条数据与21条数据比如是A、B  但是在第一页查询的时候因为是一层，然后排序查出来最后一条是B。然后第二页查询是正常的，所以第一条就是B 。导致我展现的时候重复了。才发现这个问题。所以就是如果不加上ROWNUM > 0 它的排序会混乱

**Comment by abel533** [comment]
这个问题会尽快改。
