### ISSUE TITLE
增加手写 count 查询支持--无法执行自己手写的COUNT

### ISSUE THREAD

**Issue by iamjuzi** [pagehelper/Mybatis-PageHelper#136]
刚开始用这个插件，还不太熟悉，对于手写count查询这里我是根据更新日志中的信息首先在配置文件中增加：
property name="countSuffix " value="_COUNT"
（上面参数的添加是我自己的理解，不知道对不对。）
映射文件中的id="xxxxx_COUNT"中的sql的结构为 select count(0) from (里面是一些复杂的表关联sql查询)。在执行时我看了下后台打印的SQL还是执行了默认的的count并没有执行我自己写的count查询。是我配置的有错误吗？谢谢。

**Comment by iamjuzi** [comment]
上述问题已解决！

**Comment by cranehe** [comment]
请问这个问题解决的细节是如何做的？

**Comment by Nowforpasserby** [comment]
??? 遇到同样的问题,求解决方案@iamjuzi
