### ISSUE TITLE
关于PageInfo中的firstPage和lastPage

### ISSUE THREAD

**Issue by aNightCat** [pagehelper/Mybatis-PageHelper#137]
PageInfo对象中的get/setFirstPage()和get/setLastPage()方法，虽然添加了@Deprecated标注过时，但是在json格式输出或者@RestController中返回PageInfo对象，仍会将错误的firstPage和lastPage值输出，是否将这几个方法删除或者设置正确的值更好？
![image](https://user-images.githubusercontent.com/17309471/32480614-a57e443e-c3ca-11e7-887f-89942647910f.png)
![image](https://user-images.githubusercontent.com/17309471/32480622-ade18140-c3ca-11e7-80a8-9b6e4545cca5.png)
![image](https://user-images.githubusercontent.com/17309471/32480646-c9e242bc-c3ca-11e7-99fb-174446d16066.png)
![image](https://user-images.githubusercontent.com/17309471/32480663-e2a1d1a0-c3ca-11e7-947f-15e9ac3694c9.png)
![image](https://user-images.githubusercontent.com/17309471/32480703-1223dab8-c3cb-11e7-9c3e-ec5e08e24744.png)
![image](https://user-images.githubusercontent.com/17309471/32480696-06177aae-c3cb-11e7-9815-7b7285aa6fd0.png)

**Comment by abel533** [comment]
我个人不推荐用PageInfo，因为包含了太多属性，不一定用得到，根据自己需要封装会更好。
