### ISSUE TITLE
建议分页类使用spring-data-commons

### ISSUE THREAD

**Issue by blooming** [pagehelper/Mybatis-PageHelper#139]
spring-data-commons中已经抽象了Page , Pageable等对象
spring-data-jpa , spring-data-mongodb等工程全都使用spring-data-commons中的这些对象
内置了PageableHandlerMethodArgumentResolver等实用功能
可以直接从controller的参数中解析出分页请求
建议咱这个项目中的分页对象直接使用spring-data-commons中的
与大厂保持一致

**Comment by abel533** [comment]
spring自己的可以随便依赖。

如果这里这么依赖，即使不用Spring也需要依赖Spring的东西，没什么必要。

**Comment by neXtack** [comment]
建议对pagehelper的Page进行抽象，从而能够适配

**Comment by blooming** [comment]
@abel533 spring-data-common是一个独立的包，本身不依赖spring的IoC和AOP框架。spring-data-common抽象了大量常用的DAO框架所需的基础功能。
