### ISSUE TITLE
想支持Teradata数据库的分页，如何自定义一个Parser

### ISSUE THREAD

**Issue by sunandy3** [pagehelper/Mybatis-PageHelper#14]
想支持Teradata数据库的分页，如何自定义一个Parser

**Comment by abel533** [comment]
如果是5.0版本，就继承`AbstractHelperDialect`，参考其他几个实现类就可以。然后配置 helperDialect 为你实现类的全限定名称即可。

**Comment by sunandy3** [comment]
我当前用的还是4.1.1版本，是否继承AbstractParser就可以了。
比如我的类名叫TeradataParser，在配置plugin的properties时候，dialect=teradata， 对吗？

**Comment by abel533** [comment]
自己实现的必须写类的全名。如果你没有用到分页插件的排序功能，建议你升级到 5.0.0 试试。

**Comment by abel533** [comment]
Teradata 数据库分页实现了吗？能不能分享一份，直接加到下个版本中。

**Comment by BluesTroy** [comment]
请问 Teradata 数据库分页实现了吗?我也需要teradata实现分页

**Comment by abel533** [comment]
@BluesTroy 你可以提供一个实现吗？
