### ISSUE TITLE
关联查询有collocation集合时，返回结果不对怎么解决

### ISSUE THREAD

**Issue by zhengliwu1989** [pagehelper/Mybatis-PageHelper#143]
当用分页插件关联查询时，有collocation集合时，返回结果不对怎么解决

**Comment by abel533** [comment]
不支持一对一一对多的结果映射。。

手动对主表进行分页。

**Comment by BigBroB** [comment]
@abel533 争对这种情况，有没有可能通过控制 `ThreadLocal<Page> `参数来达到结果？  
比如 通过 mapper 的方法名 判断该select方法 是不是 关联查询 ，主查询后 将 `ThreadLocal<Page> ` 清空，来避免后续查询？

**Comment by abel533** [comment]
@BigBroB 没必要对不该用的地方增加太复杂的逻辑。

**Comment by glenn2wang** [comment]
更换使用collection方法即可，可参考如下地址用法
http://blog.csdn.net/mamba10/article/details/20927225
