### ISSUE TITLE
请问对redis支持如何?

### ISSUE THREAD

**Issue by Youngffon** [pagehelper/Mybatis-PageHelper#144]
最近项目使用到redis，导致我们的分页插件失效，只能查出第一页数据。请问PageHelper对Redis的支持如何?

**Comment by abel533** [comment]
和redis没任何关系。

**Comment by Light-k** [comment]
> 最近项目使用到redis，导致我们的分页插件失效，只能查出第一页数据。请问PageHelper对Redis的支持如何?

我也遇到了  请问下你怎么解决的呀   我用的是window版的redis
