### ISSUE TITLE
count优化问题

### ISSUE THREAD

**Issue by dengchq** [pagehelper/Mybatis-PageHelper#146]
为什么我分页时获取count总数时是select count（0） from （select * from table ....），这样有些查询效率很低，有其他的解决办法么？

**Comment by abel533** [comment]
特殊SQL（查询列有函数）或者无法解析时会用嵌套方式。

**Comment by dengchq** [comment]
那关于这个能不能优化呢，或者自定义

**Comment by abel533** [comment]
可以自定义，看这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#504---2017-08-01

**Comment by dengchq** [comment]
谢谢 @abel533
