### ISSUE TITLE
MySQL全文检索报错

### ISSUE THREAD

**Issue by Dhweicheng** [pagehelper/Mybatis-PageHelper#147]
在全文检索中使用排序报错
--------------------------
MySQL 5.7
MyBatis 3.4.1
-----------------------
JAVA 代码
PageHelper.orderBy("id  DESC");
-----------------------------------
SQL片段
       <if test="keyWords != null">
                AND  MATCH (title,content) AGAINST (#{keyWords, jdbcType=VARCHAR} IN NATURAL LANGUAGE MODE)
       </if>
---------------------------------------
异常
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "AGAINST "" 
--------------------------------------------------------------------------------------------

**Comment by abel533** [comment]
jsqlparser 不支持，解析失败，不能处理这种排序

**Comment by onvertex** [comment]
你好 楼主 解决了吗

**Comment by Dhweicheng** [comment]
> 你好楼主解决了吗

当时的做法是在做关键词搜索的时候，不进行执行
