### ISSUE TITLE
springboot工程打war包部署时，分页插件sql拼接错误

### ISSUE THREAD

**Issue by veritasw** [pagehelper/Mybatis-PageHelper#148]
本地开发时跑main函数和测试环境jar包部署都正常，但是生产环境部署成war包时却出现了sql拼接错误的问题。具体错误是："LIMIT ？"在末尾重复追加了多次。

**Comment by abel533** [comment]
只有配置了多次分页插件时，才会出现这种情况，你看看项目lib目录对不对。

**Comment by veritasw** [comment]
配置了多次是指啥？说下我的项目结构吧，我猜测可能和这个有关。部署成war包的springboot工程是依赖多个打成jar包的springboot工程的，而分页插件是这些jar包的公共依赖（类似于common.jar）的依赖。不知道你说的配置了多次是不是这层意思。
