### ISSUE TITLE
JRebel重新加载导致分页失效

### ISSUE THREAD

**Issue by flashing** [pagehelper/Mybatis-PageHelper#15]
IDEA 2016.3.3 + JRebel 7.0.2 + SpringBoot 1.4.3 + SpringBoot的插件
这个模式下，Jrebel模式重新编译代码，会导致PageHelper的分页查询直接失效。
目前在多台机器上都100%存在这个问题。

**Comment by abel533** [comment]
错误信息或者现象是什么？

**Comment by flashing** [comment]
过年抽时间看了一下，刚才升级到
IDEA 2016.3.4 + JRebel 7.0.3 + SpringBoot 1.4.4
现象消失，过年开工后再观察一下。
之前的现象就是比如：
        int pageSize = Constants.getSystemConfig().getPageSize();
        //pageSize = 2;
        PageInfo<BookStoreDTO> page = PageHelper.startPage(pageNumber, pageSize).doSelectPageInfo(() -> bookStoreMapper.findBookStoreList());
        model.addAttribute("page", page);
当我为了测试分页条样式，修改pageSize的值的时候，出现编译并加载之后无效的情况。目前我在观察一下。

**Comment by fandro** [comment]
我也遇到这样的问题

**Comment by AlexanLee** [comment]
同样的问题。。
