### ISSUE TITLE
好像和activiti工作流引擎不能兼容？

### ISSUE THREAD

**Issue by drchen00** [pagehelper/Mybatis-PageHelper#152]
使用activiti的查询时分页插件貌似会失效

**Comment by abel533** [comment]
和这个问题有没有联系：https://github.com/abel533/MyBatis-Spring-Boot/issues/87

**Comment by drchen00** [comment]
找到原因了，使用activiti做复杂查询貌似activiti底层会做多次查询还是老老实实用pagelist函数算了
