### ISSUE TITLE
spring boot 配置多数据源，PageHelper报空指针

### ISSUE THREAD

**Issue by cmontxgt** [pagehelper/Mybatis-PageHelper#153]
spring boot 配置了多个数据源时，手动分页时。报空指针异常。pageHelper版本4.16。望回复

**Comment by abel533** [comment]
光凭这么一句话什么都解决不了。

为啥不把最重要的异常贴出来呢？

**Comment by cmontxgt** [comment]
已经解决了，跟 了下源代码。是因为page和pageSize传的参数为空了
