### ISSUE TITLE
插件是否支持mybatis动态表名的查询分页

### ISSUE THREAD

**Issue by happytan555** [pagehelper/Mybatis-PageHelper#154]
在项目中由于查询表名必须动态生成，所以mapper.xml中只能使用非预编译模式动态输入表名（表名和查询参数都是使用map传入的），我在尝试使用4.1.6版本的分页插件的时候总是不成功，抛出的异常显示sql语句有问题，原始sql语句后面跟着一个“limit ?,?”，导致sql执行错误。
       对于这种动态传入表名的非预编译模式应用，是否有支持的办法？

**Comment by abel533** [comment]
动态表名`${tableName}` 这种也能选择预编译方式。
