### ISSUE TITLE
PageHelper.orderBy 打出异常日志

### ISSUE THREAD

**Issue by macazy** [pagehelper/Mybatis-PageHelper#155]
不止一次遇到这个问题~~

以下是调用方法名及调用参数

com.github.pagehelper.parser.OrderByParser.converToOrderBySql(String sql, String orderBy)

sql:
`SELECT
			orders.orderId AS 'orders_orderId',
			orders.userId AS 'orders_userId',
			orders.amount AS 'orders_amount',
			orders.currencyCode AS 'orders_currencyCode',
			orders.paymentDate AS 'orders_paymentDate',
			orders.paymentMethod AS 'orders_paymentMethod',
			orders.paymentStatus AS 'orders_paymentStatus',
			orders.remarks AS 'orders_remarks',
			orders.`status` AS 'orders_status',
			orders.createdBy AS 'orders_createdBy',
			orders.updatedBy AS 'orders_updatedBy',
			orders.createdOn AS 'orders_createdOn',
			orders.updatedOn AS 'orders_updatedOn',
			useraccount.userId AS 'useraccount_userId',
			useraccount.partyId AS 'useraccount_partyId',
			useraccount.username AS 'useraccount_username',
			useraccount.email AS 'useraccount_email',
			useraccount.mobileNo AS 'useraccount_mobileNo',
			useraccount.nickname AS 'useraccount_nickname',
			useraccount.avatarUrl AS 'useraccount_avatarUrl',
			useraccount.openId AS 'useraccount_openId',
			useraccount.unionId AS 'useraccount_unionId',
			useraccount.userLevel AS 'useraccount_userLevel',
			useraccount.userType AS 'useraccount_userType',
			useraccount.systemId AS 'useraccount_systemId',
			useraccount.`status` AS 'useraccount_status',
			useraccount.createdOn AS 'useraccount_createdOn',
			useraccount.updatedOn AS 'useraccount_updatedOn',
			consultant.consultantId AS 'consultant_consultantId',
			consultant.partyId AS 'consultant_partyId',
			consultant.agencyId AS 'consultant_agencyId',
			(SELECT IF(?='en',party.partyNameEn,party.partyName) FROM party WHERE party.partyId = consultant.partyId) AS 'consultant_consultantName',
			orderitem.orderId AS 'orderItemSummary_orderId',
			orderitem.itemId AS 'orderItemSummary_itemId',
			orderitem.parentItemId AS 'orderItemSummary_parentItemId',
			orderitem.consultantId AS 'orderItemSummary_consultantId',
			orderitem.productId AS 'orderItemSummary_productId',
			orderitem.productType AS 'orderItemSummary_productType',
			orderitem.price AS 'orderItemSummary_price',
			orderitem.quantity AS 'orderItemSummary_quantity',
			(SELECT IF(?='en',product.productNameEn,product.productName) FROM product WHERE product.productId = orderitem.productId) AS 'orderItemSummary_productName',
			component.orderId AS 'component_orderId',
			component.itemId AS 'component_itemId',
			component.parentItemId AS 'component_parentItemId',
			component.consultantId AS 'component_consultantId',
			component.productId AS 'component_productId',
			component.productType AS 'component_productType',
			component.price AS 'component_price',
			component.quantity AS 'component_quantity',
			(SELECT IF(?='en',product.productNameEn,product.productName) FROM product WHERE product.productId = component.productId) AS 'component_productName'
		FROM
			orders
		LEFT JOIN useraccount ON useraccount.userId = orders.userId
		LEFT OUTER JOIN orderitem ON orderitem.orderId = orders.orderId AND orderitem.parentItemId = 0
		LEFT JOIN consultant ON consultant.consultantId = orderitem.consultantId
		LEFT OUTER JOIN orderitem component ON component.orderId = orders.orderId AND component.parentItemId = orderitem.itemId
		WHERE
			1 = 1
		AND
			orders.orderId IN
		  (  
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  , 
		 	?
		  )`

orderby:`orders_orderId desc`

**Comment by macazy** [comment]
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " <S_CHAR_LITERAL> "\'orders_orderId\' "" at line 2, column 22.
Was expecting one of:
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "END" ...
    "OPEN" ...
    "TABLE" ...
    "XML" ...
    "VALUE" ...
    "INSERT" ...
    "VALUES" ...
    "REPLACE" ...
    "TRUNCATE" ...
    "CAST" ...
    "OVER" ...
    "PARTITION" ...
    "EXTRACT" ...
    "MATERIALIZED" ...
    "PRIOR" ...
    "SIBLINGS" ...
    "COLUMN" ...
    "NULLS" ...
    "FIRST" ...
    "LAST" ...
    "ROWS" ...
    "RANGE" ...
    "FOLLOWING" ...
    "ROW" ...
    "COMMIT" ...
    "SEPARATOR" ...
    "CASCADE" ...
    "NO" ...
    "ACTION" ...
    <K_DATETIMELITERAL> ...
    "PRECISION" ...
    <S_IDENTIFIER> ...
    <S_QUOTED_IDENTIFIER> ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16395)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16248)
	at net.sf.jsqlparser.parser.CCJSqlParser.RelObjectName(CCJSqlParser.java:1883)
	at net.sf.jsqlparser.parser.CCJSqlParser.Alias(CCJSqlParser.java:2989)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectExpressionItem(CCJSqlParser.java:2869)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:2955)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:2804)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2431)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:2579)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2336)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2328)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:129)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 76 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_CHAR_LITERAL> "\'orders_orderId\' "" at line 2, column 22.`

**Comment by macazy** [comment]
对不起 不太懂 格式应该怎么写

**Comment by macazy** [comment]
`public GenericPage<OrderSummary> pageOrderSummary(OrderPagingCriteria criteria) {
		PageHelper.startPage(criteria.getPageNo(), criteria.getPageSize());
		Page<Integer> orderIdPage = (Page<Integer>) listOrderIds(criteria);
		List<OrderSummary> orderSummaries = new ArrayList<OrderSummary>();
		if (orderIdPage.getResult().size() != 0) {
			criteria.setOrderIds(orderIdPage.getResult());
			PageHelper.orderBy(StringUtils.isBlank(criteria.getOrderBy()) ? "`orders.orderId` desc" : criteria.getOrderBy());
			orderSummaries = listOrderSummary(criteria);
		}
		GenericPage<OrderSummary> genericPage = new GenericPage<OrderSummary>(criteria);
		genericPage.setList(orderSummaries);
		genericPage.setTotalCount((int) orderIdPage.getTotal());
		return genericPage;
	}`

**Comment by abel533** [comment]
复杂SQL解析会失败，失败就没法排序。。复杂情况下还是手写吧。
