### ISSUE TITLE
分页插件支持的数据库中包含自定义的数据库

### ISSUE THREAD

**Issue by sevenFire** [pagehelper/Mybatis-PageHelper#156]
连接的数据库有可能是postgresql、mysql，以及自定义的数据库。自定义数据库的分页sql语句有自己的语法，请问pageHelper是否支持这种场景：同时支持这三种数据库呢？

**Comment by abel533** [comment]
支持。。文档有详细说明。

**Comment by sevenFire** [comment]
我指的是同时支持，不是分别支持。就是连接的数据库会在三种数据库之间切换，服务并没有重启。
使用场景是：有一个页面，可以配置数据库信息和sql语句，点击执行，会查询出改数据库下的结果。我看到代码里只会为第一次遇到的数据库生成sqlUtil。

**Comment by abel533** [comment]
自定义这个现在还没法自动识别，其他常见的可以同时支持。

**Comment by abel533** [comment]
**增加功能：允许配置自动识别的jdbcurl**

**Comment by abel533** [comment]
5.1.3 版本增加 dialectAlias 参数，允许配置自定义实现的 别名，可以用于根据JDBCURL自动获取对应实现，允许通过此种方式覆盖已有的实现，配置示例如：
```xml
<property name="dialectAlias" value="oracle=com.github.pagehelper.dialect.helper.OracleDialect"/>
```
