### ISSUE TITLE
Problems brought by setting the property of 'supportMethodsArguments' to 'true'!

### ISSUE THREAD

**Issue by liushirong** [pagehelper/Mybatis-PageHelper#158]
Background:
 	It is happened in a collaborative project.

 Scene:
 	My companion implements paging by hand.Write a count method and a real  query method.The method params are 'page'、'pageSize'、‘pageNum’ and so on.But I implement paging by the plug of PageHelper.I copy the config on line.

config:
        `PageInterceptor` `pageInterceptor` `=` `new` `PageInterceptor();`
        `Properties` `props` `=` `new` `Properties();`
        `props.setProperty("reasonable",` `"true");`
        `props.setProperty("supportMethodsArguments",` `"true");`
        `props.setProperty("returnPageInfo",` `"check");`
        `props.setProperty("params",` `"count=countSql");`
        `pageInterceptor.setProperties(props);`
        `sessionFactory.setPlugins(new` `Interceptor[]` `{` `pageInterceptor});`

Problems:
       My paging method is normal,but my companion's paging method throws "index out of bounds Exception".I set  the property of 'supportMethodsArguments' to 'true' so that my companion's is intercepted by 'PageHelper' plugin.

Desires:
      If I set the property of 'supportMethodsArguments' to 'true',my method parameters should be noted what？

**Comment by abel533** [comment]
时间太久了，抱歉这么晚回复，可以试试新版本。
