### ISSUE TITLE
navigatePages 设置的值和navigatepageNums数组中的值不一致 

### ISSUE THREAD

**Issue by 191824852** [pagehelper/Mybatis-PageHelper#159]
`{
	"pageNum": 1,
	"pageSize": 5,
	"size": 5,
	"startRow": 1,
	"endRow": 5,
	"total": 43,
	"pages": 9,
	"list": [],
	"prePage": 0,
	"nextPage": 2,
	"isFirstPage": true,
	"isLastPage": false,
	"hasPreviousPage": false,
	"hasNextPage": true,
	"navigatePages": 6,
	"navigatepageNums": [1,
	2,
	3,
	4,
	5,
	6,
	7,
	8],
	"navigateFirstPage": 1,
	"navigateLastPage": 8,
	"firstPage": 1,
	"lastPage": 8
}`

请问怎么正确的设置 navigatePages  参数

**Comment by abel533** [comment]
看 PageInfo 构造方法。

**Comment by wangjianme** [comment]
"endRow": 20,
  "pages": 4,
  "prePage": 1,
  "nextPage": 3,
  "isFirstPage": false,
  "isLastPage": false,
  "hasPreviousPage": true,
  "hasNextPage": true,
  "navigatePages": 8,
  "navigatepageNums": [
    1,
    2,
    3,
    4
  ],
  "navigateFirstPage": 1,
  "navigateLastPage": 4
}
