### ISSUE TITLE
偶发性调用了分页.

### ISSUE THREAD

**Issue by JcRaymee** [pagehelper/Mybatis-PageHelper#163]
我在使用了通用mybatis执行一个selectAll() 方法的时候, 偶发性会执行select count 与带limit的分页. 几率大概10次出现1次.调试中发现(PageHelper)的boolean skip(MappedStatement ms, Object parameterObject, RowBounds rowBounds)这个方法返回false,后续再PageParamas中getPage(Object parameterObject, RowBounds rowBounds)这个方法的第一句Page page = PageHelper.getLocalPage(); 这里page居然从本地线程得到了,也就是page不为null,郁闷了, 这里page不为null后,page就会取设置CountColumn,然后开始执行initDelegateDialect(ms),接着返回false.....  重点应该就在那个hreadLocal<Page> LOCAL_PAGE.get()这里,是不是意味着某些时候clearPage() 失败了? 或者没有执行???

**Comment by JcRaymee** [comment]
版本是:
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.3</version>
        </dependency>
配置:
pagehelper.helperDialect=MYSQL
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql
pagehelper.pageSizeZero=true

**Comment by abel533** [comment]
很有可能是没按规范调用导致的。

可以看看这里[PageHelper 安全调用](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8)
