### ISSUE TITLE
微服务调用

### ISSUE THREAD

**Issue by flover28** [pagehelper/Mybatis-PageHelper#164]
在使用了 zookeeper和阿里的hsf这样的分布式容器。在服务提供者中使用后打印page对象，显示是没有问题的，在消费者接到返回结果后，打印page对象，发现完全不一样，值都是0和null。

**Comment by abel533** [comment]
page继承的ArrayList，集合序列化会丢失属性信息，你可以参考PageInfo对分页结果转换一下。
