### ISSUE TITLE
将rowBoundsWithCount配置为false，仍然执行了count查询。

### ISSUE THREAD

**Issue by sevenFire** [pagehelper/Mybatis-PageHelper#165]
配置文件中：
`<property name="rowBoundsWithCount" value="false"/>`

但是执行的语句为：
DEBUG dao.DBS.SELECT.1618407044_COUNT - ==>  Preparing: SELECT count(*) FROM t_branch 
DEBUG dao.DBS.SELECT.1618407044_COUNT - ==> Parameters: 
DEBUG dao.DBS.SELECT.1618407044_COUNT - <==      Total: 1
DEBUG dao.DBS.SELECT.1618407044 - ==>  Preparing: SELECT * FROM t_branch limit ? offset ? 
DEBUG dao.DBS.SELECT.1618407044 - ==> Parameters: 10(Integer), 0(Integer)
 DEBUG dao.DBS.SELECT.1618407044 - <==      Total: 10

即，仍然进行了count查询。

**Comment by abel533** [comment]
这个问题已经解决。

这个参数只用于使用 RowBounds 作为参数时。
