### ISSUE TITLE
springboot查询过程中报java.lang.IndexOutOfBoundsException: Index: 0, Size: 0错误

### ISSUE THREAD

**Issue by GeneralTalking** [pagehelper/Mybatis-PageHelper#167]
堆栈如下：
```
### Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
### The error may exist in com/juqitech/zb/order/dao/impl/mapper/OrderMapper.java (best guess)
### The error may involve com.juqitech.zb.order.dao.impl.mapper.OrderMapper.findByConditions_COUNT
### The error occurred while handling results
### SQL: SELECT count(0) FROM (SELECT DISTINCT o.id AS id, o.order_number AS orderNumber, o.pricing_id AS pricingId, o.tenant_customer_id AS tenantCustomerId, o.tenant_customer_phone AS tenantCustomerPhone, o.is_deleted AS isDeleted FROM zb_order AS o INNER JOIN zb_order_item oi WHERE (o.id = oi.order_id AND o.tenant_id = ? AND o.status IN ('UNPAID') AND o.create_time < ?)) table_count
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
        at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
        ... 46 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.github.pagehelper.PageInterceptor.executeAutoCount(PageInterceptor.java:202)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:113)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy152.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
        ... 51 common frames omitted
```

该count(0)应该肯定会有结果返回才对，这里是什么原因导致的？

**Comment by abel533** [comment]
分页插件版本多少？

**Comment by abel533** [comment]
在 `PageInterceptor` 类的 202 行断点。

看看201行执行的返回值是什么，截个图贴这里看看。

```java
201: Object countResultList = executor.query(countMs, parameter, RowBounds.DEFAULT, resultHandler, countKey, countBoundSql);
202: Long count = (Long) ((List) countResultList).get(0);
203: return count;
```

**Comment by GeneralTalking** [comment]
@abel533 为改行报错，查询出来的countResultList对象size为0。根源在这里。
另外，我们采用的是推荐的方式，放到了每一个需要分页查询的前面，所以应该不会出现设置了分页信息但是未执行分页查询而导致的其他问题：
`PageHelper.startPage(pageNum, pageSize);`

另外，版本采用的是spring boot pagehelper，不知是否是版本问题, pom为：
`<dependency>
      <groupId>com.github.pagehelper</groupId>
      <artifactId>pagehelper-spring-boot-starter</artifactId>
      <version>1.2.3</version>
    </dependency>`

**Comment by abel533** [comment]
@GeneralTalking 最近有人在QQ上问过我这个问题，并且我也远程实际看了看，确实有可能是size=0，你使用的是不是druid连接池？

QQ上的问题也是偶发的，在出现的问题的时候，发现问题的人通过纯JDBC方式执行COUNT查询是有结果的。由于他没在这个时间测试druid，因此不能确定问题产生的原因。

在多数情况下（最外层没有group by时），count查询一定是有结果的。所以上述问题中，size=0不是一个应该出现的情况，而且这里size=0的时候根本没法认为查询结果是0.

所以如果你们用的druid，建议在出现这个情况时，直接通过druid数据源连接数据库查询看看。

**Comment by GeneralTalking** [comment]
用的的确是druid，所以很有可能是druid连接池的问题？

**Comment by abel533** [comment]
@GeneralTalking 升级druid版本或者换个别的连接池试试，发现问题的时候可以测试纯JDBC和druid两种方式结果是否相同。

**Comment by letian313** [comment]
这个问题没解决，为啥关闭呢。
`public static Long executeManualCount(Executor executor, MappedStatement countMs, Object parameter, BoundSql boundSql, ResultHandler resultHandler) throws SQLException {
        CacheKey countKey = executor.createCacheKey(countMs, parameter, RowBounds.DEFAULT, boundSql);
        BoundSql countBoundSql = countMs.getBoundSql(parameter);
        Object countResultList = executor.query(countMs, parameter, RowBounds.DEFAULT, resultHandler, countKey, countBoundSql);
        Long count = ((Number)((List)countResultList).get(0)).longValue();
        return count;
    }`
countResultList 这个地方做个 list判断就可以了

**Comment by zhishengzhang** [comment]
countResultList 是空的，这个bug解决了吗？

**Comment by shihongwei** [comment]
> countResultList 是空的，这个bug解决了吗？
忙，估计没时间解决

**Comment by 409036864** [comment]
我之前也提出过此问题，不知道新版解决没有？这个问题太头疼了，我也是用的druid连接池，随机挑选模块出现此错误，断点的时候发现返回的是NULL，但是实际情况肯定是有结果的。

**Comment by wavesZh** [comment]
同样随机出现这种问题，使用  mybatis-spring-boot-starter 2.1.2，  pagehelper-spring-boot-starter 1.2.13

**Comment by 1092622894hzq** [comment]
我使用的也是durid，我想要通过Limit分页查询数据时，就会报这个错误，不使用limit就没有问题

**Comment by bamboog** [comment]
@abel533  问题还没修复么5.1.11代码也没动啊

**Comment by bamboog** [comment]
@abel533 或者临时解决办法有么？目前偶发报错

**Comment by abel533** [comment]
即将发布的5.2.0版本处理了这个问题。

**Comment by l-i-h-e** [comment]
pagehelper-spring-boot: 1.3.0 依然存在这个问题
测试时发现 select count(0) from xx  执行不通过，但是如果设置为 select select count(0) from xx  as x 就没问题了，实际上的情况就是，随便改一下sql就没问题了

**Comment by l-i-h-e** [comment]
如果把原始的sql直接携程 from xx as x 就都可以执行过了，不懂发生了什么，但是我的确通过这样的方法缓解了这个问题的影响

**Comment by ro9er** [comment]
想问下目前有比较明确的解决方案了么？

**Comment by abel533** [comment]
可以试试即将发布的最新版本：5.2.2

**Comment by daxue2017** [comment]
用pagehelper-spring-boot-starter组件1.4.1版本，mybatis通过oscarJDBC-1.0.jar查询神通数据库时，会报这个错误，这怎么修改啊

**Comment by abel533** [comment]
@daxue2017 试试纯JDBC是什么结果。。确认是不是oscar驱动的问题。
