### ISSUE TITLE
PageInfo 提取个父类，简化属性

### ISSUE THREAD

**Issue by abel533** [pagehelper/Mybatis-PageHelper#168]
PageInfo 提取个父类，简化属性

**Comment by DreamPWJ** [comment]
强烈支持  现在属性太多了 很多都没有 请强迫症忍不了  都是自己定义的  但是自己定义的没法用.doSelectPageInfo(() -> 方式  

    private int page;     //当前页
    private int size;     //每页记录数
    private int pages;    //总页数
    private long total;   //总记录数
    private int pageSize; //当前页的数量
    private List<T> list; //结果集

只保留这几个最常用的就可以了

**Comment by abel533** [comment]
@DreamPWJ 很早之前就已经提供了： https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/PageSerializable.java

**Comment by DreamPWJ** [comment]
PageSerializable可以用lamda表达式？

**Comment by DreamPWJ** [comment]
自定义的pageinfo 如何使用lamdba表达式@abel533
