### ISSUE TITLE
5.0 版本 不支持 PageHelper.setOrderBy 方法了？

### ISSUE THREAD

**Issue by gs-liut** [pagehelper/Mybatis-PageHelper#17]
5.0 版本 不支持 PageHelper.setOrderBy 方法了？升级后要改好多代码啊

**Comment by abel533** [comment]
有单独的排序插件：
项目地址：https://github.com/abel533/OrderByHelper
目前就简单的功能，有想法的可以提 issue。

**Comment by abel533** [comment]
可以在这个帖子进行反馈：https://github.com/pagehelper/Mybatis-PageHelper/issues/38
