### ISSUE TITLE
How to global-conf NO COUNT(0)/怎么配置全局不进行Count查询呢？

### ISSUE THREAD

**Issue by rocbin** [pagehelper/Mybatis-PageHelper#179]
Spring:
                < bean class="com.github.pagehelper.PageInterceptor" >
                    < property name="properties" >
                        < value >
                            helperDialect=sqlserver
                            count=false  // 试了不可以
                        < /value >
                    < /property >
                < /bean >

请问下怎么配置默认不COUNT呢？
用了大半年今天才发现有个COUNT，我不希望COUNT（实在是慢慢慢，而且我也不需要显示它）。

**Comment by abel533** [comment]
pagehelper.startPage第三个参数可以

**Comment by rocbin** [comment]
是的，这个方法是可以的。
但建议改进一下，支持全局配置 count=false，是不是更强大了呢？！

**Comment by abel533** [comment]
后续会考虑增加这个配置。

**Comment by abel533** [comment]
5.1.3 增加 defaultCount 参数，用于控制默认不带 count 查询的方法中，是否执行 count 查询，默认 true 会执行 count 查询，这是一个全局生效的参数，多数据源时也是统一的行为。

**Comment by liian2018** [comment]
唉 没仔细看文档 导致我一个千万级的表 每次都要先查下总数 然后慢的要死  哈哈 在这里找到了答案 谢谢作者
