### ISSUE TITLE
Cause: java.sql.SQLSyntaxErrorException: ORA-00907: 缺失右括号

### ISSUE THREAD

**Issue by aisq2008** [pagehelper/Mybatis-PageHelper#18]
使用的版本是4.2.1

**Comment by peichengguo** [comment]
直接拿sql到库里执行呢？那个占位符看着不对劲呢

**Comment by aisq2008** [comment]
问题解决了，是oracle的like查询的问题
用下面的like语句就可以了，
<where>
          <if test="stationName != null">
              S.NAME LIKE '%'||#{stationName}||'%'
          </if>
          <if test="stationAddress != null">
              AND S.ADDRESS LIKE '%'||#{stationAddress}||'%'
          </if>
          <if test="stationCode != null">
              AND S.STATION_CODE LIKE '%'||#{stationCode}||'%'
          </if>
          <if test="stationPosCode != null">
              AND S.POSITION_CODE LIKE '%'||#{stationPosCode}||'%'
          </if>
      </where>

用这种like就不行

      <where>
          <if test="stationName != null">
              S.NAME LIKE CONCAT('%',#{stationName},'%')
          </if>
          <if test="stationAddress != null">
              AND S.ADDRESS LIKE CONCAT('%',#{stationAddress},'%')
          </if>
          <if test="stationCode != null">
              AND S.STATION_CODE LIKE CONCAT('%',#{stationCode},'%')
          </if>
          <if test="stationPosCode != null">
              AND S.POSITION_CODE LIKE CONCAT('%',#{stationPosCode},'%')
          </if>
      </where>
