### ISSUE TITLE
在做关联查询的时候分页总条数和实际返回JAVA对象条数不匹配

### ISSUE THREAD

**Issue by OTTOGH** [pagehelper/Mybatis-PageHelper#186]
我在做外键关联查询想获取一对多的对象时，SQL语句查询结果是多个的，最后返回的对象列表只有一个，导致我分页插件的total值一直不对。

**Comment by Seasheller** [comment]
这个明确指出来了不支持，total对应的应该是sql执行的行数，sql 映射 中有<collection>  会将多条查询结果合成一个对象，所以total 值不对 [链接在这儿](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Important.md) ； 这个插件没法做到那么智能的去计算 你哪几条结果会合并，合并之后剩几条
