### ISSUE TITLE
按教程配置   在使用 DevTools 时，通用Mapper经常会出现 class x.x.A cannot be cast to x.x.A。

### ISSUE THREAD

**Issue by cjcj125125** [pagehelper/Mybatis-PageHelper#187]
如题，配置好restart.include.mapper=/mapper-[\\w-\\.]+jar
restart.include.pagehelper=/pagehelper-[\\w-\\.]+jar

但是还是提示这个错误，求教大佬

**Comment by abel533** [comment]
新版本的通用 Mapper 自带这个配置，不需要加这个。
