### ISSUE TITLE
在使用dubbo的时候，分页无效

### ISSUE THREAD

**Issue by fufenghua** [pagehelper/Mybatis-PageHelper#188]
在使用dubbo的时候，service和web是分开打包的，zookeerper做注册中心，这个时候设置pageNum，pageSize都没有用，依旧是查询全部。

**Comment by wasmir** [comment]
web端：core包,client包 core中只包含mapper接口
service端：core包,service包 service中分页

**Comment by abel533** [comment]
不建议直接用 PageInfo，最好封装自己需要的数据结构。

**Comment by hanzhenchaoGit** [comment]
可以自己写一个类 实现序列化接口  里面包装查询列表需要的分页数据 千万不要在消费者端转pageInfo去取数据总数  那样总数是不对的  只要在dubbo服务层把数据组装好返回去就行了

**Comment by UniqueDong** [comment]
这是个大坑
