### ISSUE TITLE
sqlserver2012分页时要求必须带上order by否则报错

### ISSUE THREAD

**Issue by sevenFire** [pagehelper/Mybatis-PageHelper#190]
原始语句：select * from ZY_test.company
分页后生成的语句：select * from ZY_test.company  OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
后台报错，执行失败。
`[42000] [Microsoft][SQL Server Native Client 10.0][SQL Server]“0”附近有语法错误。 (102)
[42000] [Microsoft][SQL Server Native Client 10.0][SQL Server]在 FETCH 语句中选项 NEXT 的用法无效。 (153)`
只有加上order by才能执行成功。
成功执行的语句：select * from ZY_test.company ORDER BY company_id OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

**Comment by sevenFire** [comment]
后面的版本已经解决了这个问题。

**Comment by abel533** [comment]
2012的分页方式不需要order by

**Comment by PelloZhang** [comment]
sqlServer2012中offset_fetch分页关键字是order by子句，参考Microsoft的文档如下
> https://docs.microsoft.com/zh-cn/previous-versions/sql/sql-server-2012/ms188385(v=sql.110)

所以如果使用sqlServer2012分页必须有order by才不会报错

**Comment by zhengweitang** [comment]
2012确实存在这个问题，建议在下一个版本默认使用主键排序

**Comment by abel533** [comment]
@zhengweitang 分页SQL是任意的，只说主键也不知道是那个字段。最合理的方式是自己在 SQL 中指定排序。

**Comment by patience00** [comment]
楼上的朋友解决了吗？
PageHelper.offsetPage(form.getPageIndex(), form.getPageSize());
PageHelper.orderBy(form.getOrderField());
是这样用的吧，还是会报错呀
