### ISSUE TITLE
sqlserver分页后返回的数据多了一列PAGE_ROW_NUMBER

### ISSUE THREAD

**Issue by sevenFire** [pagehelper/Mybatis-PageHelper#192]
原始语句：
SELECT * FROM ZY_test.company ORDER BY "company_id"

分页处理后的语句：
SELECT TOP 2 * FROM (SELECT ROW_NUMBER() OVER (ORDER BY "company_id") PAGE_ROW_NUMBER, * FROM (SELECT * FROM ZY_test.company) AS PAGE_TABLE_ALIAS) AS PAGE_TABLE_ALIAS WHERE PAGE_ROW_NUMBER > 1 ORDER BY PAGE_ROW_NUMBER 

执行正确，但是返回的数据多了一列page_row_number。能不能不出现这列？
     {
            "company_id": "2",
            "PAGE_ROW_NUMBER": 2,
            "company_name": "企业2",
            "company_income_time": "2017-01",
            "company_income": "400000"
        }

**Comment by abel533** [comment]
你用`Map` 做返回值？
