### ISSUE TITLE
难道不支持动态sql语句，mybatis中使用动态sql语句模糊查询无法查询出数据

### ISSUE THREAD

**Issue by tanzy1** [pagehelper/Mybatis-PageHelper#195]
`select u.*,r.roleName from user u inner join role r on u.roleId=r.id 
      <if test="uName!=null">
		where u.uName like concat(#{uName},"%")
      </if> 
order by u.id`

**Comment by abel533** [comment]
支持动态SQL。。执行的日志或者错误信息有吗？

**Comment by tanzy1** [comment]
昨天又重新试了试这样是可以的select u.*,r.roleName from user u inner join role r on u.roleId=r.id <where><if test="uName!=null"> u.uName like concat(#{uName},"%") </if></where> order by u.id，感谢回复

**Comment by tanzy1** [comment]
select u.*,r.roleName from user u inner join role r on u.roleId=r.id <where><if test="uName!=null">  u.uName like concat(#{uName},"%") </if></where> order by u.id添加where标签

**Comment by rocbin** [comment]
@tanzy1 
建议你用：
<if test="uName != null">
   <bind name="uNameLike" value="uName + '%'">
  where ....
</if>
