### ISSUE TITLE
求救。分页怎么没有生效，调试显示直接dialect.skip(ms, parameter, rowBounds)) 返回了true

### ISSUE THREAD

**Issue by wugang33** [pagehelper/Mybatis-PageHelper#196]
我使用的是MySqlDialect，这个方法继承了AbstractHelperDialect
而这个方法的skip方法直接返回了true
    @Override
    public final boolean skip(MappedStatement ms, Object parameterObject, RowBounds rowBounds) {
        //该方法不会被调用
        return true;
    }

导致PageInterceptor方法直接跳走了，没有进行分页。
if (!dialect.skip(ms, parameter, rowBounds)) {

不知道是我的用法有问题么？

我使用的是5.0.4版本

**Comment by abel533** [comment]
换 51.2 吧。

**Comment by wugang33** [comment]
可以。不过我看最新的代码好像也是同样的逻辑。标注不会调用的代码被调用了。我也很纳闷。

**Comment by wugang33** [comment]
@abel533 您好。谢谢您的答复。 不过51.2是什么版本。我看了。5.0.4是最新的发布版本。

**Comment by wugang33** [comment]
问题找到了，原来我在SpringBoot的application.properties里面配置了如下的配置：
pagehelper.dialect=com.github.pagehelper.dialect.rowbounds.MySqlDialect

其实留空或者是配置为（如果留空会设置为默认值com.github.pagehelper.PageHelper）：
pagehelper.dialect=com.github.pagehelper.PageHelper

**Comment by liuzhenji** [comment]
擦，我也遇到这个问题了，就这个pageParam.skip方法内，一个(rowBounds != RowBounds.DEFAULT）的判断造成的。。。我一开始一直以为dialect的是MysqlDialect实例是正确 的。。。。看了你的issue才知道，正确的dialect实例是PageHelper的实例对象。。。不过好在问题解决了，我接着调试下，看看正确的逻辑，跟这个错误的逻辑之间的关系，有收获再回来分享

**Comment by liuzhenji** [comment]
好吧，我试了，换了也不好使，照样走我刚说的那个逻辑。。。。。。

**Comment by liuzhenji** [comment]
发现这样一个情况，分页想过是有的，但是如果你查询的当前页没有数据的话，ThreadLocal里的page对象会在set,get前后不一致，get到的，是被处理成有数据页面状态的（如pageNum字段，startRow\endRow等字段），continuing.....

**Comment by liuzhenji** [comment]
好了，真相大白了，擦，是resonable参数设置为true后，在pageNum >总页数的时候，进行判断，超出后，重新set了ThreadLocal内的page参数。
闹剧结束。。。。
