### ISSUE TITLE
查询出来的结果变成了Page类型，请问照成这种情况的原因

### ISSUE THREAD

**Issue by cky-thinker** [pagehelper/Mybatis-PageHelper#197]
Mapper的查询sql是正确的，但是最后查出来的list却变成了Page类型，请问是什么原因，如何解决？

**Comment by wugang33** [comment]
这个就是这样的。page类型可以当做list类型使用。可以看文档。

**Comment by cky-thinker** [comment]
哦哦，我直接用toString打印的，Page把原来ArrayList的toString覆盖了，转成json是用反射搞得就没问题了，谢谢。
