### ISSUE TITLE
Enhancement：throw new PageException("不支持该SQL转换为分页查询!") at com.github.pagehelper.parser.SqlServerParser

### ISSUE THREAD

**Issue by rocbin** [pagehelper/Mybatis-PageHelper#200]
建议此处抛出异常时，把异常参数 e 带上。
我遇到的情况是自己的动态 SQL 语法有问题，导致解析报异常，最后只能去调试代码，才发现真实问题。
建议：
`throw new PageException("不支持的分页 SQL 语句转换或此 SQL 语法不正确请检查", e);`

**Version 5.0.0**

**Comment by abel533** [comment]
已解决。
