### ISSUE TITLE
mysql存在左右连接时，count sql语句出错

### ISSUE THREAD

**Issue by DuanDuanPan** [pagehelper/Mybatis-PageHelper#201]
原始sql语句如下，BASE_PARENT，BASE_STUDENT，BASE_PARENT_STUDENT组成多对多
`
SELECT
  bp.ID,
  bp.NAME,
  bp.PHONE,
  bp.IDCODE,
  bp.CREDENTIALS_PIC,
  bp.ROLE,
  bs.ID   child_id,
  bs.NAME child_name
FROM BASE_PARENT bp LEFT JOIN (BASE_STUDENT bs ,BASE_PARENT_STUDENT bst)
    ON (bp.ID = bst.PARENT_ID AND bs.ID = bst.STUDENT_ID)
WHERE 1 = 1
`
经过分页后，count 生成的sql语句如下所示
`
SELECT count(*)
FROM BASE_PARENT bp LEFT JOIN (BASE_STUDENT bs BASE_PARENT_STUDENT bst)
    ON (bp.ID = bst.PARENT_ID AND bs.ID = bst.STUDENT_ID)
WHERE 1 = 1
`
其中LEFT JOIN后的括号中表之间的逗号被自动去除，调试发现SqlParser.getSmartCountSql函数中转化为count sql语句时出错

**Comment by abel533** [comment]
最近的 jsqlparser 1.2 仍然不支持这种方式。

**Comment by xiaoyangzhang** [comment]
括号中的逗号改为join也不行吗

**Comment by xiaoyangzhang** [comment]
试了试两个表的左连接，正常返回了
