### ISSUE TITLE
jsqlparse 解析这条语句的时候 出错了   ifnull(sum(if(o.bet_status=5,o.bet_fee,0)),0) as sumRefund,

### ISSUE THREAD

**Issue by smembers** [pagehelper/Mybatis-PageHelper#203]
net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( ""

但是不影响查询数据分页, 只是在控制台会输出错误日志, 感觉会是一个隐患
软件版本
Spring Boot 1.5.9.RELEASE
PageHelper Boot 1.2.3

**Comment by smembers** [comment]
MYSQL

**Comment by abel533** [comment]
复杂sql解析不了。

**Comment by hao117** [comment]
复杂sql解析不知道Druid可以不，可以试试

**Comment by abel533** [comment]
@hao117 以后会测试 druid 的sql解析。
