### ISSUE TITLE
使用pagehelper后导致拦截器链失效，尤其是后置执行的，比如 统计查询时间的拦截器

### ISSUE THREAD

**Issue by shanjunmei** [pagehelper/Mybatis-PageHelper#209]
如题

**Comment by abel533** [comment]
一个解决的办法就是调整顺序。

更彻底解决办法和原因可以查看：[Executor 拦截器高级教程 - QueryInterceptor 规范
](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md).

目前在 mybatis 最新版本提交了个 PR，就是解决这里的 query 方法无法被拦截的问题。
