### ISSUE TITLE
分页时枚举类型报错？

### ISSUE THREAD

**Issue by ydq** [pagehelper/Mybatis-PageHelper#22]
在mapper.xml中已经对相应的枚举类型设置了
```properties
typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler
```
page自动查询count的语句正常输出，但是查询list结果的语句就会提示`Object does not represent an enum type.`的异常。dubug的时候，我的两个枚举两次正常进入，不明白的是为什么又进入了第三次传入了一个Object类型的Class对象，理应来说只有两个参数设置了typeHandler，应该进入两次就完了。

![image](https://cloud.githubusercontent.com/assets/8097340/23100423/0109bf46-f6bb-11e6-8a1a-236de6aeffdf.png)

<img width="786" alt="page_bug" src="https://cloud.githubusercontent.com/assets/8097340/23100384/65967b6c-f6ba-11e6-8224-62185015a2f8.png">

如果注释掉分页，直接查询list结果集也是可以正常查询的，所以我斗胆猜测是否是分页引起的bug，麻烦作者检查一下（PS：我用mybatis的时间不是很长，也许是我使用方法有误，也麻烦请告知，请包涵）

**Comment by abel533** [comment]
我还没试，有可能是分页处理handler时出错。

**Comment by abel533** [comment]
增加了个测试（看关联的提交），没有发现问题。

前面枚举type正常传入是因为解析resultMap(Type)的时候能够从类型中获取字段的类型。

后面是Object是在解析SQL时，你参数`#{}`中并没有指定`javaType`所以是Object。在我这个测试中没有出错。

**Comment by ydq** [comment]
@abel533  好的，谢谢您
