### ISSUE TITLE
MyBatis分页插件PageHelper的用法的一个小疑问

### ISSUE THREAD

**Issue by Li23023Li** [pagehelper/Mybatis-PageHelper#221]
`在一个项目中看到PageHelper分页插件这样的用法`
![pagehelper](https://user-images.githubusercontent.com/31609204/39663840-c961ddce-50ac-11e8-9cdf-f71168d38883.png)

**Comment by abel533** [comment]
productList中有分页和total信息。。所以这里这么处理的。

**Comment by Li23023Li** [comment]
```
那我们直接PageInfo pageResult = new PageInfo(productListVoList);不可以吗？
在此项目的另一个功能中，有把VO对象直接传进构造方法中的用法，如:
```
![vo](https://user-images.githubusercontent.com/31609204/39663949-530fbc02-50ae-11e8-822f-2fdedc6f97fd.png)

一定要赞一下作者，回复快的都想不到啊

**Comment by abel533** [comment]
不可以，你这种写法得不到 total 值。
最新版本的 PageInfo 增加了一个基类，那个类更简单，推荐用。

**Comment by abel533** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/PageSerializable.java
