### ISSUE TITLE
[Bug] 同一时间，存在多个请求时，多个请求的返回值会有互相混淆的错误

### ISSUE THREAD

**Issue by Icemap** [pagehelper/Mybatis-PageHelper#223]
复现步骤：
    后端使用PageHelper进行分页，前端请求时，使用异步，即：第一个请求未完成的情况下，进行第二个请求，即使该请求链中不存在分页操作（PageHelper.start(0,0);），也会造成错误。

错误描述：
    同一时间，存在多个请求时，多个请求的返回值会有互相混淆的错误。
    例如：请求A的返回值为RA；请求B的返回值为RB；该错误会使得A的请求值有可能成为RB。

PageHelper配置(该配置位于Spring配置的org.mybatis.spring.SqlSessionFactoryBean类中)：
```
...
<property name="plugins">
	<array>
	  <bean class="com.github.pagehelper.PageInterceptor">
	  <property name="properties">
          <!--使用下面的方式配置参数，一行配置一个 -->
          <value>
            pageSizeZero=true
          </value>
        </property>
	  </bean>
	</array>
</property> 
```

请求调用链代码：
```
Controller：
    return kmlService.getKmlByKmlTypeId(kmlTypeId);
Service:
    return kmlMapper.selectKmlByKmlTypeId(kmlTypeId);
Mapper-SQL:
    <select id="selectKmlByKmlTypeId" resultMap="BaseResultMap" parameterType="java.lang.Long" >
    select 
    <include refid="Base_Column_List" />
    from t_kml
    where kml_type_id = #{kmlTypeId,jdbcType=BIGINT}
  </select>
```
调用版本：
PageHelper：5.1.2；
Mybatis：3.2.6；
Spring：4.3.8.RELEASE；
Java：1.8；

项目托管地址：
https://github.com/Icemap/WaterManagerSystem
master分支
commit次数为13

**Comment by Icemap** [comment]
补充1：请求A与请求B的URL相同，仅参数不同。

**Comment by abel533** [comment]
看这里 [3). PageHelper 安全调用](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8)

**Comment by Icemap** [comment]
我的代码段中并未使用PageHelper.start(0,0);
即使这样，也会造成不安全？？？

**Comment by Icemap** [comment]
Sorry。
是我自己智障了。
不好意思。
自己代码的问题。
