### ISSUE TITLE
关于startPage和offsetPage用法选择的疑问

### ISSUE THREAD

**Issue by mccxj** [pagehelper/Mybatis-PageHelper#224]
你好，我看到用法上有提供startPage和offsetPage两种用法，而且用法似乎没有明显区别。

请问这背后的原因是什么？
项目组最好能够统一用法，我应该推荐哪一个用法呢？

**Comment by qingwanggo** [comment]
offsetPage  好像已经没了 新的版本

**Comment by abel533** [comment]
offsetPage 是指定开始位置。
startPage 是指定第几页（从1开始）。
区别很大吧？

**Comment by JKTerrific** [comment]
@abel533  你好 4.x版本的PageHelp中注释是否存在问题。```@param offset  页码``` 这句注释是否应该改为```@param offset  开始位置```

**Comment by abel533** [comment]
@JKTerrific 有问题，需要改。

**Comment by qrqhuang** [comment]
@abel533  是否可以在注释上标注下 ```@param offset 起始位置，偏移位置，从0开始```

**Comment by ChengXiRui** [comment]
@abel533 你好，我在使用PageHelper.offsetPage(skip, limit)分页时，当limit大于等于返回列表的total时候，查不出数据；当使用PageHelper.offsetPage(skip, limit, false)的时候倒是正常分页，但是total需要手动统计过。请问这是一个BUG吗，需要怎么实现，期待回答！！

**Comment by coolapker** [comment]
> 

这个有个配置可以智能识别
