### ISSUE TITLE
没有显示调用startPage，却被莫名的增加了分页

### ISSUE THREAD

**Issue by mychao** [pagehelper/Mybatis-PageHelper#226]
采用mybatis，自定义查询sql语句，没有分页。奇怪的是，每次都会被莫名的添加分页的操作，还请给予帮忙解答。

**Comment by abel533** [comment]
看这里 [3). PageHelper 安全调用](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8)
