### ISSUE TITLE
读写分离，多数据源情况下，如何使用

### ISSUE THREAD

**Issue by jandyu** [pagehelper/Mybatis-PageHelper#23]
配置了两个数据源，只有primary的pagehelper有效，另一个无效，应该如何处理？

**Comment by abel533** [comment]
有几个 sqlSession ?

**Comment by jandyu** [comment]
用了两个@Configuration注册了两个DataSource，对应有两个SqlSessionFactory，分别扫描自己的mapper，一个为主数据加了@Primary，另一个没有加。只有调用@Primary的mapper前的pagehelper有效，可以分页，无@Primary的pagehelper设置无效。

**Comment by abel533** [comment]
分页插件配置两个了吗？

**Comment by jandyu** [comment]
原来一个数据源的代码是用PageHelper.startPage(query.getPage(), query.getPageSize())进行分页的，
数据源和mapper调整为两套后，出现这个问题。

分页插件两个如何配置为？startPage这种调用模式是否可以？

**Comment by abel533** [comment]
一个sqlsession就得对应一个配置。。静态方法可以用，不会乱。

**Comment by jandyu** [comment]
终于搞定，不过发现主数据源@Primary中不能用setPlugins来设置PageInterceptor，会生成错误的sql，导致错误，只能在application.yml中配置，才能有效。
而另一个数据源必须在SqlSessionFactory中setPlugins才能有效，在application.yml无法配置。
有点弄不明白，应该都可以用setPlugins配置，为什么@Primary就不可以？

**Comment by AlexanLee** [comment]
我也发现，好像配置多数据源之后，分页有问题。

**Comment by BearBig-CN** [comment]
@jandyu 你是怎么解决的？我也是在SqlSessionFactory设置了Plugins，但是在执行SQL时提示配置了多个分页插件的异常

**Comment by BearBig-CN** [comment]
问题解决了，是因为系统启动的时候PageHelperAutoConfiguration会自动注册，只需要在启动的时候排除掉即可，写法：@SpringBootApplication(exclude = PageHelperAutoConfiguration.class)。
