### ISSUE TITLE
自定义count无效

### ISSUE THREAD

**Issue by frame-faker** [pagehelper/Mybatis-PageHelper#230]
![image](https://user-images.githubusercontent.com/24647589/40300680-8aef2782-5d1c-11e8-9e87-ada8c243769c.png)

**Comment by frame-faker** [comment]
![image](https://user-images.githubusercontent.com/24647589/40300696-98e65c16-5d1c-11e8-8058-23db77c5f104.png)

**Comment by frame-faker** [comment]
还是走了中间表，没有使用自定义的count语句

**Comment by abel533** [comment]
和这里的要求符合吗：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#504---2017-08-01

能不能断点看看查找该方法时的情况，断点位置：https://github.com/pagehelper/Mybatis-PageHelper/blob/78b4701359ef807192549d74f82a79e9f47bd4b3/src/main/java/com/github/pagehelper/PageInterceptor.java#L102
