### ISSUE TITLE
springboot下，pom.xml已经配置了pagehelper-spring-boot-starter依赖，还一直报找不到PageInterceptor

### ISSUE THREAD

**Issue by 276234199** [pagehelper/Mybatis-PageHelper#231]
java.lang.ClassNotFoundException: Cannot find class: com.github.pagehelper.PageInterceptor

在maven dependencies里已经能找到pagehelp包，包里也能找到PageInterceptor，启动springboot总是报错？求解~

**Comment by 276234199** [comment]
pom.xml
<dependency>
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper-spring-boot-starter</artifactId>
			<version>1.2.5</version>
</dependency>

application.yml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

哪里没弄对。。？

**Comment by 276234199** [comment]
我把pagehelper降低版本到1.2.4就不报错了 什么鬼

**Comment by 276234199** [comment]
我重新下载了1.2.5 没报错了  估计是网络没把包下载完整

**Comment by abel533** [comment]
应该是网络的问题。
