### ISSUE TITLE
关于查询全部

### ISSUE THREAD

**Issue by hbhghong** [pagehelper/Mybatis-PageHelper#232]
1.设置了orderby当pageSize=0的时候查询全部，为什么orderby就没有了
*我使用单独的orderby插件，不会这样
2.pageSizeZero这个flag设置与否都会查询全部
3.查询全部返回的pageInfo里pages为啥是0，不应该是1吗，还有endRow也是0？

**Comment by hbhghong** [comment]
版本5.1.4.关于pageinfo我自己构造了。
但是orderby的问题是存在的，还有pageSizeZero

**Comment by abel533** [comment]
pageSize=0的时候不会经过分页处理，因此orderBy 也无效了，这种情况下，建议设置为 Integer.MAX_VALUE.

**Comment by blukhand** [comment]
我也遇到了这个问题，文档中说明pageSize为零时候，是否分页，受到pageSizeZero这个flag的影响。
而且pageSizeZero 默认为false。但是实际使用中发现，pageSizeZero 没有效果，无论怎么设置，都相当于设置为true。
从代码里面看。beforePage 里面只判断了 page.isOrderByOnly() || page.getPageSize() > 0， pageSizeZero 没有相关逻辑。
单元测试中，也没有覆盖到，pageSizeZero为默认值，pageSize=0的测试用例，也是返回了所有的结果。
所以认为这边应该是文档和实现不相符。
看如何调整
谢谢

**Comment by tinyuu** [comment]
这个bug还没解决么？ 我在设置pageSize=0 或者 pageSize=Integer.MAX_VALUE 时发现 order by还是不生效 ，原因是在new Page 时下面代码又给设置成0了  ，我现在的解决方式是 设置 pageSize=Integer.MAX_VALUE-1
if (pageNum == 1 && pageSize == 2147483647) {
            this.pageSizeZero = true;
            pageSize = 0;
        }

**Comment by abel533** [comment]
5.2.0版本已处理。
