### ISSUE TITLE
CACHE 变量内存溢出问题

### ISSUE THREAD

**Issue by xiaojiejie123** [pagehelper/Mybatis-PageHelper#233]
你好！
在V4.1.6版本中，com/github/pagehelper/parser/SqlParser.java 类中有一个变量CACHE用来缓存相同查询语句时sql语句中查询总量的sql字符串，当项目中有大量（查询条件不同）的分页查询时，JVM虚拟机堆内存会溢出。 

//缓存已经修改过的sql
private Map<String, String> CACHE = new ConcurrentHashMap<String, String>();

建议自定义个Map类继承LinkedHashMap,重写removeEldestEntry函数。限制CACHE至只能缓存MAX_SIZE条数，当需要缓存新的sql语句时，删除最旧的记录。
class CacheLinkedHashMap<K, V> extends LinkedHashMap<K, V> {

  private static final long serialVersionUID = 1L;
  private int MAX_SIZE = 200;

  @Override
  protected boolean removeEldestEntry(java.util.Map.Entry<K, V> eldest) {
    return size() > MAX_SIZE;
  }
}

private Map<String, String> CACHE = new ConcurrentHashMap<String, String>();
修改为
private static Map<String, String> CACHE = Collections.synchronizedMap(new CacheLinkedHashMap<String, String>());

不知道我的想法是否更好 ？

**Comment by abel533** [comment]
推荐用最新版本。。或者看看你使用的版本能否配置缓存（最新版本肯定没问题）。
