### ISSUE TITLE
求教params里的count=countSql是做什么用的？

### ISSUE THREAD

**Issue by ghostman-git** [pagehelper/Mybatis-PageHelper#235]
params里的count=countSql是做什么用的？

**Comment by ghostman-git** [comment]
嗯，params我看文档了，我想知道设置countSql ，起到什么作用或者产生了什么效果？

**Comment by abel533** [comment]
如果POJO或者Map中发现了countSql属性，就会作为count参数使用。

**Comment by donny-dong** [comment]
我们项目里用到了pagehelper工具，但是最近我发现，我的普通全量查询返回list时会偶发出现数据分页（不知道为什么按（1,5）的结果处理）:
正常时Dao层返回的结果是：[object1,object2......]
异常时Dao层返回的结果是：Page{count=true, pageNum=1, pageSize=5, startRow=0, endRow=5, total=9, pages=2, reasonable=false, pageSizeZero=false} [object1,object2,object3,object4,object5]
这个是为什么呢？
这个map里就放了一个参数map.put("type","user")
List<InteractiveDataVo> interactiveDataVos = ewsUserDao.selectInteractiveUsers(searchMap);

**Comment by abel533** [comment]
文档中有一块内容是 **安全调用**，可以看看这里。
