### ISSUE TITLE
业务层封装vo. PageInfo失效

### ISSUE THREAD

**Issue by ShiyuNiu** [pagehelper/Mybatis-PageHelper#24]
我在使用静态方法使下一个select方法分页生效后，得到的list中是po对象，将它们转换为了适用于页面的vo对象list后，放入PageInfo中，也可以分页，但是pageinfo的属性失效了，所以我现在调用两种Service方法，一种返回po，一种封装为vo，因为我只想要PageInfo的分页属性，请问有没有什么好的解决方案？我也在思考中，感谢！

**Comment by abel533** [comment]
直接写个自己的 PageInfo 就行了，提供的 PageInfo 就是个例子，用来参考实现的。

**Comment by ShiyuNiu** [comment]
好的，明天到公司试一试，我还是个初学者。

得到作者的回答万分荣幸！

**Comment by ShiyuNiu** [comment]
好的，明天到公司试一试，我还是个初学者。

得到作者的回答万分荣幸！
