### ISSUE TITLE
分页查询一会快一会慢，很有规律，不知道是不是bug

### ISSUE THREAD

**Issue by libp** [pagehelper/Mybatis-PageHelper#242]
1、sql语句如下：
`<select id="selectArticleByPage" resultMap="ResultMapWithBLOBs">
        select
        <include refid="Article_Column_List" />
        from tbl_nichuiniu_article
    </select>`
2、请求截图，时快时慢
https://imgchr.com/i/CHZBX6

**Comment by libp** [comment]
直接用navicate  数据库查询工具 查询这个语句用时10毫秒，加上分页插件后，即使通过postman请求，也需要200毫秒左右。结合应用使用时有时高达500度毫秒，挺奇怪的

**Comment by chncho** [comment]
建议在数据查询前后添加日志进行分析，截图的时间还包含网络消耗

**Comment by libp** [comment]
因为结合elementui的table控件，数据库查询时间基本是恒定的。应该是前台加载时有问题
