### ISSUE TITLE
sqlparser error

### ISSUE THREAD

**Issue by alxe1528** [pagehelper/Mybatis-PageHelper#246]
sql ：
SELECT adcd,(SELECT RTRIM(stnm)+'['+stcd+']'+',' FROM (SELECT a.*,b.stnm FROM shzh_zhyj_hn_2017..village_stcd a
        LEFT JOIN shzh_water_hn_2017..ST_STBPRP_B b ON a.stcd = b.stcd WHERE b.stnm IS NOT NULL)  x
        WHERE x.adcd=y.adcd FOR XML PATH('')) AS StList
        FROM (SELECT a.*,b.stnm FROM shzh_zhyj_hn_2017..village_stcd a
        LEFT JOIN shzh_water_hn_2017..ST_STBPRP_B b ON a.stcd = b.stcd WHERE b.stnm IS NOT NULL) y
        GROUP BY adcd
throw ex：
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!] with root cause
com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!

**Comment by abel533** [comment]
SQL 太复杂，SQL解析器目前无法解析。

**Comment by rocbin** [comment]
@abel533 
`
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy29.selectList(Unknown Source)

`
对于动态SQL错误这种打印的引起的日志，日志内容缺失必要的SQL语句，没办法分析问题的所在。
建议在这个情况下，异常 message 中打印出SQL。

**Comment by rocbin** [comment]
主要是针对线上的系统日志，开发中是简单可以看到问题 SQL 的。

**Comment by abel533** [comment]
最新版本的 jsqlparser 2.0 能解析了
