### ISSUE TITLE
Page作为dubbo接口返回值时，只能接受List，无法获取到Page对象的分页数据

### ISSUE THREAD

**Issue by MeiZhuSQ** [pagehelper/Mybatis-PageHelper#249]
3.7.5版本，说是因为rowBound反序列化，但是更新到4.0.1，还是无法接收到page分页参数，更新到最新的5.0.4也是一样。是不是page实现了Serializable，另还实现了多个接口，导致返回的Page参数获取不到分页参数吗？到底是什么原因，求解

**Comment by abel533** [comment]
最新的是 5.x 版本。。继续升级试试。

**Comment by abel533** [comment]
配置有变化，注意看文档。

**Comment by AKingSSS** [comment]
org.apache.dubbo.common.serialize.SerializationException: java.lang.UnsupportedOperationException， 分页bug
