### ISSUE TITLE
Oracle下PageInfo的total一直是pageSize的数量

### ISSUE THREAD

**Issue by youuycom** [pagehelper/Mybatis-PageHelper#251]
Oracle下PageInfo的total一直是pageSize的数量，实际上我数据库是有28条数据的。

![image](https://user-images.githubusercontent.com/8571049/42357102-bc097a9c-8108-11e8-9b06-4c564df822ea.png)

**Comment by abel533** [comment]
贴出来SQL日志看看。

**Comment by newbby123** [comment]
==>  Preparing: SELECT count(0) FROM dict_mould a 
==> Parameters: 
<==      Total: 1
==>  Preparing: SELECT * FROM dict_mould a order by id ASC LIMIT ? 
==> Parameters: 10(Integer)
<==      Total: 10

**Comment by newbby123** [comment]
我是查出了分页数据后，对数据做了过滤，之后total变成了pageSize的大小，不处理数据即正确
