### ISSUE TITLE
Oracle下使用分页时使用order by 排序，排序的字段如果重复值多的话，查询出的结果不准

### ISSUE THREAD

**Issue by cjbbobo** [pagehelper/Mybatis-PageHelper#252]
例如分页查询一张表，表的数据量大约有1000条记录，表中有个字段为status，该字段总共有4个值（1，2，3，4），
假设每个值各有250条记录，即：status值为1的记录有250条，2的记录有250条；以此类推。
通过order by status字段分页查询时（假设每页10条），不管查第几页，查出的数据都是一样的

**Comment by abel533** [comment]
只能增加排序条件使得顺序唯一。
