### ISSUE TITLE
sql2008分页缓慢

### ISSUE THREAD

**Issue by zjl1985** [pagehelper/Mybatis-PageHelper#255]
我看输出语句是原有语句去掉order by 在外层又加入了一层select，在加上rounumber，这样相当于子查询一次后，再进行分页，会不会有问题，还是我的的用法就不对？

**Comment by abel533** [comment]
可以扩展自己实现。

**Comment by qilongpingchuan** [comment]
不知道如何扩展实现呢

**Comment by abel533** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md

搜 helperDialect

分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值：
oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页。

**你也可以实现 AbstractHelperDialect，然后配置该属性为实现类的全限定名称即可使用自定义的实现方法。**
