### ISSUE TITLE
求大神解答！使用Mockito写单元测试怎么mock如下代码？

### ISSUE THREAD

**Issue by Ailubby** [pagehelper/Mybatis-PageHelper#256]
文档中有个示例代码：pageInfo = PageHelper.startPage(1, 10).doSelectPageInfo(() -> countryMapper.selectGroupBy());

我想模拟 when(PageHelper.startPage(anyInt(),anyInt())).thenReturn(pageInfo),也就是这种ISelect接口怎么用Mockito测试？

**Comment by abel533** [comment]
没试过。
需要注意的是，返回结果不是分页插件返回的，是查询方法。

**Comment by CoderHuUestc** [comment]
大佬，我也遇到这个问题了，解决了没

**Comment by cznno** [comment]
> 没试过。
> 需要注意的是，返回结果不是分页插件返回的，是查询方法。

拿Ailubby的问题打比方，就算mock了CountryMapper#selectGroupBy()这个方法，也不能得到正确的返回结果：测试的时候mock的方法返回的List大小为0。

**Comment by dk980241** [comment]
遇到同样的问题，看来是还没有答案

**Comment by dk980241** [comment]
应该是 mockito 的问题，看到 Mockito项目中有问这个问题的，但是木有看到什么结果。。

**Comment by liuhaiyun012** [comment]
同求解决办法

**Comment by pysongyg** [comment]
同求解决办法，这个确实有点恶心人

**Comment by qingshanyuluo** [comment]
> 应该是 mockito 的问题，看到 Mockito项目中有问这个问题的，但是木有看到什么结果。。

有具体链接吗

**Comment by hujghc** [comment]
me too 有什么办法解决吗？
我是mock (countryMapper.selectGroupBy())
不管我怎么设置返回值，最后都是空的

**Comment by azh3ng** [comment]
摸索出一种写法，抛砖引玉

假设 UserService.java 中
```java
@Override
public Page<User> page(int pageNum, int pageSize) {
    Page<User> page = PageHelper.startPage(pageNum, pageSize).doSelectPage(() -> userMapper.select());
    return page;
}
```

测试方法：
```java
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

@Test
void test() {
    try (MockedStatic<PageMethod> pageMethod = mockStatic(PageMethod.class)) {
        Page<User> page = new Page<>();
        page.add(new User());
        pageMethod.when(() -> PageMethod.startPage(anyInt(), anyInt())).thenReturn(page);
        
        Page<User> users = service.page(1, 10);
        Assertions.assertEquals(1, users.size());
    }
}
```

注意： 
1. 需要引入依赖 groupId=org.mockito, artifactId=mockito-inline 原因见：https://blog.csdn.net/qq_38646452/article/details/124943944  
2. mockStatic 的类是 PageMethod 而不是 PageHelper 原因见： https://blog.csdn.net/weixin_43410352/article/details/118799839
