### ISSUE TITLE
OrderByParser异常信息输出

### ISSUE THREAD

**Issue by starflash** [pagehelper/Mybatis-PageHelper#257]
OrderByParser::converToOrderBySql()方法里的异常能不能抛出来，而不是直接用e.printStackTrace()输出？

**Comment by qixiaobo** [comment]
原来是打印错误 现在是直接报错了~sqlParser对于if函数支持不完善的场景下会导致直接无法执行……

**Comment by qixiaobo** [comment]
https://github.com/JSQLParser/JSqlParser/issues/100

**Comment by abel533** [comment]
@qixiaobo 测试发现最新 2.0 版本已支持。
