### ISSUE TITLE
针对阿里云ADS的查询count(0)会报异常, 有没有自定义count的方法?

### ISSUE THREAD

**Issue by mclubing** [pagehelper/Mybatis-PageHelper#259]
ADS: select count(0) from xxx; 会报错, count(1) 就不会, 有没有自定义count sql的方法?

**Comment by abel533** [comment]
自己能指定 count 里面的值。

https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#501---2017-04-23
