### ISSUE TITLE
版本5.0.0 报空指针异常，注册两次分页插件

### ISSUE THREAD

**Issue by cookier** [pagehelper/Mybatis-PageHelper#26]
嗨，我遇到了一个问题，跟 https://github.com/pagehelper/Mybatis-PageHelper/issues/9 一样。
可我只配置了一次，PageInterceptor中intercept方法却被调用了2次，换成4.2的版本就正常了。
我的设置如下：
```XML
<property name="plugins">
            <array>
                <!--配置mybatis分页插件-->
                <bean class="com.github.pagehelper.PageInterceptor"/>
            </array>
        </property>
```
请问还有可能是哪里的问题呢？
@wolazy

**Comment by abel533** [comment]
正常配置的情况下，只有用 pagehelper-starter 1.0.0 版本才会出现。

单独的分页插件，只有配置多次才会出现。

**Comment by cookier** [comment]
经过断点调试发现，需要以下配置：
```XML
<bean class="com.github.pagehelper.PageInterceptor">
                    <property name="properties">
                        <value>dialect=</value>
                    </property>
                </bean>
```
根据我的观察，`PageIntercepor.setProperties`方法里是设置`dialect`属性值的，如果在配置文件中没有调用到`setProperties`方法，则`dialect`为空，也没有默认值，所以导致执行插件的`intercept`方法时，调用`dialect.afterAll()`方法发生NPE。

**Comment by abel533** [comment]
在 `XMLConfigBuilder` 中：
```java
private void pluginElement(XNode parent) throws Exception {
    if (parent != null) {
      for (XNode child : parent.getChildren()) {
        String interceptor = child.getStringAttribute("interceptor");
        Properties properties = child.getChildrenAsProperties();
        Interceptor interceptorInstance = (Interceptor) resolveClass(interceptor).newInstance();
        interceptorInstance.setProperties(properties);
        configuration.addInterceptor(interceptorInstance);
      }
    }
  }
```
源码中，不管 properties 是否有值，都会执行 setProperties 方法，不是你说的问题。你可以看看这里。

**Comment by cookier** [comment]
生成XMLConfigBuilder的前提是有mybatis的配置文件，可我是用spring的属性配置方式。这样在`SqlSessionFactoryBean.buildSqlSessionFactory`的方法里由于`configLocation`属性值为空，不会生成`xmlConfigBuilder`对象，所以都不会执行到`pluginElement`方法。

**Comment by abel533** [comment]
非常感谢！！
确实有这个问题。
后面我会考虑在 `public Object plugin(Object target)` 方法中初始化插件。
