### ISSUE TITLE
我跟踪了下mybatis的源代码，发现在执行阶段并没有将limit 动态添加，是不是跟我执行的是CacheExector有关呢，请

### ISSUE THREAD

**Issue by yadong2000** [pagehelper/Mybatis-PageHelper#261]
可以肯定的是其他方法是可以执行分页的，
我跟踪了下mybatis的源代码，发现在执行阶段并没有将limit 动态添加，是不是跟我执行的是CacheExector有关呢，首先我在mybatis源代码中Plugs类中打了断点：但是并没有执行

然后我在mybatis中的的方法中也没有发现limit加上了，请问是什么原因啊

**Comment by huicaier** [comment]
有可能，你这个方法执行了之后将他执行结果保存到了Guava 的LocalCach缓存里了，可以在getIfPresent()这个方法里打一个断点

**Comment by abel533** [comment]
在分页插件拦截器中断点看看。。如果进不去，在拦截器的setProperties中也断点看看。。
