### ISSUE TITLE
非预编译期sql无法分页

### ISSUE THREAD

**Issue by somewhater** [pagehelper/Mybatis-PageHelper#265]
`	<select id="getConf" resultType="com.foresee.vsconfig.dto.ConfDTO" statementType="STATEMENT">
		select `module`,`key`,`value`,`desc` from ${tableName}
	</select>`
生成的分页sql如下：
`select `module`,`key`,`value`,`desc` from conf_default_lgw LIMIT ?`
分页插件都是预编译期类型，不知道有没有什么办法解决，或者是不需要解决？

完整报错：
查询失败 ### Error querying database. Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 ### The error may exist in URL [jar:file:/E:/yyzx/vsconfig/vsconfig-cjpt-web/target/vsconfig-cjpt-web-0.0.1-SNAPSHOT/WEB-INF/lib/vsconfig-cjpt-java-0.0.1-SNAPSHOT.jar!/mybatis-lhywzx-xml/ConfMapper.xml] ### The error may involve com.foresee.vsconfig.mapper.lhywzx.ConfMapper.getConf ### The error occurred while executing a query ### SQL: select `module`,`key`,`value`,`desc` from conf_default_lgw LIMIT ? ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 ; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1

**Comment by abel533** [comment]
中间有个版本是不需要预编译的，建议在 select 上配置预编译。
