### ISSUE TITLE
使用说明错误或者java.lang.NoClassDefFoundError: com.github.pagehelper.parser.SqlServerParser 

### ISSUE THREAD

**Issue by piaoxuew** [pagehelper/Mybatis-PageHelper#266]
![image](https://user-images.githubusercontent.com/4532348/44512650-da9d4500-a6ed-11e8-9a00-9d3f29bf57fc.png)
这里JSqlParser版本不对，我使用了jsqlparser-1.1，顺利分页成功

**Comment by abel533** [comment]
文档老了。。

我改改。
