### ISSUE TITLE
关于sqlserver2012 不能正确分页的问题

### ISSUE THREAD

**Issue by piaoxuew** [pagehelper/Mybatis-PageHelper#267]
sqlserver2012进行分页时，拼装最终sql语句缺少order by，需要用户自行在sql语句中添加，否则出错，请作者在下一版本修复该问题

**Comment by abel533** [comment]
你用的什么版本？

**Comment by piaoxuew** [comment]
mybatis 3.4.6 pagehelper-5.1.5.jar 这两个，sql server不能正确翻页

**Comment by yf-chen** [comment]
麻烦帮忙看看我这个问题
https://github.com/mybatis-book/book/issues/74
