### ISSUE TITLE
pageNum的的意思是不就是第几页吗? 作者是不是搞错了?

### ISSUE THREAD

**Issue by R1310328554** [pagehelper/Mybatis-PageHelper#270]
我这么调用:
PageHelper.startPage(1, 20);  // 我以前都是这样传参的,   这表示查询第一页, 每页20 行数据.
观察sql, 第一页结果是正确的, 

但是我翻页, 到第二页就不对了: 
PageHelper.startPage(2, 20);
观察sql,  竟然还是第一页的结果,  

然后第三页是第二页的结果, 以此类推...

这不对吧?? pageNum的的意思是不就是第几页吗? 我错了? 作者搞错了?

我后面查看了源码, 发现这个方法似乎有问题: 

    private void calculateStartAndEndRow() {
        this.startRow = this.pageNum > 0?(this.pageNum - 1) * this.pageSize:0;
        this.endRow = this.startRow + this.pageSize * (this.pageNum > 0?1:0);
    }

我感觉作者把 startRow 当做了 pageNum , 而pageNum  的含义就比较奇怪了..  

难道需要我 每个调用startPage的时候,  pageNum  手动加1吗??

**Comment by miaogr86** [comment]
pageNum 就是第几页啊
startRow 是 mysql的 offset

**Comment by R1310328554** [comment]
现在情况是: 
PageHelper.startPage(0, 20);  是第一页的结果
PageHelper.startPage(1, 20);  是第一页的结果
PageHelper.startPage(2, 20);  是第一页的结果
PageHelper.startPage(3, 20);  是第二页的结果
PageHelper.startPage(4, 20);  是第三页的结果

以此类推

**Comment by R1310328554** [comment]
@abel533 
代码是这样的, 没有排序:

		SELECT ROLE_ID,ROLE_NAME,IS_VALID,CREATE_TIME,UPDATE_TIME,REMARK FROM T_ROLE r
		WHERE 1=1
			<if test="role.roleName != null">
				AND r.ROLE_NAME like CONCAT('%','${role.roleName}','%' )
			</if>
			<if test="role.isValid != null">
				AND r.IS_VALID = #{role.isValid}
			</if>

**Comment by R1310328554** [comment]
不好意思, 是我这边代码的问题:
public class WmsPage {
	//当前页
	private int page;
	//每页多少条
	private int rows;
	public int getPage() {
		return page - 1;
	}
...

没注意, 也没想到 getPage 有个坑

**Comment by Soinice** [comment]
一个这么多人用的插件，有bug也是有可能的，但是这么幼稚的bug，你应该先自查，这么多人为什么都没发现
