### ISSUE TITLE
动态传入表名情况下, 所有的参数需要用${}来接收, 使用pageHelper 会爆语法错误,  .....limit?,?   出现这样的问题,大神指导这个怎么解决吗?

### ISSUE THREAD

**Issue by muzitianya** [pagehelper/Mybatis-PageHelper#279]
动态传入表名情况下, 所有的参数需要用${}来接收, 使用pageHelper 会爆语法错误,  .....limit?,?   出现这样的问题,大神指导这个怎么解决吗?

**Comment by abel533** [comment]
有没有详细的错误信息？最好能贴上你代码。

**Comment by ruiluxu** [comment]
使用动态传入表名好像没有拦截，查询统计的sql也没执行。
![image](https://user-images.githubusercontent.com/6949003/45471568-144cf300-b764-11e8-885a-9919ad4b499f.png)
![image](https://user-images.githubusercontent.com/6949003/45471635-46f6eb80-b764-11e8-98bd-90aafb0c4275.png)
![image](https://user-images.githubusercontent.com/6949003/45471684-6ee64f00-b764-11e8-85e8-9c2506b2ae3d.png)

**Comment by Danbaoshan** [comment]
大哥，问题解决了吗？我也是动态表名，然后接受 page,size的时候接受不到，导致语法错误

**Comment by abel533** [comment]
@Danbaoshan 看这里#343
