### ISSUE TITLE
maxpagesize 最大页

### ISSUE THREAD

**Issue by seal90** [pagehelper/Mybatis-PageHelper#282]
我没找到这个参数的设置，若没有的话请考虑添加。因为 pagesize 是从前端传入，所以可能被人为修改，所以是否需要添加一个最大页大小来限制 pagesize。可以在controller 校验，感觉还是在分页实现最终校验比较理想。

**Comment by miaogr86** [comment]
需求不错！

**Comment by abel533** [comment]
有个分页合理化参数，你可以看看文档。

**Comment by seal90** [comment]
reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
如果是这个参数，那么所表述的并不能解决我的问题。
举个例子，使用如下 api 实现分页
startPage(int pageNum, int pageSize) 
如果我传递 pageNum=1&pageSize=100000 那么程序就会查出 100000 条数据，我期望的是最大能查100 条，当然可以通过别的方式来实现这个控制，但是若有这个配置作为最后的防线，可以避免很多的不小心。

**Comment by abel533** [comment]
这种明显的逻辑应该在业务层做。

**Comment by seal90** [comment]
嗯 确实可以通过别的方式来实现防止大页问题，但是将防线放在这个位置可以避免不少问题。

**Comment by lngg057** [comment]
2022年了，这个需求现在有实现吗？请问
