### ISSUE TITLE
如何让自定义的Interceptor在PageInterceptor之前执行呢？

### ISSUE THREAD

**Issue by Lean-King** [pagehelper/Mybatis-PageHelper#283]
想通过Interceptor做数据拦截器，可是PageInterceptor总是在自定义拦截器之前执行，导致得到的sql都是已经分页处理过的，而QueryInterceptor也未能执行，还希望能解答一下，感谢

**Comment by abel533** [comment]
调整拦截器顺序试试

**Comment by philipsm** [comment]
请教下怎么调整拦截器顺序？我只能配置自己的拦截器啊，难道要引入pageHelper的源码么？
