### ISSUE TITLE
在分库分表下group 查询时，返回的totalSize没有分组去重

### ISSUE THREAD

**Issue by dyoner1** [pagehelper/Mybatis-PageHelper#284]
patrol_task_extend_1和 patrol_task_1表进行了分表，一共10个表，进行分组查询count(0)时，统计十个表中的数据，得到的totalSize没有group，直接计算的和
SELECT count(0)
 FROM (SELECT t2.username, t2.user_id
 FROM patrol_task_extend_1 t1
 LEFT JOIN patrol_task_1 t2 ON t1.patrol_task_id = t2.id
 WHERE 1 = 1  GROUP BY t2.user_id) table_count;
得到的结果
{
    "data": {
        "totalSize": 3,
        "resultList": [
            {
                "id": 48,
                "depId": null,
                "username": "调度长2",
                "roleName": "调度员",
                "onLineState": null
            }
        ]
    },
    "errorCode": "0",
    "errorMsg": "请求成功"
}

实际应该totalSize=1

**Comment by abel533** [comment]
resultMap 贴出来看看？是不是用嵌套映射了。

**Comment by dyoner1** [comment]
> resultMap贴出来看看？是不是用嵌套映射了。

表1和表2有一条相同的数据，现在想做分组查询只查询出来一条记录，在查询记录总数的的时候，两个表都返回了数据总数1，但是因为是分表，表1和表2的这条数据是重复的，返回的totalsize是2，并没有对这两条数据合并
