### ISSUE TITLE
超大表分页，有没有优化的方案~比如count语句缓存等

### ISSUE THREAD

**Issue by poolye** [pagehelper/Mybatis-PageHelper#285]
有几张特别大的表（5000万+），平时分页查询的时候，count语句会很慢。而且也不用准确（甚至可以不用）显示总的条数。有没有什么办法可以优化这个分页逻辑。

**Comment by abel533** [comment]
新版本可以配置默认是否执行count，而且在 startPage 方法中也能控制。

如果想缓存，需要自己处理或者用mybatis二级缓存。
