### ISSUE TITLE
关于PageHelper分页结果集的问题类型转换问题

### ISSUE THREAD

**Issue by ljgGit** [pagehelper/Mybatis-PageHelper#288]
实例：
        PageHelper.startPage(1, 2);
        Page<BookInfoDO> bookInfos = (Page<BookInfoDO>) bookInfoDOMapper.selectAll();
        System.out.println(bookInfos.getClass());
        System.out.println(bookInfos.getResult());
查询结果强转Page后， 一般情况下，查询结果 和 分页信息都会外传到其他系统。
所以此时Page对象就需要转成常规数据对象。
目前
**com.github.pagehelper.Page#getResult** 返回的是this, 本身。而非ArrayList对象。
**建议**
此方法能够提供类型转换，数据以原始ArrayList对象返回。

依赖版本
``` 
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.5</version>
        </dependency>
```

**Comment by xiaoyangzhang** [comment]
Page<KeyWordReplyVO> page = PageHelper.startPage(query.getPageNum(), query.getPageSize());
List<KeyWordReplyVO> result = page.getResult();
定义泛型的page对象，page.getResult返回的就是泛型对象
所以没明白【返回的是this, 本身。而非ArrayList对象。】这句话什么意思

**Comment by abel533** [comment]
Page extends ArrayList

**Comment by lafangyuan** [comment]
> @xiaoyangzhang @abel533
> 抱歉没有描述清楚。想表达的意识：想通过page.getResult来更改返回集合容器类型，来摆脱对Page容器的依赖。
> 
> ```
> /**
>  * 通过此方法摆脱对Page对象的依赖
>  *
>  * @return
>  */
> public List<E> getResult() {
>     return new ArrayList<E>(this);
> }
> ```

这个问题解决了没？
