### ISSUE TITLE
有人知道吗?FastJson解析page类只解析集合内的对象..

### ISSUE THREAD

**Issue by A3liu** [pagehelper/Mybatis-PageHelper#289]
`@Test

	public void testPageHelper() {

		BackEndUserDAO bean = beanFactory.getBean(BackEndUserDAO.class);

		PageHelper.startPage(1, 2);

		Page<UserPojo> pageInfo = (Page)bean.findAllUser();

		System.out.println(JSON.toJSON(pageInfo));

		System.out.println(pageInfo);

		assertEquals(0, pageInfo.getStartRow());

		assertEquals(1, pageInfo.getPageNum());

		assertEquals(2, pageInfo.getPageSize());

	}`

如上所示....今天发现FastJson解析Page类分页信息都木有了呢....有人知道原因吗...

[{"lastLogin":1537568715000,"modifiedTime":1537568720000,"password":"2624522","address":"asdf","salt":"0","nickName":"刘耀森","createdTime":1537568718000,"id":1,"age":10,"desc":"哈哈哈哈啊哈哈","status":99,"username":"liuyaosen"},{"lastLogin":1537616334000,"modifiedTime":1537616340000,"password":"2624522","address":"464","salt":"0","nickName":"RuaRUa!~","createdTime":1537616337000,"id":2,"age":56,"desc":"撒范德萨地方","status":1,"username":"liuyaosen2"}]

Page{pageNum=1, pageSize=2, startRow=0, endRow=2, total=3, pages=2}

**Comment by abel533** [comment]
Page 是 List，序列化特殊。。你需要参考 PageInfo。

**Comment by Xanthuim** [comment]
> Page 是 List，序列化特殊。。你需要参考 PageInfo。

你的意思需要把Page转成PageInfo才行，为啥不直接返回PageInfo呢？

**Comment by abel533** [comment]
@Xanthuim Mapper 接口定义的返回值是 List。。。你想直接用 PageInfo 吗？这样的耦合太大了。
