### ISSUE TITLE
关于查询结果  缓存的问题

### ISSUE THREAD

**Issue by xdota3310** [pagehelper/Mybatis-PageHelper#290]
你好  我初次使用你的插件，发现你的插件对已经查询过的分页内容有类似缓存的方式保存着（现象就是再次点击查询过的页面页面反应很快，响应时间很短），我想了解一下pagehelper有没有做类似的将查询的结果保存在缓存中的操作呢，如果有在呢实现的呢（我跟了一下代码好像没有看见实现的地方）

**Comment by abel533** [comment]
支持mybatis二级缓存。。如果你开启了就有效果。
