### ISSUE TITLE
分页页数与页码都为0时，排序不生效

### ISSUE THREAD

**Issue by cdmamata** [pagehelper/Mybatis-PageHelper#292]
版本：5.1.4
PageHelper.startPage(pageNumber, pageLimit, orderby);
当 pageNumber 与 pageLimit 都为0，orderby 不为空时，order by 不生效

**Comment by abel533** [comment]
pageLimit = 0 的时候不会进行分页，可以调用单独orderBy方法。。或者 pageLimit = Integer.MAX_VALUE;

**Comment by yydzxz** [comment]
> Integer.MAX_VALUE

经过测试, 设置为Integer.MAX_VALUE也不行,设置为Integer.MAX_VALUE -1就行了
