### ISSUE TITLE
【bug】page属性篡sql

### ISSUE THREAD

**Issue by hughchan** [pagehelper/Mybatis-PageHelper#296]
在两次web请求中，a请求某查询sql语句设置了page:
PageHelper.startPage(request.getPage(), request.getSize());
PageHelper.orderBy("callout_dial_time desc, session_id desc");
b 请求没有设置page，却在b请求中的某sql语句中出现了a请求中的page信息。
两次请求中的sql是属于不同的mapper的。
想问一下作者，ThreadLocal 变量 LOCAL_PAGE是否会存在在数据库请求结束后没被清除，导致两次请求线程池分配了同一个线程，使用了同一个LOCAL_PAGE的情况。

**Comment by liuzhenji** [comment]
我也遇到类似的LOCAL_PAGE set，get前后不是同一个page的问题

**Comment by liuzhenji** [comment]
#196 统一在那分享了

**Comment by laohubuchiyu** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8

可能是用法不当吧

**Comment by liuzhenji** [comment]
我原因找到了，是因为resonable：true设置下的，分页查询参数合理化造成的重置。不是BUG
