### ISSUE TITLE
查询结果不正确：count总数和page数不正确

### ISSUE THREAD

**Issue by 66545shiwo** [pagehelper/Mybatis-PageHelper#298]
您好：
      我这边用的pagehelp 4.1版本，PageInfo只能对List进行实例；
      如果我设置的接口返回类型是Iterable类型的，我在service层将Iterable转成List传到PageInfo内，count 和page数就不正确了。
     请问是我的问题，还是不支持转换呢

**Comment by 66545shiwo** [comment]
我大概跟了下源码，源码内的page和count结果都是正确的。所以我怀疑是我service层Iterable转List导致的。`List<Entity> list = IteratorUtils.toList(repository.findAllByUserId(userId).iterator());`

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去

**Comment by littlecurl** [comment]
> 我大概跟了下源码，源码内的page和count结果都是正确的。所以我怀疑是我service层Iterable转List导致的。`List<Entity> list = IteratorUtils.toList(repository.findAllByUserId(userId).iterator());`

+1，源码内total正确，转一下List就不对了

**Comment by littlecurl** [comment]
原来是我用错方式了?
我最终解决方式如下:
原先的分页代码:
```
        PageHelper.startPage(1,1);
        List<UserModel> userModelList = userService.getUserListByPage();
        PageInfo<UserModel> userModelPageInfo = new PageInfo<>(userModelList);
```
改为现在的:
```
        Page page = PageHelper.startPage(1,1);
        List<UserModel> userModelList = userService.getUserListByPage();
        PageInfo<UserModel> userModelPageInfo = page.toPageInfo();
```
这样得到的PageInfo数据都是正确的.

**Comment by keegan-x** [comment]
楼上的正解
