### ISSUE TITLE
默认会用效率高的方式。。。但是当SQL无法解析或者有聚合函数，group by等情况时也会直接套一层。

### ISSUE THREAD

**Issue by MurderWind** [pagehelper/Mybatis-PageHelper#303]
_Originally posted by @abel533 in https://github.com/pagehelper/Mybatis-PageHelper/issues/184#issuecomment-371491333_

哪个版本使用效率高的，可否给出一个版本，目前我使用的是
5.1.2 版本仍然是count(0)

**Comment by MurderWind** [comment]
5.1.6 版本也是select count(0)

**Comment by MurderWind** [comment]
column 可以被指定

**Comment by abel533** [comment]
有 group by 一定是嵌套。。

新版本会区分聚合函数和普通函数，只有聚合函数会嵌套。
