### ISSUE TITLE
关于tomcat nio 使用线程池时发现ThreadLocal<Page>无法被清除

### ISSUE THREAD

**Issue by coolbeevip** [pagehelper/Mybatis-PageHelper#307]
我发现一个问题，当使用tomcat nio方式发起请求调用mybatis，当出现使用翻页和不使用翻页的请求大并发时我发现不翻页的请求会从ThreadLocal中取出Page，但是我看SqlUtil中的processPage方法使用finally进行了线程变量的清除，不过好像没有生效，另外我看4.2.0版本中的PageHelper类也增加了清除线程变量的方法，加这个方法的目的是什么，难道你已经发现了会存在无法清除ThreadLocal<Page>的问题？

**Comment by coolbeevip** [comment]
我发现问题的是4.1.6版本

**Comment by xuweiming** [comment]
新版本解决了吗请问

**Comment by coolbeevip** [comment]
> 新版本解决了吗请问

后来发现其实是使用上的问题，官方样例在方法开始前调用PageHelper.startPage 方法，然后框架会在sql执行后自动移除SqlUtil中的LOCAL_PAGE线程对象，本来这样是没有错误的，但是如果调用了PageHelper.startPage，但是没有执行sql，这个时候就不会移除SqlUtil中的LOCAL_PAGE，就会导致我这个问题，（导致没有执行sql的方法有很多，例如自己实现了缓存等），所以我看后期的框架中增加了PageHelper.clearPage方法，所以我想官方样例应该改成如下就ok了

PageHelper.startPage(xxx)
try{
    xxxxx
}finally{
    PageHelper.clearPage()
}
