### ISSUE TITLE
无法理解 public static <E> Page<E> startPage(int pageNum, int pageSize, String orderBy)

### ISSUE THREAD

**Issue by rocbin** [pagehelper/Mybatis-PageHelper#309]
方法声明
`public static <E> Page<E> startPage(int pageNum, int pageSize, String orderBy)`
 static 后面的这个 <E> 是写错了吗？为什么坑了我这个菜鸟呢：
我这么写：`Page<User> page = PageHelper.startPage(1,10, "id desc");`
Java 8 编译报错。
我觉得 `<E>` 是多余的。

**Comment by abel533** [comment]
静态方法必须指定。。你现在应该理解了吧。
