### ISSUE TITLE
实体类包含分页参数，通过 Example 构建查询条件不会自动分页

### ISSUE THREAD

**Issue by gxing19** [pagehelper/Mybatis-PageHelper#312]
实体类里包含了分页参数：pageNum, pageSize; 将实体类传入做为查询参数会自动分页。
但通过 Example 构建查询条件，则不会自动分页，通过 PageHelper 再设置下才会分页。

是这样设计的，还是有其它地方需要再设置下，文档看了没找到相关的。

**Comment by An0nymous0** [comment]
一样的
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql;pageNum=pageNum;pageSize=pageSize;


实体类里+pageNum和pageSize不生效

**Comment by abel533** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md

supportMethodsArguments：支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
