### ISSUE TITLE
共两页,查询第三页的时候还能查询出数据来

### ISSUE THREAD

**Issue by MaRuifu** [pagehelper/Mybatis-PageHelper#321]
共两页,查询第三页的时候还能查询出数据来,且显示第二页的数据

**Comment by dk980241** [comment]
reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。

**Comment by mrzenter** [comment]
问一下 你在哪里看见我邮箱 发给我的

发送自 Windows 10 版邮件应用

发件人: dk980241
发送时间: 2018年12月13日 15:05
收件人: pagehelper/Mybatis-PageHelper
抄送: Subscribed
主题: Re: [pagehelper/Mybatis-PageHelper] 共两页,查询第三页的时候还能查询出数据来 (#321)

reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。

**Comment by raychou1203** [comment]
注意看文档...
设置了 `reasonable=true`

**Comment by MaRuifu** [comment]
好的 谢谢  知道了
