### ISSUE TITLE
集成sharding-jdbc查询时，无法执行分页。

### ISSUE THREAD

**Issue by lxq1008** [pagehelper/Mybatis-PageHelper#324]
<dependency>
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper-spring-boot-starter</artifactId>
			<version>1.2.10</version>
</dependency>

sql写法
  @Override
    public PageInfo<OrderInfo> queryUserOrderPage(UserOrderPageRequest request) {
        PageHelper.startPage(request.getPageIndex(),request.getPageSize(),true);
        List<OrderInfo> orderInfoList = tOrderMainMapper.selectUserOrderInfoList(request);
        return new PageInfo<>(orderInfoList);
    }

Logic SQL: select order_id from t_order_main where user_id = ?   and order_status in  (  ?  )   order by order_id desc LIMIT ? 
sql分页里面只剩下pageSize了。

期望：
Logic SQL: select order_id from t_order_main where user_id = ?   and order_status in  (  ?  )   order by order_id desc LIMIT ### ? ?

注：多数据源情况下。

application.yml配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true
  supportMethodsArguments: true
  params: count=countSql

**Comment by ternence-tao** [comment]
您好，弱弱的问一句，这个问题解决了吗，或者有什么解决办法吗

**Comment by wqwin** [comment]
同求

**Comment by lxq1008** [comment]
自己写分页实现了。

**Comment by BoGeManger** [comment]
同求怎么解决的，能分享下吗

**Comment by lxq1008** [comment]
没用pageHeler。直接把分页参数带到mybatis
select order_id from t_order_main where user_id = ? and order_status in ( ? ) order by order_id desc LIMIT #{startIndex},#{pageSize}

**Comment by xszhe** [comment]
使用 com.github.pagehelper:pagehelper:5.3.0 + sharding-jdbc 5.0 没发现这个问题
