### ISSUE TITLE
Informix跨库查询错误

### ISSUE THREAD

**Issue by lailexin** [pagehelper/Mybatis-PageHelper#325]
![image](https://user-images.githubusercontent.com/5419819/50127307-9db41a00-02ab-11e9-8033-4a457d42de12.png)
解析错误时会导致调用生成的count语句使用了SELECT COUNT(0) 似的配置了countColumn失效
应改成 return getSimpleCountSql(sql, name);  共有三处可能会导致countColumn失效
注: jsqlparser无法正常解析informix跨库查询

**Comment by abel533** [comment]
谢谢，5.1.9 已改。
