### ISSUE TITLE
pagehelper 5.0.0 Paging failure

### ISSUE THREAD

**Issue by wanwujiedao** [pagehelper/Mybatis-PageHelper#33]
This is my pom.xml:
     <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper</artifactId>

            
            <version>4.1.0</version>
            
      </dependency>

Of cause , pagehelper-spring-boot-starter is ok!Only version 5.0.0 is failure.

**Comment by wanwujiedao** [comment]
<version>4.1.0</version>
            
        </dependency>
-->

**Comment by abel533** [comment]
如果没有失败信息我也没法看什么原因。

**Comment by wanwujiedao** [comment]
很是抱歉，没有抛出任何异常信息，用5.0.0版本的时候分页并没有效果，将结果全部查询返回给前端了，4.1.0版本，能够分页成功。我将一个小项目上传的github，敬请过目，希望各位大牛能够找到原因，谢谢！[https://github.com/wanwujiedao/mybatis-pagehelper-5.0.0](url)

**Comment by wanwujiedao** [comment]
[项目地址](https://github.com/wanwujiedao/mybatis-pagehelper-5.0.0)

**Comment by abel533** [comment]
找到原因了：
```java
@Configuration
public class MyBatisConfiguration {

    @Bean
    public PageHelper pageHelper() {
        System.out.println("万物皆导");
        PageHelper pageHelper = new PageHelper();
        Properties p = new Properties();
        p.setProperty("offsetAsPageNum", "true");
        p.setProperty("rowBoundsWithCount", "true");
        p.setProperty("reasonable", "true");
        pageHelper.setProperties(p);
        return pageHelper;
    }
}
```
新版本中，拦截器不是这个类。应该是 `PageInterceptor`

**Comment by wanwujiedao** [comment]
好的，非常感谢，我试试

**Comment by wanwujiedao** [comment]
已经测试成功了，谢谢大哥，大牛，嘿嘿
