### ISSUE TITLE
MyBatis 的mapper.xml中resultMap标签内配置了collection后多表关联分页查询总数据量与映射转换后对象总数据量不一致

### ISSUE THREAD

**Issue by heiyu106** [pagehelper/Mybatis-PageHelper#331]
Mapper.xml 内resultMap 配置如下
`<resultMap id="baseResultMap" type="User">
    <id property="id" column="id" />
    <result property="loginName" column="login_name" />
    <result property="name" column="name" />
    <collection property="roleList" ofType="Role">
        <id property="id" column="role.id" />
        <result property="roleName" column="role.roleName"/>
        <result property="roleEname" column="role.roleEname"/>
    </collection>
</resultMap>
<select id="selectList" resultMap="baseResultMap">
    SELECT
        a.id,  a.login_name,  a.name,
        f.id AS "role.id", f.role_name AS "role.roleName", f.role_ename AS "role.roleEname"
    FROM
	tc_sys_user a
    LEFT JOIN (
	SELECT user_id, role_id  FROM  tc_sys_user_role
	WHERE 1=1
		AND user_id IS NOT NULL AND user_id !=""
		AND role_id IS NOT NULL AND role_id !=""
    ) e ON e.user_id = a.id 
    LEFT JOIN tc_sys_role f ON f.id = e.role_id
    WHERE  1=1
</select>`

查询的总数是关联查询后的总记录数，主表User 表数据会出现重复记录，collection 标签归并部分数据后导致对象数据总量与 select count(SQL) tmp_count 的结果不一致，进而会出现每页的数据量比设置的pageSize数据量要少，分页的页面总数也不正常

**Comment by aeasylife** [comment]
遇到了同样的问题，等待决策是否要弃用

**Comment by aeasylife** [comment]
` <collection property="resultDetailDTOList"
                    ofType="com.cwag.pss.ipss.order.api.dto.trip.TransferFindByCardResultDetailDTO"
                    column="order_id"
                    select="groupForFindByCard">
        </collection>`
将collection中改成调用select方法，也就是将多关系的那部分提取出来，原本的sql里也不用加入多关系，就能成功使用

**Comment by heiyu106** [comment]
是的 在 <resultMap> 节点内配置 collection 节点，并将 colection 节点的 select 属性配置指向一个从表根据其外键字段查询SQL 即可，这个方法之前别人也给我讲了，不过还是要多谢你在这里回复这个问题

**Comment by huskyui** [comment]
> ` <collection property="resultDetailDTOList" ofType="com.cwag.pss.ipss.order.api.dto.trip.TransferFindByCardResultDetailDTO" column="order_id" select="groupForFindByCard"> </collection>`
> 将collection中改成调用select方法，也就是将多关系的那部分提取出来，原本的sql里也不用加入多关系，就能成功使用

感谢了
