### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by liumy001** [pagehelper/Mybatis-PageHelper#334]
1，分页查count拼sql建议不要用子查询直接切割就好，有order by建议去掉order by查count没必要。
2，建议查分页和查list采用异步方式，最起码要有一个开关

**Comment by abel533** [comment]
默认不用子查询，除非有聚合函数或group by。
默认会去 order by。

异步方式可以考虑，目前的逻辑中，如果 count = 0，就不会继续查询。

**Comment by liumy001** [comment]
感觉查询时候还是有数据时候多，异步时候即使多查了一次，对性能影响并不大,所以建议增设分页时候异步开关，让用户自己选择。
