### ISSUE TITLE
pageSize=0,currentPage=0的问题

### ISSUE THREAD

**Issue by zl7261** [pagehelper/Mybatis-PageHelper#337]
pageSizeZero: Default value is false, When this parameter is set to true, if pageSize=0 or RowBounds.Limit = 0 will query all the results (the equivalent of a Paged query did not execute, but the return type of the result is still Page).

reasonable: Rationalization of paging parameters, Default value is false。 When this parameter is set to true, pageNum <= 0 will query the first page, PageNum> pages (over the total number), will query the last page. Default false, the query directly based on parameters.

这两个配置不管如何配置，在pageSize=0,curPage=0的情况下，不会去分页查询页数,回去查询全部数据。
这样就跟pageSizeZero=false或者reasonable=true的说明矛盾了.

这两个配置的作用域在某个情况下是有交叉的。

**Comment by zl7261** [comment]
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  pageSizeZero: false
  params: count=countSql
  reasonable: true

**Comment by wanghuiwen1** [comment]
同问

**Comment by abel533** [comment]
pageSize 和 pageNum 不冲突啊。
