### ISSUE TITLE
MetaObjectUtil 

### ISSUE THREAD

**Issue by zhangxinyuan1** [pagehelper/Mybatis-PageHelper#340]
报如下错误：Could not initialize class com.github.pagehelper.util.MetaObjectUtil ？
mybatis 版本是3.2.4
pagehelper 版本是 5.1.8

**Comment by zhangxinyuan1** [comment]
问题已解决：版本太低导致分页插件拦截器里面反射失败
升级mybatis 版本为：3.4.4   、升级mybatis-spring版本为：1.3.0

**Comment by abel533** [comment]
这是分页插件兼容性没做好导致的，该问题已经解决，将要发布的 5.1.9 支持 mybatis 低版本。#349
