### ISSUE TITLE
请大神给一个动态表名下分页的解决方案吧

### ISSUE THREAD

**Issue by Danbaoshan** [pagehelper/Mybatis-PageHelper#343]
数据库mysql 
如果传动态表名
` <select id="XX" resultMap="XX" statementType="STATEMENT">
  select * from ${tableName}  --tableName 是从作为参数传进来的
</select>`
解析出sql语句后为
`select * from tableName limit ?,?` //?并没有转换为相应的值  
 这样的情况下，就会报语法错误，最后会解析为 select * from tablename limit ?,? 。 其中？，？就是size,page,可能接受的时候用#接受的，导致接受不到 而statementType="STATEMENT" 时参数要用$来接受。有谁能提供一个方案吗？

**Comment by abel533** [comment]
当前的版本只能使用预编译（PREPARED）方式。

动态表名，用 $ 的时候可以是预编译方式。
