### ISSUE TITLE
sqlserver2012 多表连接with(nolock)报错

### ISSUE THREAD

**Issue by yccool** [pagehelper/Mybatis-PageHelper#345]
如：我用的sqlserver2012，分页方式也是按照2012的offset方式，mybatis的查询语句如下：
Select  CC.ClinicID, CC.CaseHistoryNum, CC.CaseHistoryID, CC.DoctorID, CC.ClientRegisterID
From Client CC With(Nolock)
Left Outer Join Register CR With(Nolock) On CC.ClientRegisterID = CR.ClientRegisterID
Where CC.ClientID =  14374

当我使用分页后就报错

SQL: SELECT count(0) FROM Client CC with(nolock) LEFT OUTER JOIN Register CR with(nolock) WHERE CC.ClientID = 14374\r\n### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'WHERE' 附近有语法错误。\n; bad SQL grammar []; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'WHERE' 附近有语法错误。",

从错误来看就是没有On 条件了，省略了“On CC.ClientRegisterID = CR.ClientRegisterID”

请检查一下

**Comment by jiaoyilun** [comment]
关注中，遇到同样问题

**Comment by jiaoyilun** [comment]
遇到同样问题，更新插件5.1.8版本可解决，maven中央仓库有这个版本，不知道这里为什么没更新

**Comment by yccool** [comment]
> 遇到同样问题，更新插件5.1.8版本可解决，maven中央仓库有这个版本，不知道这里为什么没更新

不行的，如果单表查询5.1.8版本是解决了，但是多表连接时还说没解决的，如：
select * from tb a with(nolock)  inner join tb2 b with(nolock) on a.id=b.aid

**Comment by jiaoyilun** [comment]
> > 遇到同样问题，更新插件5.1.8版本可解决，maven中央仓库有这个版本，不知道这里为什么没更新
> 
> 不行的，如果单表查询5.1.8版本是解决了，但是多表连接时还说没解决的，如：
> select * from tb a with(nolock) inner join tb2 b with(nolock) on a.id=b.aid

我这就是多表连接查询

**Comment by yccool** [comment]
> > > 遇到同样问题，更新插件5.1.8版本可解决，maven中央仓库有这个版本，不知道这里为什么没更新
> > 
> > 
> > 不行的，如果单表查询5.1.8版本是解决了，但是多表连接时还说没解决的，如：
> > select * from tb a with(nolock) inner join tb2 b with(nolock) on a.id=b.aid
> 
> 我这就是多表连接查询

在5.1.8版本中多表连接是没有解决这个with(nolock)问题的，我试过了，也跟博主沟通过了，他说是jsqlparser的问题，他没办法

**Comment by jiaoyilun** [comment]
我的sql大概是这样（加工了下，见谅）
`
SELECT  c.* 
FROM p WITH(NOLOCK) 
LEFT JOIN  c WITH(NOLOCK) ON c.a1 = p.b1
LEFT JOIN  c2 WITH(NOLOCK) ON c2.a1 = c.a2
`
我写这个sql的时候，也遇到这个问题，我的解决方法是，升级了5.1.8，另外我的项目里单独引入的有jsqlparser1.4，这个语句执行正常

**Comment by yccool** [comment]
> 我的sql大概是这样（加工了下，见谅）
> `SELECT c.* FROM p WITH(NOLOCK) LEFT JOIN c WITH(NOLOCK) ON c.a1 = p.b1 LEFT JOIN c2 WITH(NOLOCK) ON c2.a1 = c.a2`
> 我写这个sql的时候，也遇到这个问题，我的解决方法是，升级了5.1.8，另外我的项目里单独引入的有jsqlparser1.4，这个语句执行正常

我的不行啊，我的sql如下：
```
<select id="selectDoctorList" resultType="java.util.HashMap" >
	Select AU.UserID, AU.UserName, AU.OrderCount, A2.CodeDesc as Area, AG.Sex
	From ACM_User AU with(Nolock)
	Inner Join ACM_GlobalUser AG with(Nolock) On AU.GlobalUserID=AG.GlobalUserID
	Inner Join Code_Clinic CC with(Nolock) On AU.ClinicID=CC.CodeID
	Inner Join Clinic_Detail CD with(Nolock) On CC.CodeID = CD.ClinicID
	Inner Join Code_Area A1 with(Nolock) On CD.AreaLevel1ID=A1.CodeID
	Inner Join Code_Area A2 with(Nolock) On CD.AreaLevel2ID=A2.CodeID
	<where>
		<if test="area1 != null">
		 AND A1.CodeID = #{area1}
		</if>
		<if test="area2 != null">
		 AND A2.CodeID = #{area2}
		</if>
		<if test="doctorName != null and doctorName!=''">
		 AND AU.UserName like '%'+#{doctorName}+'%'
		</if>
		<if test="clinicAddress != null and clinicAddress!=''">
		 AND CD.Address like '%'+#{clinicAddress}+'%'
		</if>
	</where>
  </select>
```

但最后生成的sql是这样子的
`SELECT count(0) FROM ACM_User AU with(nolock)
INNER JOIN ACM_GlobalUser AG with(nolock) 
INNER JOIN Code_Clinic CC with(nolock) 
INNER JOIN Clinic_Detail CD with(nolock) 
INNER JOIN Code_Area A1 with(nolock) 
INNER JOIN Code_Area A2 with(nolock) 
WHERE A1.CodeID = ? AND A2.CodeID = ? `

On条件没有了

**Comment by jiaoyilun** [comment]
sorry ，我们这边有同事反馈，确实 nolock还是有问题，当时测试可能出了什么问题，以为解决了

**Comment by abel533** [comment]
最新版本 jsqlparser 2.0 解析后的结果，似乎没问题：
```sql
SELECT TOP 10 ClinicID, CaseHistoryNum, CaseHistoryID, DoctorID, ClientRegisterID
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY RAND()) AS PAGE_ROW_NUMBER, ClinicID, CaseHistoryNum, CaseHistoryID, DoctorID
		, ClientRegisterID
	FROM (
		SELECT CC.ClinicID, CC.CaseHistoryNum, CC.CaseHistoryID, CC.DoctorID, CC.ClientRegisterID
		FROM Client CC WITH (NOLOCK)
			LEFT JOIN Register CR WITH (NOLOCK) ON CC.ClientRegisterID = CR.ClientRegisterID
		WHERE CC.ClientID = 14374
	) PAGE_TABLE_ALIAS
) PAGE_TABLE_ALIAS
WHERE PAGE_ROW_NUMBER > 1
ORDER BY PAGE_ROW_NUMBER
```
