### ISSUE TITLE
一个优化建议

### ISSUE THREAD

**Issue by arjenzhou** [pagehelper/Mybatis-PageHelper#347]
若要在 Controller 中直接接受参数使用 Page 对象获取分页参数，而 Page 对象没有实现 IPage 接口，在`getPageFromObject(Object params, boolean required)` 中不能直接获取参数。若直接在 Controller 使用 IPage 接口，接口没有分页属性直接获取不到参数。只能使用 `PageHelper.startPage(page.getPageNum(),page.getPageSize());`

**Comment by raychou1203** [comment]
可以提供一个更简便的方式直接使用 Page 对象作为参数传入 `Page.startPage()`

**Comment by raychou1203** [comment]
自定义 MyPage 类同时继承 Page 、实现 IPage 会有同名方法冲突

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去
