### ISSUE TITLE
急，total数量不对问题

### ISSUE THREAD

**Issue by reallinxu** [pagehelper/Mybatis-PageHelper#348]
使用的版本为 1.2.10
pageSize设置为8以内时查询出来的list类型为arraylist，此时获取total为list.size，没有错误
但当pageSize设置为8或以上，此时list类型为page，获取total为((Page)list).getTotal()，此时获取为0，查询到数据，但是total数量不对，求指导，查询出来的list类型是在哪里进行转换的，怎么设置才能获取正确total，谢谢

**Comment by reallinxu** [comment]
@abel533 麻烦帮忙解答一下，现在获取total不是当前查询总数，pagesize超过8就是0，谢谢啦

**Comment by abel533** [comment]
贴几个 SQL 看看
