### ISSUE TITLE
5.1.8出现NoSuchMethodException

### ISSUE THREAD

**Issue by Shichimiyasatone** [pagehelper/Mybatis-PageHelper#349]
### 环境：
pagehelper：5.1.8
mybatis：3.2.8
mybatis-spring：1.3.1

### 代码：
PageHelper.startPage(pageCurrent, pageSize);
// 出错代码
**List< SysLog> pages = sysLogDao.findAllPageObjects();**
PageInfo< SysLog> pageInfo = new PageInfo<>(pages);

### Mapper.xml:
< select id="findAllPageObjects" resultType="com.sys.entity.SysLog">
	select * from sys_logs
</ select>

### 错误信息：
> java.lang.NoSuchMethodException: org.apache.ibatis.reflection.MetaObject.forObject(java.lang.Object)

### 解决办法：
将pagehelper版本调至5.1.2，问题消失。

**Comment by abel533** [comment]
bug 已解决
