### ISSUE TITLE
生成count查询sql时，导致having中的找不到指定字段

### ISSUE THREAD

**Issue by S01010011** [pagehelper/Mybatis-PageHelper#350]
com.github.pagehelper.parser.CountSqlParser#getSmartCountSql(java.lang.String, java.lang.String)
这个方法中，生成智能的count查询sql中，如果sql中带有having条件，生成的sql中字段会被替换成count(0)，导致异常：Unknown column 'xxx' in 'having clause'

- 比如原sql：
   - `select a,b,c from tb_test having a not null`
- 生成的count查询sql：
   - `select count(0) from tb_test having a not null`
- 异常：
   - `Unknown column 'a' in 'having clause'`

- 现在的解决是：
   - 在sql的外面再套一层select，或者在sql中加入/\*keep orderby\*/。

不知能否根据having判断使用普通的getSimpleCountSql()方法。

**Comment by abel533** [comment]
测试没有问题：
```sql
select count(0) from (select a,b,c from tb_test having a not null) tmp_count
```

**Comment by qinzeduomoxiong** [comment]
确实有这个问题，如果having 不写表名 直接写字段名 pagerhlper的count语句就会识别不到具体是哪一张表的字段

**Comment by yunmengmeng** [comment]
having的问题我也遇到了，后来我把版本升级到了1.4.0，就解决了

**Comment by renzhenqi** [comment]
> 
哈哈哈哈  刚看到你的回复 我都忘了当初我是怎么解决的了
