### ISSUE TITLE
dubbo 调用，分页失效。

### ISSUE THREAD

**Issue by UniqueDong** [pagehelper/Mybatis-PageHelper#351]
dubbo调用，web与service分开部署，在consumer层将返回的list包装成PageInfo是错误的，同时service也没有执行分页查询

**Comment by zhiguangliu** [comment]
分页插件的原理是利用同一个线程的threadlocal变量传递分页标记。dubbo之后，变量无法传递。而且你应该是在web层调用的pagehelper的startpage方法。可以考虑把调用挪到service中。按照命名规则（比如：方法名以ByPage结尾）采用aop的方式实现分页调用。

**Comment by abel533** [comment]
序列化时不要用 `Page`，需要转换提取 `total` 和 list 在传递，最好自己封装一个 PageInfo
