### ISSUE TITLE
sqlutil的优化建议

### ISSUE THREAD

**Issue by 294033186** [pagehelper/Mybatis-PageHelper#353]
这里为了获取一个url个人认为没有必要每次都去连接池获取连接，可以将datasource的name和url缓存起来？博主认为这个可行吗？
![image](https://user-images.githubusercontent.com/31615469/53326839-8041a300-3921-11e9-9e82-5e1377b28f77.png)

**Comment by 294033186** [comment]
不好意思，我看错了，您已经做过缓存了，不好意思啊

**Comment by abel533** [comment]
由于存在动态数据源，真正需要使用的场景无法缓存。
