### ISSUE TITLE
SQL SERVER ISNULL函数不识别

### ISSUE THREAD

**Issue by jiaoyilun** [pagehelper/Mybatis-PageHelper#354]
数据库:sql server
hepler version: 5.1.8
jsqlparser version: 1.2
执行 SELECT ISNULL(tb.a, '') from table tb,提示不支持该sql转为分页sql，
提示错误位置在isnull

**Comment by jiaoyilun** [comment]
补充一下，刚才查看jsqlparser项目，
1.3版本已对isnull函数做了修正
[https://github.com/JSQLParser/JSqlParser/releases/tag/jsqlparser-1.3](url)

**Comment by jiaoyilun** [comment]
在项目中添加jsqlparser最新依赖，问题解决

**Comment by kuhai1234** [comment]
问一下，现在可以支持STUFF和FOR XML PATH 了么。

**Comment by jiaoyilun** [comment]
> 问一下，现在可以支持STUFF和FOR XML PATH 了么。

这个不知道，目前没有用到

**Comment by abel533** [comment]
最新版本的 jsqlparser 已支持：
```sql
SELECT TOP 10 ISNULL(tb.a, '')
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY RAND()) AS PAGE_ROW_NUMBER, ISNULL(tb.a, '')
	FROM (
		SELECT ISNULL(tb.a, '')
		FROM table tb
	) PAGE_TABLE_ALIAS
) PAGE_TABLE_ALIAS
WHERE PAGE_ROW_NUMBER > 1
ORDER BY PAGE_ROW_NUMBER
```
