### ISSUE TITLE
5.1.8中手动创建PageInfo存在报错情况

### ISSUE THREAD

**Issue by lvshuding** [pagehelper/Mybatis-PageHelper#359]
5.1.8版本中，使用此构造函数 public PageInfo(List<T> list, int navigatePages) 创建对象时，如果传入的List = null， 会报错；看源码是在调用super(list)中，没有校验list是否为空，直接获取size()导致，
public PageSerializable(List<T> list) {
        this.list = list;
        if(list instanceof Page){
            this.total = ((Page)list).getTotal();
        } else {
            this.total = list.size();
        }
    }

**Comment by abel533** [comment]
建议封装自己的 PageInfo.
