### ISSUE TITLE
pagehelper 5.0.0版本 动态SQL分页问题

### ISSUE THREAD

**Issue by zhongjunjun** [pagehelper/Mybatis-PageHelper#36]
PageHelper.startPage(1,5);
mapper.executeSql(String sqlStr);//此sql语句是动态传入的，mapper.xml文件写法是${sqlStr}。执行后确实分页了。
PageHelper.clearPage();
mapper.select1(pagram1);//但是这个普通的select 语句都也被分页了。mapper.xml文件写法是select * from **
mapper.select2(pagram1);//这个普通的select 语句都也被分页了。
mapper.select3(pagram1);//这个普通的select 语句都也被分页了。
而我只想分页一次,即让executeSql分页，不想让select1,select2,select3分页。怎么办？
加上PageHelper.clearPage()；也不行。

**Comment by abel533** [comment]
测试过了，没有这种情况，只有第一个会被分页。
可以查看这个测试：
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/test/java/com/github/pagehelper/test/basic/TestExecute.java

**Comment by abel533** [comment]
最终原因是因为dialect配置错了，应该用helperDialect。

**Comment by zhongjunjun** [comment]
前两天忙，不好意思，忘了关了，是我自己的原因，分页插件好着

**Comment by zhongjunjun** [comment]
当时是因为把包含pageNum和pageSize的对象，传到后边的查询方法导致的，耽误你时间了，望见谅。

**Comment by abel533** [comment]
@zhongjunjun 没事。
