### ISSUE TITLE
controller中设置分页参数，在service中执行查询数据库，这样会有问题吗

### ISSUE THREAD

**Issue by chkllchkll** [pagehelper/Mybatis-PageHelper#360]
controller.java  A方法 
void A(){
	PageHelper.startPage(pageNum,pageSize)
       B();//调用service的B方法，B方法中有个查询数据库操作
}
service.java B方法
void B(){
   queryById();//查询数据库，我没有把PageHelper.startPage(pageNum,pageSize)设置在service中
}

controller 调用 service ，这种情况下PageHelper 可以使用吧，不会产生线程安全问题吧 ；

**Comment by initpassion** [comment]
如果B未成功执行， 或者B方法内部的查询未执行，属于分页不安全， 官方文档的介绍说是因为内部用了ThreadLocal参数保存了本次分页的信息。后面的第一个分页查询会消费掉改信息（remove），之前我在项目中遇到过类似的情况， 注意采坑
