### ISSUE TITLE
PageAutoDialect中的动态获取分页方式是否可以提供一个自定义实现

### ISSUE THREAD

**Issue by olderjim** [pagehelper/Mybatis-PageHelper#361]
PageAutoDialect目前是根据jdbcUrl截断获取的数据库信息，如果同时使用sqlserver2012和mysql就不能动态切换了。可以用户自定义实现在何种情况下使用何种delegate么

**Comment by abel533** [comment]
可以动态切换，看更新日志和文档，最新版本可以配置默认的 sqlserver 默认实现。
