### ISSUE TITLE
分页插件单独使用

### ISSUE THREAD

**Issue by qichunlin** [pagehelper/Mybatis-PageHelper#364]
就是我用了普通的sql查询 然后得到一个list集合,结合你们的分页插件,数据不是mybatis查询出来的,是不是就不能分页,因为永远都是显示总页数1,记录数就是数据库页数

**Comment by piaoxuew** [comment]
不能单独使用，这个分页插件就是基于mybatis查询，通过拦截mybatis接口，实现修改sql语句来进行分页的

**Comment by qichunlin** [comment]
好嘞,谢谢解答
