### ISSUE TITLE
关于PageRowBounds分页用例中的一点小疑惑

### ISSUE THREAD

**Issue by initpassion** [pagehelper/Mybatis-PageHelper#366]
//or PageRowBounds
PageRowBounds rowBounds = new PageRowBounds(0, 10);
List<Country> list = countryMapper.selectIf(1, new RowBounds(0, 10));
long total = rowBounds.getTotal();

这里的示例代码有个疑问,  PageRowBounds继承于RowBounds
应该是下面代码才合理吧
PageRowBounds pageRowBounds = new PageRowBounds(0, 10);
List<Country> list = countryMapper.selectIf(1, pageRowBounds );
long total = pageRowBounds.getTotal();

**Comment by abel533** [comment]
对，示例代码写错了。
