### ISSUE TITLE
getPageSize=0

### ISSUE THREAD

**Issue by wanghuiwen1** [pagehelper/Mybatis-PageHelper#367]
`  @Override
    public boolean beforePage(MappedStatement ms, Object parameterObject, RowBounds rowBounds) {
        Page page = getLocalPage();
        if (page.isOrderByOnly() || page.getPageSize() > 0) {
            return true;
        }
        return false;
    }`
page.getPageSize() > 0 此处改为大于-1如何，我觉得pagesize=0的时候返回全部数据并不合适 #337 

>

**Comment by abel533** [comment]
为什么不合适？

**Comment by wanghuiwen1** [comment]
> 为什么不合适？

我理解pagesize为0的时候不应该返回0条记录吗

**Comment by abel533** [comment]
这么理解也对，但是这种改动和低版本不兼容，不是必须的。

**Comment by qrqhuang** [comment]
@abel533 

此处不应该用到`pageSizeZero`这个参数吗。
按你的文档说明： 
> pageSizeZero：默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。

所以期望情况下
- pageSizeZero= false
  返回空结果， 需改造： `com.github.pagehelper.dialect.AbstractHelperDialect#afterCount`
- pageSizeZero= true
  返回全部结果。

**Comment by abel533** [comment]
`pageSizeZero` 最新版本中已经处理正确，可以升级试试。
