### ISSUE TITLE
新数据插入，导致分页数据重复

### ISSUE THREAD

**Issue by gpqhl0071** [pagehelper/Mybatis-PageHelper#368]
问题描述：
分页查询功能，按照ID倒序查询，第一次查询的时候，数据量为20条，第一页展示数据A1 - A10,
点击下一页的之前，插入了一条新纪录，在点击下一页的时候，A10出现在第二页，导致数据的重复出现，

请问此种问题是否有解决方案？

我目前的解决方案，是数据传给前端时，携带唯一ID，前端遍历数组是否存在ID，存在则不展示。

**Comment by ZeyiY** [comment]
这个问题和分页没有什么关系吧，新增加了记录，你分页不久应该A10出现在第二页吗？如果你想不出现，那就用缓存去做吧，根据用户唯一ID，查一页的时候缓存住当时的数据，以后走缓存分页。

**Comment by gpqhl0071** [comment]
> 这个问题和分页没有什么关系吧，新增加了记录，你分页不久应该A10出现在第二页吗？如果你想不出现，那就用缓存去做吧，根据用户唯一ID，查一页的时候缓存住当时的数据，以后走缓存分页。

恩 ，已经有解决方案了，第一页请求额时候，获取一个最新的ID，后面所有的分页，都通过此ID做一个条件，这样就不会受到新增数据的影响了。

[https://stackoverflow.com/questions/55607852/new-data-insertion-resulting-in-duplicate-paging-data?noredirect=1#comment97914020_55607852](url)

**Comment by ZeyiY** [comment]
嗯，这种方案能解决新增数据的影响，但是删除数据的影响就没有办法解决了，不知道你的场景涉及不涉及数据的删除。

**Comment by gpqhl0071** [comment]
> 嗯，这种方案能解决新增数据的影响，但是删除数据的影响就没有办法解决了，不知道你的场景涉及不涉及数据的删除。

恩，目前业务没有涉及到删除记录，如果删除，的确也会导致分页的异常。不过大部分还是新增数据的业务场景比较多。

**Comment by VectorWen** [comment]
我用的一个方案是
where id < 前端回传的最后一条数据ID
order by id desc 
limit 20
