### ISSUE TITLE
如何在代码中使用的第四个方法的疑问

### ISSUE THREAD

**Issue by ACXNX** [pagehelper/Mybatis-PageHelper#370]
在 https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-%E5%A6%82%E4%BD%95%E5%9C%A8%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%BD%BF%E7%94%A8

中介绍的方法四种
```
//第四种，参数方法调用
//存在以下 Mapper 接口方法，你不需要在 xml 处理后两个参数
public interface CountryMapper {
    List<Country> selectByPageNumSize(
            @Param("user") User user,
            @Param("pageNum") int pageNum, 
            @Param("pageSize") int pageSize);
}
//配置supportMethodsArguments=true
//在代码中直接调用：
List<Country> list = countryMapper.selectByPageNumSize(user, 1, 10);
```
这里的Country、User两个Bean对象是什么关系么？为什么需要传入user参数？没太看懂，使用这个例子测试的时候一直没通过，一直都是下面的提示
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.acanx.mbg.dao.countryDao.selectByPageNumSize

**Comment by abel533** [comment]
和 User 无关，后面两个分页参数起作用。。
