### ISSUE TITLE
reasonable=true的实际使用场景是什么

### ISSUE THREAD

**Issue by klvoek** [pagehelper/Mybatis-PageHelper#372]
PageHelper 有一个reasonable属性，默认为null。若配置成true，小与零则会查询第一页，大于实际数据页数则会返回最后一页，即上下限的控制。最大页控制见com.github.pagehelper.Page.setTotal方法。

在使用穷尽分页场景中则可能陷入死循环，造成误用，取大于实际页数的页码始终能返回数据（最后一页的数据），比如实际只有9页，如果查询11页返回的是滴9页的数据而不是空。

穷尽查询

```
do{
    PageHelper.startPage(++page, pageSize);  
    data = DBQUERY  
}while(NotEmpty(data)) 
```

而如果是用户输入的话，正常应该对用户输入上下限进行限制的。那么，reasonable的实际使用场景是什么？

**Comment by abel533** [comment]
例如：新闻列表，如果用户手动输入第1000页，会直接显示最后一页内容。

**Comment by zhengzhenning** [comment]
如此看来，在商城瀑布流分页中，此属性应设置为 `false`

**Comment by abel533** [comment]
@zhengzhenning 对，否则会一直重复出现最后一页内容。
