### ISSUE TITLE
连接查询中使用表别名，传入排序字段时提示字段不明确

### ISSUE THREAD

**Issue by B1gB1gRAin** [pagehelper/Mybatis-PageHelper#377]
调用方式为
PageHelper.startPage(pageNum, pageSize, orderBy);
orderBy 值为create_time.
执行报错 提示：com.microsoft.sqlserver.jdbc.SQLServerException: 列名 'create_time' 不明确。
数据库版本为：sqlserver 2005
pagehelper版本是5.1.4

mapper中语句为：
` select distinct u.user_id, u.dept_id, u.login_name, u.user_name, u.email, u.phonenumber, u.status, u.create_time
	    from sys_user u
			 left join sys_dept d on u.dept_id = d.dept_id
			 left join sys_user_role ur on u.user_id = ur.user_id
			 left join sys_role r on r.role_id = ur.role_id
	    where u.del_flag = '0' and (r.role_id != #{roleId} or r.role_id IS NULL)
	    and u.user_id not in (select u.user_id from sys_user u inner join sys_user_role ur on u.user_id = ur.user_id and ur.role_id = #{roleId})`
**pagehelper生成的sql语句如下**
`SELECT
	TOP 10 user_id,
	dept_id,
	login_name,
	user_name,
	email,
	phonenumber,
	status,
	create_time
FROM
	(
		SELECT
			ROW_NUMBER () OVER (ORDER BY ROW_ALIAS_1 DESC) PAGE_ROW_NUMBER,
			user_id,
			dept_id,
			login_name,
			user_name,
			email,
			phonenumber,
			status,
			create_time
		FROM
			(
				SELECT DISTINCT
					u.user_id,
					u.dept_id,
					u.login_name,
					u.user_name,
					u.email,
					u.phonenumber,
					u.status,
					u.create_time,
					create_time AS ROW_ALIAS_1
				FROM
					sys_user u
				LEFT JOIN sys_dept d ON u.dept_id = d.dept_id
				LEFT JOIN sys_user_role ur ON u.user_id = ur.user_id
				LEFT JOIN sys_role r ON r.role_id = ur.role_id
				WHERE
					u.del_flag = '0'
				AND r.role_id = ?
			) AS PAGE_TABLE_ALIAS
	) AS PAGE_TABLE_ALIAS
WHERE
	PAGE_ROW_NUMBER > 0
ORDER BY
	PAGE_ROW_NUMBER`

**Comment by o0iYi0o** [comment]
我也遇到了同样的问题，

**Comment by o0iYi0o** [comment]
不知道你有没有解决掉

**Comment by abel533** [comment]
下面是升级 jsqlparser 2.0 后生成的 SQL，看着是对的：
```sql
SELECT TOP 10 user_id, dept_id, login_name, user_name, email
	, phonenumber, status, create_time
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY RAND()) AS PAGE_ROW_NUMBER, user_id, dept_id, login_name, user_name
		, email, phonenumber, status, create_time
	FROM (
		SELECT DISTINCT u.user_id, u.dept_id, u.login_name, u.user_name, u.email
			, u.phonenumber, u.status, u.create_time
		FROM sys_user u
			LEFT JOIN sys_dept d ON u.dept_id = d.dept_id
			LEFT JOIN sys_user_role ur ON u.user_id = ur.user_id
			LEFT JOIN sys_role r ON r.role_id = ur.role_id
		WHERE u.del_flag = '0'
			AND (r.role_id != 1
				OR r.role_id IS NULL)
			AND u.user_id NOT IN (
				SELECT u.user_id
				FROM sys_user u
					INNER JOIN sys_user_role ur
					ON u.user_id = ur.user_id
						AND ur.role_id = 1
			)
	) PAGE_TABLE_ALIAS
) PAGE_TABLE_ALIAS
WHERE PAGE_ROW_NUMBER > 1
ORDER BY PAGE_ROW_NUMBER
```

**Comment by cmdegr** [comment]
在重名的字段后面加个 AS.
例如:  t1 t2都有name字段,  在select中 把重名字段后面加个 as
