### ISSUE TITLE
自定义拦截器内部执行sql

### ISSUE THREAD

**Issue by wangjiahao123456** [pagehelper/Mybatis-PageHelper#378]
我自定义了一个拦截器用于业务操作，操作中包含了查询数据库，当该查询同时设置了分页插件执行以后，拦截器中的业务查询同时也会带上我不需要的分页操作，我该怎么做才能让拦截器内部的查询不执行分页查询？

**Comment by abel533** [comment]
和插件配置的顺序有关，解决办法看这里：
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md
