### ISSUE TITLE
分页后数据对象类型转换问题

### ISSUE THREAD

**Issue by babay523** [pagehelper/Mybatis-PageHelper#381]
数据库里查询是User对象，想转为UserVo对象并分页，看文档和代码没有找到一个好的办法，不知道如何处理比较优雅，看到也有人遇到类似问题[https://www.oschina.net/question/3222159_2279148](url)

**Comment by abel533** [comment]
我们实际代码中直接封装的 Orika，分页查询结果是 Page，先取出 total 和你需要的分页信息，然后转换为自己的 `PageVO` 类，例如：
```java
public class PageVO<VO> {
private Long total;
private List<VO> rows;

....
}
```

**Comment by zb315044652** [comment]
`    @Override
    public PageInfo<SystemLogVo> systemLogVoList(SyslogDto syslogDto) {
        PageInfo<SysLogDo> logPage = PageHelper.startPage(syslogDto.getPageNum(), syslogDto.getPageSize())
                .doSelectPageInfo(() ->
                        sysLogMapper.selectByOperatorTime(syslogDto.getBeginTime(), syslogDto.getEndTime()));

        PageInfo<SystemLogVo> voPageInfo = new PageInfo<>();
        if (logPage.getTotal() < 1) {
            BeanUtils.copyProperties(logPage, voPageInfo);
            return voPageInfo;
        }

        List<SystemLogVo> systemLogVos = logPage.getList().stream()
                .map(sysLogDo -> {
                    SystemLogVo vo = new SystemLogVo();
                    vo.setOperateTime(sysLogDo.getOperateTime());

                    StringBuilder logMsg = new StringBuilder();
                    String exceptionDetail = sysLogDo.getExceptionDetail();
                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("[操作异常]");
                    }
                    logMsg.append("执行方法[").append(sysLogDo.getMethod()).append("]");
                    logMsg.append("请求参数[").append(sysLogDo.getParams()).append("]");

                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("错误信息[").append(exceptionDetail).append("]");
                    }

                    vo.setLogMsg(logMsg.toString());
                    return vo;
                }).collect(Collectors.toList());

        BeanUtils.copyProperties(logPage, voPageInfo);
        voPageInfo.setList(systemLogVos);
        return voPageInfo;
    }`

**Comment by zb315044652** [comment]
i do it like this
`
    @Override
    public PageInfo<SystemLogVo> systemLogVoList(SyslogDto syslogDto) {
        PageInfo<SysLogDo> logPage = PageHelper.startPage(syslogDto.getPageNum(), syslogDto.getPageSize())
                .doSelectPageInfo(() ->
                        sysLogMapper.selectByOperatorTime(syslogDto.getBeginTime(), syslogDto.getEndTime()));

        PageInfo<SystemLogVo> voPageInfo = new PageInfo<>();
        if (logPage.getTotal() < 1) {
            BeanUtils.copyProperties(logPage, voPageInfo);
            return voPageInfo;
        }

        List<SystemLogVo> systemLogVos = logPage.getList().stream()
                .map(sysLogDo -> {
                    SystemLogVo vo = new SystemLogVo();
                    vo.setOperateTime(sysLogDo.getOperateTime());

                    StringBuilder logMsg = new StringBuilder();
                    String exceptionDetail = sysLogDo.getExceptionDetail();
                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("[操作异常]");
                    }
                    logMsg.append("执行方法[").append(sysLogDo.getMethod()).append("]");
                    logMsg.append("请求参数[").append(sysLogDo.getParams()).append("]");

                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("错误信息[").append(exceptionDetail).append("]");
                    }

                    vo.setLogMsg(logMsg.toString());
                    return vo;
                }).collect(Collectors.toList());

        BeanUtils.copyProperties(logPage, voPageInfo);
        voPageInfo.setList(systemLogVos);
        return voPageInfo;
    }

`

**Comment by zb315044652** [comment]
> i do it like this

```java
    @Override
    public PageInfo<SystemLogVo> systemLogVoList(SyslogDto syslogDto) {
        PageInfo<SysLogDo> logPage = PageHelper.startPage(syslogDto.getPageNum(), syslogDto.getPageSize())
                .doSelectPageInfo(() ->
                        sysLogMapper.selectByOperatorTime(syslogDto.getBeginTime(), syslogDto.getEndTime()));

        PageInfo<SystemLogVo> voPageInfo = new PageInfo<>();
        if (logPage.getTotal() < 1) {
            BeanUtils.copyProperties(logPage, voPageInfo);
            return voPageInfo;
        }

        List<SystemLogVo> systemLogVos = logPage.getList().stream()
                .map(sysLogDo -> {
                    SystemLogVo vo = new SystemLogVo();
                    vo.setOperateTime(sysLogDo.getOperateTime());

                    StringBuilder logMsg = new StringBuilder();
                    String exceptionDetail = sysLogDo.getExceptionDetail();
                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("[操作异常]");
                    }
                    logMsg.append("执行方法[").append(sysLogDo.getMethod()).append("]");
                    logMsg.append("请求参数[").append(sysLogDo.getParams()).append("]");

                    if (!StringUtils.isEmpty(exceptionDetail)) {
                        logMsg.append("错误信息[").append(exceptionDetail).append("]");
                    }

                    vo.setLogMsg(logMsg.toString());
                    return vo;
                }).collect(Collectors.toList());

        BeanUtils.copyProperties(logPage, voPageInfo);
        voPageInfo.setList(systemLogVos);
        return voPageInfo;
    }
```
