### ISSUE TITLE
Dubbo 使用分页类型转换失败 com.github.pagehelper.PageInfo cannot be cast to java.util.List

### ISSUE THREAD

**Issue by powerttt** [pagehelper/Mybatis-PageHelper#383]
一个页面加载7个初始化方法，同时调用了5个带有PageHelper的方法，另外两个返回List。
出现如下错误：

返回List的：
`com.github.pagehelper.PageInfo cannot be cast to java.util.List`

返回Page的
`.xx.xx.entity.EmployeeView cannot be cast to com.github.pagehelper.PageInfo`

这是线程的问题嘛

**Comment by abel533** [comment]
PageInfo 不是 List，Page 是。
