### ISSUE TITLE
5.0.1版本中指定dialect无效

### ISSUE THREAD

**Issue by andersonme** [pagehelper/Mybatis-PageHelper#385]
4.1.1中我们指定MySQL的dialect是这样的
PageHelper pageHelper = new PageHelper();
        Properties properties = new Properties();
        properties.setProperty("offsetAsPageNum","true");
        properties.setProperty("rowBoundsWithCount","true");
        properties.setProperty("reasonable","true");
        properties.setProperty("dialect","mysql");
        pageHelper.setProperties(properties);

换到5.0.1之中是怎么设置呢？
我用 properties.setProperty("dialect","com.github.pagehelper.dialect.helper.MySqlDialect")不起作用，看代码是在执行skip(MappedStatement ms, Object parameterObject, RowBounds rowBounds) 的时候直接返回了true。

**Comment by abel533** [comment]
新版本中有 helperDialect 和 dialect 两个参数，文档对参数有介绍。

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去
