### ISSUE TITLE
增加了一个计算列后就开始各种报错

### ISSUE THREAD

**Issue by ifu25** [pagehelper/Mybatis-PageHelper#386]
原来的语句是正常执行没有问题的，如下：
```
    <!--查询所有单据-->
    <select id="findAll" resultType="co.weiku.framework.model.DataEntity">
        select a.Guid,
               ProManager,
               WorkOrderType,
               a.Name,
               WorkNote,
               b.Name                             TeamName,
               ConstructionSite,
               a.MaterialGuid,
               c.Code                          as MaterialCode,
               c.FullName                         MaterialName,
               d.FullName                         MatStdSortName
        from RMC_WorkOrder a
                 left join dbo.SYS_OrgFrame b on a.TeamGuid = b.Code and b.ParentGuid is null
                 left join dbo.BAS_Material c on a.MaterialGuid = c.Guid
                 left join BAS_MatStdSort d on a.MatStdSortGuid = d.Guid
        where a.ConfirmUser is null
          and b.Guid = #{LegalUnitGuid}
        order by a.ContractBillNO desc
    </select>
```

后来增加了一个计算列`iif(a.MaterialGuid is null, 0, 1) as IsMaterial,`，然后就报错了，修改后代码如下：
```
    <!--查询所有单据-->
    <select id="findAll" resultType="co.weiku.framework.model.DataEntity">
        select a.Guid,
               ProManager,
               WorkOrderType,
               a.Name,
               WorkNote,
               b.Name                             TeamName,
               ConstructionSite,
               iif(a.MaterialGuid is null, 0, 1) as IsMaterial,
               a.MaterialGuid,
               c.Code                          as MaterialCode,
               c.FullName                         MaterialName,
               d.FullName                         MatStdSortName
        from RMC_WorkOrder a
                 left join dbo.SYS_OrgFrame b on a.TeamGuid = b.Code and b.ParentGuid is null
                 left join dbo.BAS_Material c on a.MaterialGuid = c.Guid
                 left join BAS_MatStdSort d on a.MatStdSortGuid = d.Guid
        where a.ConfirmUser is null
          and b.Guid = #{LegalUnitGuid}
        order by a.ContractBillNO desc
    </select>
```
**报错如下：**
> 除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效

**尝试1：**
看了下执行的 sql，增加计算列后将我写的 sql 放到了`select count(0) from ( xxx) `中，这样我写的语句就有 `order by`肯定就会报上面的错。于是我网上查找到了 `手写 count 查询支持`，于是定义了一个专门用于查询 count 的 sql 如下：
```
    <!--查询记录数-->
    <select id="findAll_COUNT" resultType="Long">
        select count(*)
        from RMC_WorkOrder a
                 left join dbo.SYS_OrgFrame b on a.TeamGuid = b.Code and b.ParentGuid is null
        where a.ConfirmUser is null
          and b.Guid = #{LegalUnitGuid}
    </select>
```
结果又报错：
> com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!

**尝试2：**

我又把`findAll`中的 `order by` 去掉。还是报错：` 不支持该SQL转换为分页查询!`

**尝试3：**
我把 `PageHelper.startPage(pageIndex, pageSize, false);`加了个`false`还是报错

只有去掉计算列` iif(a.MaterialGuid is null, 0, 1) as IsMaterial`就没有问题，只要添加上，无论如何也不也。实现没办法了。

**Comment by ifu25** [comment]
尝试4：
我把我写的`findAll`语句整个放到 `select * from (xxxx) as t order by t.bbb` 任然会报错`不支持该SQL转换为分页查询`

**Comment by ifu25** [comment]
![20190518115856935](https://user-images.githubusercontent.com/5575008/57964232-54541d80-7964-11e9-981f-95a2dcdc7ec5.png)

**Comment by abel533** [comment]
这是由于 jsqlparser 无法解析 sql 导致的。

**Comment by ifu25** [comment]
> 这是由于 jsqlparser 无法解析 sql 导致的。

谢谢，我换成 `case when` 就没有问题了。
看来依赖的 `jsqlparser` 版本不支持 `iif` 语法，
有没计划什么时候升级 `jsqlparser` 呢，我看新版本似乎是支持的。

**Comment by abel533** [comment]
最新版本 jsqlparser 生成的 SQL 如下，你可以试试能不能执行：
```sql
SELECT TOP 10 Guid, ProManager, WorkOrderType, Name, WorkNote
	, TeamName, ConstructionSite, IsMaterial, MaterialGuid, MaterialCode
	, MaterialName, MatStdSortName
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY ROW_ALIAS_1 DESC) AS PAGE_ROW_NUMBER, Guid, ProManager, WorkOrderType, Name
		, WorkNote, TeamName, ConstructionSite, IsMaterial, MaterialGuid
		, MaterialCode, MaterialName, MatStdSortName
	FROM (
		SELECT a.Guid, ProManager, WorkOrderType, a.Name, WorkNote
			, b.Name AS TeamName, ConstructionSite
			, iif(a.MaterialGuid IS NULL, 0, 1) AS IsMaterial
			, a.MaterialGuid, c.Code AS MaterialCode, c.FullName AS MaterialName, d.FullName AS MatStdSortName, a.ContractBillNO AS ROW_ALIAS_1
		FROM RMC_WorkOrder a
			LEFT JOIN dbo.SYS_OrgFrame b
			ON a.TeamGuid = b.Code
				AND b.ParentGuid IS NULL
			LEFT JOIN dbo.BAS_Material c ON a.MaterialGuid = c.Guid
			LEFT JOIN BAS_MatStdSort d ON a.MatStdSortGuid = d.Guid
		WHERE a.ConfirmUser IS NULL
			AND b.Guid = 1
	) PAGE_TABLE_ALIAS
) PAGE_TABLE_ALIAS
WHERE PAGE_ROW_NUMBER > 1
ORDER BY PAGE_ROW_NUMBER
```

**Comment by ifu25** [comment]
> 最新版本 jsqlparser 生成的 SQL 如下，你可以试试能不能执行：
> 
> ```sql
> SELECT TOP 10 Guid, ProManager, WorkOrderType, Name, WorkNote
> 	, TeamName, ConstructionSite, IsMaterial, MaterialGuid, MaterialCode
> 	, MaterialName, MatStdSortName
> FROM (
> 	SELECT ROW_NUMBER() OVER (ORDER BY ROW_ALIAS_1 DESC) AS PAGE_ROW_NUMBER, Guid, ProManager, WorkOrderType, Name
> 		, WorkNote, TeamName, ConstructionSite, IsMaterial, MaterialGuid
> 		, MaterialCode, MaterialName, MatStdSortName
> 	FROM (
> 		SELECT a.Guid, ProManager, WorkOrderType, a.Name, WorkNote
> 			, b.Name AS TeamName, ConstructionSite
> 			, iif(a.MaterialGuid IS NULL, 0, 1) AS IsMaterial
> 			, a.MaterialGuid, c.Code AS MaterialCode, c.FullName AS MaterialName, d.FullName AS MatStdSortName, a.ContractBillNO AS ROW_ALIAS_1
> 		FROM RMC_WorkOrder a
> 			LEFT JOIN dbo.SYS_OrgFrame b
> 			ON a.TeamGuid = b.Code
> 				AND b.ParentGuid IS NULL
> 			LEFT JOIN dbo.BAS_Material c ON a.MaterialGuid = c.Guid
> 			LEFT JOIN BAS_MatStdSort d ON a.MatStdSortGuid = d.Guid
> 		WHERE a.ConfirmUser IS NULL
> 			AND b.Guid = 1
> 	) PAGE_TABLE_ALIAS
> ) PAGE_TABLE_ALIAS
> WHERE PAGE_ROW_NUMBER > 1
> ORDER BY PAGE_ROW_NUMBER
> ```

我在我项目中将` jsqlparser 2.0 `引入。结果执行报错：
`net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()Ljava/util/List;`
另见你之前说 https://github.com/pagehelper/Mybatis-PageHelper/issues/34 得用指定版本。

所以请教下我目前是不是还不能用`jsqlparser 2.0`，你的回复只是说最新版jsqlparser`可以解析我的sql了，但我还是没法生产环境使用是吧。

**Comment by abel533** [comment]
先直接在数据库试试上面的 SQL。。马上会发布 5.1.9 版本，使用的 jsqlparser 2.0

**Comment by ifu25** [comment]
非常感谢，已升级到`5.1.9`，搞定了。
