### ISSUE TITLE
该插件能结合 LEFT JOIN 实现一对多查询时的分页吗？

### ISSUE THREAD

**Issue by bingoogolapple** [pagehelper/Mybatis-PageHelper#39]
![image](https://cloud.githubusercontent.com/assets/8949716/25086976/54be5880-239e-11e7-80d8-647cd24b2688.png)

![image](https://cloud.githubusercontent.com/assets/8949716/25086986/6154410e-239e-11e7-8c4a-7295b31829b4.png)

![image](https://cloud.githubusercontent.com/assets/8949716/25087054/d43fd26e-239e-11e7-96dc-513b60cb6055.png)

显示用户列表的时候想同时显示用户所属的所有公司名称，所以用了 LEFT JOIN 来实现一对多，目前结合该插件分页查询后总的条数和单独执行 SQL 的结果是一样的「但是希望分页的时候能按左表来计算分页属性，该插件能通过某种配置来实现这种一对多的查询吗？」

**Comment by abel533** [comment]
仔细想想都不能自动实现，一对多（一对一）会去重，也只有全部查询出来之后才能知道总数。

所以这种分页只能手写。

**Comment by bingoogolapple** [comment]
thx

**Comment by maybeyj** [comment]
不能使用懒加载吗
