### ISSUE TITLE
构造分页时能不能提供startRow方法不要单纯提供startPage,这样的可扩张性是不是更高一点

### ISSUE THREAD

**Issue by liyunq** [pagehelper/Mybatis-PageHelper#391]
构造分页时不能提供startRow方法不要单纯提供startPage,这样的可扩张性是不时更高一点？
虽然本质上传入pagenum时,就可以知道startrow，但是当我接收到的参数是startrow时，就很尴尬了，
因为不能从startrow推导出准确的pagenum

**Comment by abel533** [comment]
看这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/page/PageMethod.java#L157
