### ISSUE TITLE
oracle 分页改了不能走索引了啊

### ISSUE THREAD

**Issue by bsklqgy** [pagehelper/Mybatis-PageHelper#392]
SELECT * FROM ( SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( SELECT t.* FROM table1 t order by t.createdate desc) TMP_PAGE) WHERE ROW_ID <= ? AND ROW_ID > ? oracle方言分页怎么改这种了,不能走索引啊

**Comment by abel533** [comment]
原来什么样？

**Comment by bsklqgy** [comment]
三层嵌套的的写法

**Comment by abel533** [comment]
你上面发的 SQL 也是三层嵌套

**Comment by bsklqgy** [comment]
可以走索引的这样SELECT * FROM ( SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( SELECT t.* FROM table1 t order by t.create_date desc ) TMP_PAGE WHERE ROWNUM <= ? ) WHERE ROW_ID > ?

**Comment by abel533** [comment]
上面这种写法在很多情况下的分页数据有问题。

如果你需要上面的方式，可以扩展一下。

**Comment by abel533** [comment]
即将发布的5.2.0增加了 Oracle9iDialect 方式可选。
