### ISSUE TITLE
最新pageHelper支持mybatis的嵌套结果分页了吗

### ISSUE THREAD

**Issue by ZaneGeng** [pagehelper/Mybatis-PageHelper#393]
由于嵌套结果方式会导致结果集被折叠，因此分页查询的结果在折叠后总数会减少，所以无法保证分页结果数量正确，这个问题能否修复？

**Comment by abel533** [comment]
不能被修复。。这种情况下想自动分页就要查询全部，等mybatis处理完嵌套关系再返回。。

根本起不到分页的作用，只能手写。
