### ISSUE TITLE
查出来的数据，跟打印出来的sql通过Navicat查出的数据不一致？

### ISSUE THREAD

**Issue by yoyoyoga** [pagehelper/Mybatis-PageHelper#397]
# pageinfo
![image](https://user-images.githubusercontent.com/18576341/58869089-230f7780-86f0-11e9-986c-bac25f403d23.png)

# Navicat查的数据
![image](https://user-images.githubusercontent.com/18576341/58869129-37537480-86f0-11e9-8bde-9f16531c77c1.png)

为啥不一样呢？

**Comment by abel533** [comment]
sql 不全，看不出来。。你有排序吗？

**Comment by yoyoyoga** [comment]
> sql 不全，看不出来。。你有排序吗？

这是控制台打印的sql
`SELECT
	t.id,
	t.category_id,
	t.brand,
	t.type,
	t.`name`,
	t.second_name,
	t.img_url,
	t.price,
	t.sale_price,
	t.cost_price,
	t.quantity,
	t.warn_quantity,
	t.views,
	t.`status`,
	t.description,
	t.length,
	t.serial_number,
	t.distribution,
	t.sale_service,
	t.specification,
	t.weight,
	t.create_time,
	t.create_id,
	t.modify_time,
	t.modify_id,
	mc.NAME AS categoryName,
	sd.NAME AS typeName 
FROM
	m_commodity t
	LEFT JOIN m_category mc ON mc.id = t.category_id
	LEFT JOIN (
SELECT
	s.`value`,
	s.`name` 
FROM
	s_dictionary s 
WHERE
	1 = 1 
	AND s.parent_id = '269827693909127168' 
	AND s.`status` = 1 
	) sd ON sd.`value` = t.type 
WHERE
	1 = 1 
ORDER BY
	t.create_time DESC 
	LIMIT 10`

**Comment by abel533** [comment]
直接通过 JDBC 查询试试数据是否一致，很有可能是排序条件导致的。。

或者先改成根据id排序试试。

**Comment by yoyoyoga** [comment]
> 直接通过 JDBC 查询试试数据是否一致，很有可能是排序条件导致的。。
> 
> 或者先改成根据id排序试试。

改成根据id排序数据是一致的。。

**Comment by yoyoyoga** [comment]
数据是批量导入的，每一批的create_time都是一样的，导致排序异常
