### ISSUE TITLE
分页求和，能否指定调用另外一个sql语句

### ISSUE THREAD

**Issue by iamdiffuser** [pagehelper/Mybatis-PageHelper#400]
目前的分页
PageHelper.startPage(2, 3);
List list = auditLogManager.fetchAll(hm);
 //用PageInfo对结果进行包装
 PageInfo page = new PageInfo(list);

我发现求count的时候是通过 select count(0) from (原有的SQL)，不知道是否有地方设置，比如靠后缀名count来调用让我调用另外一个sql语句

**Comment by iamdiffuser** [comment]
比如在xml定义了
<select id="pageSelectcount" resultType="long">........
<select id="pageSelect" resultMap="TestResult">.......
当我通过pageSelect分页的时候，求count的时候，会用pageSelectcount

**Comment by abel533** [comment]
看这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#504---2017-08-01
