### ISSUE TITLE
插件里面使用staff函数就会报错是为什么呢

### ISSUE THREAD

**Issue by xiaoxiaoxiaodouzi** [pagehelper/Mybatis-PageHelper#402]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
既然有报错。。。报错信息呢？

如果是 jsqlparser 的异常，那就是目前不支持解析这个函数。

**Comment by xiaoxiaoxiaodouzi** [comment]
普通查询使用这个函数没有问题，但是只要是用到了分页，就会报错无法转换。
`Caused by: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!`

**Comment by xiaoxiaoxiaodouzi** [comment]
> 既然有报错。。。报错信息呢？
> 
> 如果是 jsqlparser 的异常，那就是目前不支持解析这个函数。

普通查询使用这个函数没有问题，但是只要是用到了分页，就会报错无法转换。
Caused by: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!

**Comment by xiaoxiaoxiaodouzi** [comment]
> 既然有报错。。。报错信息呢？
> 
> 如果是 jsqlparser 的异常，那就是目前不支持解析这个函数。

![image](https://user-images.githubusercontent.com/36183399/59646238-a036f400-91a8-11e9-9222-ec84a8c84186.png)

**Comment by xiaoxiaoxiaodouzi** [comment]
> 既然有报错。。。报错信息呢？
> 
> 如果是 jsqlparser 的异常，那就是目前不支持解析这个函数。

是否是目前不支持解析这个函数呢？

**Comment by abel533** [comment]
提供的异常位置不对，看不出来。
