### ISSUE TITLE
pagehelper 性能问题（不同版本表现差异）

### ISSUE THREAD

**Issue by bluesword12350** [pagehelper/Mybatis-PageHelper#403]
### 使用环境
* 数据库类型和版本: PostgreSQL 

### 版本性能问题
一个复杂SQL查询，开始使用pagehelper-spring-boot-starter:1.2.12 添加依赖
平均耗时为8000ms+
更换为 pagehelper:5.1.10 + 配置config 后 平均耗时为 700ms+
后尝试多个版本（5.1.10 - 4.2.0） 平均耗时均为 700ms+ 
更换为 pagehelper:4.1.6 后平均耗时为 300ms+

**Comment by abel533** [comment]
看不同版本的 SQL 是否有明显区别

**Comment by bluesword12350** [comment]
`public PageHelper pageHelper() {
        PageHelper pageHelper = new PageHelper();
        Properties properties = new Properties();
        properties.setProperty("offsetAsPageNum", "true");
        properties.setProperty("rowBoundsWithCount", "true");
        properties.setProperty("reasonable", "true");
        properties.setProperty("dialect", "postgresql");
        pageHelper.setProperties(properties);
        return pageHelper;
    }`

**Comment by bluesword12350** [comment]
我上次测试没有注意观察SQL变化，但是我的测试集中在一个小时内进行，期间除了变更pagehelper版本以外没有修改其他任何代码，一会儿我再简单测试一下，再给你反馈一次

**Comment by bluesword12350** [comment]
上次测试确实有问题，5.0+版本 耗时 700ms+ 是因为 config 没有生效，网上确实有博客说用5.0+版本分页插件 只能用pagehelper-spring-boot-starter 来添加配置，但这也反过来说明 用分页插件进行分页效率反倒比移除分页插件效率还要低，这个时间消耗肯定不是SQL的原因。
目前我测试 中 4.2.1和4.1.6 时间消耗上基本一致。我一会儿继续测试一下 pagehelper-spring-boot-starter 版本影响。

**Comment by bluesword12350** [comment]
pagehelper-spring-boot-starter：1.2.12/1.2.10 平均耗时 4000ms+
pagehelper-spring-boot-starter 都依赖的是 pagehelper：5.0+
5.0+ 前几个版本没有提供，我们代码中用到的 startPage(int pageNum, int pageSize, String orderBy)
时间原因，我就不进行详细测试了。

**Comment by bluesword12350** [comment]
我想采用 pagehelper：4.2.1 结果 4.2.1/4.2.0 平均耗时为 700ms+ 偶尔还有 1200ms+的耗时出现
4.1.6 平均耗时为 300ms+ 。绕了一圈还是回来了。麻烦帮忙看一下，难道是配置的问题。因为我和同事发现是 pagehelper 影响性能后，我同事就到网上找博客试了一下，刚好用的是4.1.6，结果试了一圈4.1.6就是表现最好的，不会这么巧吧，是不是配置的原因？我这边先采用4.1.6版本了，麻烦作者看一下了。

**Comment by bluesword12350** [comment]
@abel533

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去
