### ISSUE TITLE
SQLServer with ( nolock ) 分页失败

### ISSUE THREAD

**Issue by kylixs** [pagehelper/Mybatis-PageHelper#404]
- [Y ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.10
* 数据库类型和版本: SqlServer
* JDBC_URL: jtds

#### 原 SQL

```sql
select * from xxx with ( nolock ) where xxx = xxx
```

#### 期望的结果：

分页正确，但是分页失败了

## 功能建议

调试发现RegexWithNolockReplaceSql的正则的兼容性不好，不能匹配nolock前后包含空格的情况。
```
    @Override
    public String replace(String sql) {
        return sql.replaceAll("((?i)\\s*(\\w+)\\s*with\\s*\\(nolock\\))", " $2_PAGEWITHNOLOCK");
    }
```
建议修改为：
```
((?i)\\s*(\\w+)\\s*with\\s*\\(\\s*nolock\\s*\\))
```

**Comment by abel533** [comment]
这里的空格看着多余，如果有这种需要可以自己实现通过配置来替换。

**Comment by kylixs** [comment]
开发人员不了解这个写法， 对于他们来说 with ( nolock )  与 with (nolock) 是没有太大区别的，不能太多拼写限制

**Comment by abel533** [comment]
即将发布的5.2.0允许有空格。
