### ISSUE TITLE
having中使用的是前面select里生成的虚拟字段，生成count时报错，找不到该虚拟字段

### ISSUE THREAD

**Issue by Muscleape** [pagehelper/Mybatis-PageHelper#411]
## 场景说明
规则表（table_rule），其中有两个字段标识该规则的有效期，分别是规则有效起始日期（start_time）和规则有效截止日期（end_time）；规则的状态（rule_state）不能落库，在每次查询时，需要由当前的系统时间，根据start_time和end_time来判定规则的状态（0：已失效；1：生效中；2：未生效）；
## 演示SQL
```sql
-- sql所下所示（只查询生效中状态的规则）：
SELECT 
CASE
        WHEN CURDATE() < start_time THEN 3
        WHEN CURDATE() > end_time THEN 0
        ELSE 2
        END AS rule_state
FROM table_rule
HAVING rule_state = 2；
```
## 异常说明
在执行计算该SQL的count时，由于组装的SQL中已经没有临时字段（rule_state），导致SQL异常

**Comment by abel533** [comment]
生成的 SQL 什么样？

**Comment by Muscleape** [comment]
> 生成的 SQL 什么样？

SELECT 
count(0)
FROM table_rule
HAVING rule_state = 2；

**Comment by abel533** [comment]
最新版本已解决。
