### ISSUE TITLE
用Page<T> 封装返回对象list，本来查询不想分页，查询前没有调用startPage方法，但是查询结果却给添加了分页查询

### ISSUE THREAD

**Issue by lianhan** [pagehelper/Mybatis-PageHelper#412]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.10
* 数据库类型和版本: mysql 5.6.44-86.0

#### 错误描述：
mybatis mapper中用Page<T> 封装返回对象list，本来查询不想分页，查询前没有调用startPage方法，但是查询结果却给添加了分页查询，这种情况偶尔会出现。

**Comment by abel533** [comment]
看这儿：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8
