### ISSUE TITLE
对分页结果处理时，分页返回total错误

### ISSUE THREAD

**Issue by dasonXu** [pagehelper/Mybatis-PageHelper#417]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: pagehelper-spring-boot-starter1.2.12
* 数据库类型和版本: 5.6
*配置：
pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

PageHelper.startPage(pageNum, pageSize);
 List<xxx> list = xxxMapper.getxxx(userId, status);
for(list){}
PageInfo pageInfo = new PageInfo(result);
当我调用时分页后,对返回的list进行了循环（因为要特殊处理某些字段），然后在使用PageInfo封装分页结果时发现错误：
数据库中有20条数据，
当pageNum=1，pageSize=50时，结果与期望相符
当pageNum=1，pageSize=10时，total为10，页数为1

但当我在查询后直接使用PageInfo pageInfo = new PageInfo(result)，中间不进行其他处理的话，结果便是正确的，如果是我的打开方式有问题，那这种情况有什么优雅的处理方式？

**Comment by ljgstudy** [comment]
for(list){} 处理的逻辑能否贴一下？
另外，xxxMapper.getxxx(userId, status);返回的是个Page对象，首先猜测的一种可能是会不会在for(list){}中做了某些操作破坏了Page对象造成的？

**Comment by dasonXu** [comment]
循环里，只是单纯的get model的属性，然后根据时间，set一下返回给前端的文案。
list<B> listB;
PageHelper.startPage(pageNo, pageSize);
List<A> listA =AMapper.get();
for(a : list<A>){
    B b = new B(a.get());
    list<B>.add(b);
}
PageInfo pageInfo = new PageInfo(listB);

**Comment by ljgstudy** [comment]
那就很清楚了，listA看起来是个List, 其实不然，他实际是个page对象，然而listB是个真正的list。
可以debug一下PageInfo pageInfo = new PageInfo(listB)这段代码...
good luck！

**Comment by dasonXu** [comment]
thanks，看到了，只不过我想有没有优雅点的写法
public PageSerializable(List<T> list) {
        this.list = list;
        if (list instanceof Page) {
            this.total = ((Page)list).getTotal();
        } else {
            this.total = (long)list.size();
        }

    }

**Comment by ljgstudy** [comment]
已知的信息不能给出很具体的建议，大概方向：
1、比较List<T> listA, List<TT> listB, 确认T和TT是否是同一个类型，如果是的话，其实没必要将listA倒腾到listB中去，额外的值只遍历一遍listA就行了，这样不破坏listA；
2、看有没有办法将for(list)()干掉，mapper返回的分页好的数据直接暴露给消费者；

@abel533 这个问题怎么看？

**Comment by dasonXu** [comment]
如果是同类型，我就没必要再创个list了，但是dao层的数据又不想直接返回给消费者；没有优雅点的写法的话，是不是只能先将listA强转成Page对象，然后复制相应的分页信息到最终我想返回PageInfo

**Comment by ljgstudy** [comment]
也可以改造dao, dao层的数据格式就是要返回给消费者的格式 ：）

**Comment by dasonXu** [comment]
改造dao层不合适，我先就这样用吧：）

**Comment by MMMbka789** [comment]
你好，我也遇见了这个问题, 我给前端需要listB ，我一直想我代码能 优美点 ，最终写了一个工具类
![image](https://user-images.githubusercontent.com/39337686/62787668-c8333b80-baf7-11e9-9aa9-a32924ecd5fb.png)
![image](https://user-images.githubusercontent.com/39337686/62787697-d4b79400-baf7-11e9-8c6f-a4c99bf28895.png)

**Comment by MMMbka789** [comment]
![image](https://user-images.githubusercontent.com/39337686/62788087-c4ec7f80-baf8-11e9-8eea-e45db6c5baa7.png)
 补图

**Comment by MMMbka789** [comment]
![](http://image.ymxlass.com/20190809225625_th44j7_Screenshot.jpeg)

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去

**Comment by jannal** [comment]
@dasonXu @MMMbka789 @ljgstudy 
扩展一个静态方法是不是就可以了

```java
public class PageInfoExt<T> extends PageInfo<T> {

    public static <T, R> PageInfo<R> of(List<T> list, Function<T, R> mapper) {
        if (list instanceof Page) {
            Page<T> page = (Page<T>) list;
            List<R> newList = page.getResult()
                    .stream()
                    .map(mapper)
                    .collect(Collectors.toList());
            PageInfo<R> newPageInfo = new PageInfo<>(newList);
            org.springframework.beans.BeanUtils.copyProperties(page.toPageInfo(), newPageInfo, "list");
            return newPageInfo;
        }
        throw ValidateParamsException.valueOfParamsIllegal("list不是Page实例");
    }

}
```

**Comment by uyoaix** [comment]
修改下写法就可以了
`
public PageInfo<ItemInfoResp> itemList(ItemListReq req) {
  Page<ItemInfoResp> pages = PageHelper.startPage(req.getPageNum(), req.getPageSize());
  List<ItemDTO> itemList = itemMapper.getItemList(req.getStatus());
  // 这个要放在mapper查询后面
  PageIngo<ItemInfoResp> itemPageInfo = pages.toPageInfo();
  List<ItemInfoResp>  itemListResp = itemList.stream.map(item -> {
    ItemInfoResp resp = new ItemInfoResp();
     resp.setxxx();
   return resp;
});
itemPageInfo.setList(itemListResp);
return itemPageInfo;
}

`
