### ISSUE TITLE
自定义count

### ISSUE THREAD

**Issue by hb0730** [pagehelper/Mybatis-PageHelper#418]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本:`pagehelper-spring-boot-starter 1.2.12`
* 数据库类型和版本: `mysql 5.7.20-log`
* JDBC_URL: mysql8.0.6 驱动

# 自定_COUNT
在使用自定义count时，当自定count获取的数据为null，分页查询保存
查看您的项目代码时发现
```
  public static Long executeManualCount(Executor executor, MappedStatement countMs, Object parameter, BoundSql boundSql, ResultHandler resultHandler) throws SQLException {
        CacheKey countKey = executor.createCacheKey(countMs, parameter, RowBounds.DEFAULT, boundSql);
        BoundSql countBoundSql = countMs.getBoundSql(parameter);
        Object countResultList = executor.query(countMs, parameter, RowBounds.DEFAULT, resultHandler, countKey, countBoundSql);
        Long count = ((Number)((List)countResultList).get(0)).longValue();
        return count;
    }
```
**(List)countResultList).get(0)** 在此之前并未做`countResultList`的大小或者为空判断

**Comment by xuzhengbin** [comment]
没有结果返回的是0

**Comment by hb0730** [comment]
> @hb0730 你是怎么解决的，自定义count返回0就出现这个空指针了

时间过久，忘了，我们现在不再使用[Mybatis-PageHelper](https://github.com/pagehelper/Mybatis-PageHelper) ，使用[MP](https://github.com/baomidou/mybatis-plus)自带Page

**Comment by Z-Beatles** [comment]
@hb0730 我估计这里还是个bug？历史项目，看来针对这种复杂SQL我还是手写count吧
