### ISSUE TITLE
求大神解答

### ISSUE THREAD

**Issue by orchpo** [pagehelper/Mybatis-PageHelper#420]
pageHelper版本：5.0.4

我也是用page<T>返回封装的list，最开始存pagesize是3，然后不想用分页了，就把startPage注释，但是还是会分页，但如果把3换成5，就不会出现这样的事。之前在issues看到有人出了同样的问题，下面的解决方法是说线程会存储数据，可我每次都清空tomcat。线程都被清了

**Comment by abel533** [comment]
估计是你代码编译的缓存，clean后试试。。。和线程没关系。
