### ISSUE TITLE
多数据库时的bug

### ISSUE THREAD

**Issue by gaohuixx** [pagehelper/Mybatis-PageHelper#424]
我配置了两个数据源，一个是mysql，一个是oracle，且这两个数据源都用到了分页插件。结果：程序启动后，如果我首先访问mysql分页，那么再访问oracle分页就会有问题，依然用的是mysql的语法拼的分页语句，反之亦然

我大致看了一下源码，在**PageInterceptor**拦截器中，只有一个**Dialect**，就是说拦截mysql和oracle用的都是这一个，至于具体创建的是mysql还是oracle方言，是在第一次访问时创建的，这就导致了上面我说的问题

我感觉应该一个数据源对应一个方言比较合理

**Comment by fangjinuo** [comment]
Sqlhelper 试一试GitHub：sqlhelper
