### ISSUE TITLE
能不能支持下自定义LIMIT位置的分页

### ISSUE THREAD

**Issue by icesugar** [pagehelper/Mybatis-PageHelper#427]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议
`select * from t1  where dmaketime>'2019-01-01' order by ts limit 100000,10`
分页很多的时候 查询最后一页组装出来的sql是这样的，结果会很慢很慢。
通过下面方式避免回表会快到0.016秒
`select a.* from t1 a,(select id from t1  where dmaketime>'2019-01-01' order by ts limit 100000,10) b where a.id=b.id` 
但是就没办法用pagehelper了，我现在是单独写了个SQL
`select a.* from t1 a,(select id from t1  where dmaketime>'2019-01-01' order by ts {#LIMIT#}) b where a.id=b.id` 
然后修改pagehelper的`MySqlDialect`和`CountSqlParser` 去替换掉 `{#LIMIT#}` 
但是当不用pagehelper分页时这个SQL 就不正确了，因为`{#LIMIT#}` 就不符合mybatis写法

**Comment by JanYunkai** [comment]
同问，有办法支持吗

**Comment by abel533** [comment]
这种方式依赖太强，也不容易理解，可以自己尝试提供一个dialect实现。

**Comment by fangjinuo** [comment]
已在这里支持上了 f6244b3e350847160ac4b35611b52301de593a3e

**Comment by flynnxin0730** [comment]
同问，有办法支持吗
