### ISSUE TITLE
自动生成count 语句对 not like 查询解析错误

### ISSUE THREAD

**Issue by xuLeon** [pagehelper/Mybatis-PageHelper#428]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
select  xxx,xxx 
        from table_name where category = 2  and  type not like 'V6%'
          order by create_time desc
生成的count 语句：
SELECT count(0) FROM table_name WHERE category = 2 AND NOT  type LIKE 'V6%'"
### 使用环境

* PageHelper 版本: 5.1.9
* 数据库类型和版本: mysql 5.7
* JDBC_URL: xxx

### SQL 解析错误
, Token 'NOT' , Unsupported char found in SQL 
#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by swzhu-harry** [comment]
select * from xx where A not like  'xxx'    分页查询 拦截生成count的时候  被修改为：.... where not A not like 'xxx';
严重bug

**Comment by abel533** [comment]
升级到最新的jsqlparser3.2版本解决，对应将要发布的分页插件5.2.0版本。
