### ISSUE TITLE
关于生成_PageHelper和 _Count的MapperStatement问题

### ISSUE THREAD

**Issue by dengxxiang** [pagehelper/Mybatis-PageHelper#429]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

你好:
比如我是通过 getAllUser 这个id查询并分页,那么插件帮我
生成带_PageHelper和 _PageHelper_Count的MapperStatement加入configuration后,如果我想写一个脚本重新加载user.xml后,这个xml里的MapperStatement可以生效,那么带_PageHelper和 _PageHelper_Count的MapperStatement我该怎么删除或者让他失效呢.
可能这属于mybatis的范畴,源码说不定有对应方法,但本人研究不深,希望大拿指点迷津.
谢谢....

### 使用环境

* PageHelper 版本: 3.6.3
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
好像在哪儿见过这个问题，题主好像已经实现了。

**Comment by dengxxiang** [comment]
是啊,在码云上也提问了一遍,现在已经解决了

**Comment by donglonglong** [comment]
为啥邮件都回复到我邮箱里了


------------------
  






------------------ 原始邮件 ------------------
发件人: "dengxxiang"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 晚上8:59
收件人: "pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [pagehelper/Mybatis-PageHelper] 关于生成_PageHelper和 _Count的MapperStatement问题 (#429)




是啊,在码云上也提问了一遍,现在已经解决了
