### ISSUE TITLE
pageNum大于pages时，PageInfo类的judgePageBoudary返回数据有误

### ISSUE THREAD

**Issue by xjcherie** [pagehelper/Mybatis-PageHelper#432]
例如：当pageNum = 2，pages = 1时，返回的值为
        isFirstPage = false
        isLastPage = false
        hasPreviousPage = true
        hasNextPage = false
即：不是最后一页，但是没有下一页，是不是应该将isLastPage的判断改为
> this.isLastPage = this.pageNum >= this.pages || this.pages == 0;

**Comment by abel533** [comment]
PageInfo 提供了太多不必要的属性，建议自己封装一个，别依赖这里的 PageInfo。

**Comment by fangjinuo** [comment]
[sqlhelper](http://github.com/fangjinuo/sqlhelper)支持近100种数据库，包括绝大部分国产数据库，可以无缝从pagehelper 切换过去，，并且没有这个问题
