### ISSUE TITLE
java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupBy()

### ISSUE THREAD

**Issue by peterzy-ios** [pagehelper/Mybatis-PageHelper#435]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.10
* 数据库类型和版本: mysql/8.0.15

详细说明，尽可能提供(伪)代码示例。

**Comment by PETERZer** [comment]
调用 PageHelper.startPage(page, rows); 这行代码的时候报的错

**Comment by PETERZer** [comment]
补充：
Jsqlparser版本：2.0

**Comment by Burt-L** [comment]
@PETERZer  你找找是不是在哪个地方引入了非最新版本的pagehelper，把版本都改成最新的就好了。

**Comment by abel533** [comment]
jsqlparser版本不一致。可以看当前项目不同版本中的 pom.xml 中依赖的版本，也可以直接从下面连接选择版本后，查看依赖版本：
https://mvnrepository.com/artifact/com.github.pagehelper/pagehelper
