### ISSUE TITLE
startPage（）和SQL语句执行顺序不同会带来什么影响？

### ISSUE THREAD

**Issue by Noneplus** [pagehelper/Mybatis-PageHelper#436]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本:1.2.5
* 数据库类型和版本:mysql 5.7.27
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 大致情况描述
```
List<UserInfo> userInfos =userInfoMapper.getUserTen();
        System.out.println(userInfos);

        PageHelper.startPage(pageNum,pageSize);

        PageInfo<UserInfo> pageInfo = new PageInfo<UserInfo>(userInfos);
        System.out.println(pageInfo);
        model.addAttribute("pageInfo",pageInfo);
```
其中   PageHelper.startPage(pageNum,pageSize);必须在List<UserInfo> userInfos =userInfoMapper.getUserTen();之后才能正常执行sql语句。

之前是把sql查询放在   PageInfo<UserInfo> pageInfo = new PageInfo<UserInfo>(userInfos);里面的。

## sql语句
```
@Select("SELECT * FROM user_info ORDER BY ID DESC LIMIT 10")
```

对于其他没有limit的sql语句跟上述问题无关。

**Comment by HCJ-shadow** [comment]
@Select("SELECT * FROM user_info ORDER BY ID DESC LIMIT 10")
    public List<UserInfo> getUserTen();

//redis
    @RequestMapping("/redis")
    public String redis(@RequestParam(defaultValue = "1") int pageNum,
                       @RequestParam(defaultValue = "10") int pageSize,
                       Model model)
    {
        //????  PageHelper.startPage(pageNum,pageSize);和List<UserInfo> userInfos =userInfoMapper.getUserTen();
        //的顺序不能颠倒，为什么？？？
        List<UserInfo> userInfos =userInfoMapper.getUserTen();
        System.out.println(userInfos);

        PageHelper.startPage(pageNum,pageSize);

        PageInfo<UserInfo> pageInfo = new PageInfo<UserInfo>(userInfos);
        System.out.println(pageInfo);
        model.addAttribute("pageInfo",pageInfo);
        return "redis";
    }

**Comment by abel533** [comment]
执行前处理。。执行完就没用了。。（仍然绑定在当前线程，会让下一次select产生莫名其妙的分页）。
