### ISSUE TITLE
Page<E>是否考虑过继承自链表(LinkedList)Page<E>

### ISSUE THREAD

**Issue by passedbylove** [pagehelper/Mybatis-PageHelper#440]
数组(ArrayList)和链表(LinkedList)数据结构的本质区别在于:链表即用即申请内容，数组一次性申请空间，不够了再扩充。扩充规则具体见ArrayList源代码。用LinkedList能节省栈开销，遍历的时候不管是基于迭代还是按数组索引，性能相差不大，为什么没有用他？分页数据量小？忽略不记？

**Comment by abel533** [comment]
分页查询时，数据量基本上是确定的，而且不会很大，`ArrayList` 正好。
