### ISSUE TITLE
PageHelper-SpringBoot + OrderByHelper 排序无效！

### ISSUE THREAD

**Issue by wc394915432** [pagehelper/Mybatis-PageHelper#45]
这是POM： 
		`<dependency>
		    <groupId>com.github.pagehelper</groupId>
		    <artifactId>pagehelper-spring-boot-starter</artifactId>
		    <version>1.1.0</version>
		</dependency>`
		
		`<dependency>
		    <groupId>tk.mybatis</groupId>
		    <artifactId>orderby-helper</artifactId>
		    <version>0.0.1</version>
		</dependency>`

分页+排序代码片段：
`PageHelper.startPage(pageBean.getPage(),pageBean.getRows());
		//添加排序字段  
			OrderByHelper.orderBy(baseEntity.getSort()+" "+baseEntity.getOrder());`

还有 MyBatis.xml的配置： `<plugins>
    
    <plugin interceptor="tk.mybatis.orderbyhelper.OrderByHelper"/>
	</plugins>`

结果是没排序

**Comment by freprite** [comment]
我试了没有问题，是不是插件配置顺序放错了？
`<plugins>
	    <plugin interceptor="com.github.pagehelper.PageInterceptor">
	        <property name="helperDialect" value="mysql"/>
	    </plugin>
	    <plugin interceptor="tk.mybatis.orderbyhelper.OrderByHelper"/>
    </plugins>`

**Comment by wc394915432** [comment]
我没有配置：<plugin interceptor="com.github.pagehelper.PageInterceptor"> <property name="helperDialect" value="mysql"/> </plugin>  
因为我不是用了pagehelper-spring-boot-starter嘛，所以Mybatis.xml只配置了OrderBy的Interceptor，是不是需要加上PageInterceptor？

**Comment by abel533** [comment]
是顺序的问题，boot方式需要通过注解控制顺序，可以参考：http://blog.csdn.net/isea533/article/details/53975720

**Comment by abel533** [comment]
后续版本会在分页插件上增加排序功能。

**Comment by zhengmingliang** [comment]
@abel533 请问现在PageHelper插件上增加排序功能了吗

**Comment by abel533** [comment]
@zhengmingliang 5.1.0 版本已经添加了

**Comment by zhengmingliang** [comment]
@abel533 恩恩，好的，谢谢，刚查了下maven库，最新版本为5.1.0-beta2

**Comment by zhengmingliang** [comment]
@abel533 换了5.1.0的PageHelper插件使用无论使用PageHelper.startPage(pageNum,pageSize,orderBy)
还是直接使用PageHelper.orderBy(orderBy)排序无效啊，这个配置文件中还需要配置什么吗
![image](https://user-images.githubusercontent.com/16442564/29803989-0d2b7836-8cb2-11e7-957b-87bdc365b59b.png)
![image](https://user-images.githubusercontent.com/16442564/29804050-7456e09a-8cb2-11e7-8aa1-bf7e12f2de08.png)

**Comment by abel533** [comment]
你把下面的 count 查询删了。

**Comment by penghaige** [comment]
orderby是否可以以方法入参的方式传入？

**Comment by abel533** [comment]
@penghaige 支持
