### ISSUE TITLE
七百万数据分页直接跳到最后一页会很慢怎么解决呢？

### ISSUE THREAD

**Issue by hezhuoyukuai** [pagehelper/Mybatis-PageHelper#457]
七百万数据分页直接跳到最后一页会很慢，请问有什么好的解决办法吗？

**Comment by 2YSP** [comment]
单表数据超过五百万就会出现性能问题了，分库分表吧。或者在id自增的情况下先查最后一页的第一条数据的id，然后where id >= 那个id limit pageSize

**Comment by hezhuoyukuai** [comment]
id是uuid，不是自增长的.

**Comment by 2YSP** [comment]
主键UUID是种很蠢的做法，UUID很长会造成索引占用空间较多。把数据存到Redis中利用list数据结构分页。

**Comment by wangwei-ying** [comment]
MySQL并不是跳过offset行，而是取offset+N行，然后返回放弃前offset行，返回N行，那当offset特别大的时候，效率就非常的低下，要么控制返回的总页数，要么对超过特定阈值的页数进行SQL改写。

```sql
SELECTa.* FROM 表1 a,(select id from 表1 where 条件LIMIT 100000,20 ) b wherea.id=b.id
```

**Comment by shuyoulin** [comment]
SELECTa.* FROM 表1 a,(select id from 表1 where 条件LIMIT 100000,20 ) b wherea.id=b.id  对应 PageHelper该怎么写sql

**Comment by shuyoulin** [comment]
SELECTa.* FROM 表1 a,(select id from 表1 where 条件LIMIT 100000,20 ) b wherea.id=b.id 对应 PageHelper该怎么写sql和代码
