### ISSUE TITLE
关于使用PageInterceptor切面的问题

### ISSUE THREAD

**Issue by ghost** [pagehelper/Mybatis-PageHelper#458]
在使用这个切面后，假使不使用 pagehelper 进行分页，如果参数相同的话也一样会默认走分页，版本5.0.0

**Comment by abel533** [comment]
开启参数分页了吗？

7. `supportMethodsArguments`：支持通过 Mapper 接口参数来传递分页参数，默认值`false`，分页插件会从查询方法的参数值中，自动根据上面 `params` 配置的字段中取值，查找到合适的值时就会自动分页。
使用方法可以参考测试代码中的 `com.github.pagehelper.test.basic` 包下的 `ArgumentsMapTest` 和 `ArgumentsObjTest`。
