### ISSUE TITLE
由于sql注释引起的BUG

### ISSUE THREAD

**Issue by Chen-Jt** [pagehelper/Mybatis-PageHelper#459]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.0.0
* 数据库类型和版本: mysql 8.0.18

### 当查询的sql语句中存在注释时，有可能会导致分页失效
比如mapper中的sql如下
```sql
    select * from emp 
 --   order by emp.emp_id
```
分页参数：
```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```
生成的sql如下：
```sql
    select * from emp 
 --   order by emp.emp_id LIMIT 10
```
这样注释就会导致分页失败
### 修复建议
可以换行后再添加分页参数`LIMIT 10`来避免这种情况下的bug

**Comment by TTcheng** [comment]
我也遇到了这个问题，另外如果行尾是mysql风格的#注释，还会导致count计数时报错，暂时的解决办法是把注释都写为xml格式
