### ISSUE TITLE
无知请教

### ISSUE THREAD

**Issue by LoveVsLike** [pagehelper/Mybatis-PageHelper#460]
## 无知请教
CacheFactory类里面的createCache方法，为什么要添加Class.forName("com.google.common.cache.Cache")；想不明白添加这行代码的意义，能否请教大神指导

部分代码如下:
try {
      Class.forName("com.google.common.cache.Cache");
      return new GuavaCache<K, V>(properties, prefix);
 } catch (Throwable t) {
     return new SimpleCache<K, V>(properties, prefix);
 }

**Comment by abel533** [comment]
如果你的依赖中存在 guava，就用 guava 的缓存实现，否则就用 SimpleCache

**Comment by LoveVsLike** [comment]
> 如果你的依赖中存在 guava，就用 guava 的缓存实现，否则就用 SimpleCache

那我是不是可以理解为 Class.forName("com.google.common.cache.Cache"); 可有可无，因为我认为没有这句应该也不会有问题吧？

**Comment by Foredoomed** [comment]
不是，这句是要创建GuavaCache类，如果没有这句还怎么创建呢

**Comment by LoveVsLike** [comment]
不对啊！我验证了，有没有这句代码都不影响执行的结果的，不知道作者为啥这么写
