### ISSUE TITLE
如何自定义拦截器，实现super.startPage(pagedRequest);前对SQL进行预处理，添加数据权限条件？

### ISSUE THREAD

**Issue by lengjiaxin** [pagehelper/Mybatis-PageHelper#463]
### 如何自定义拦截器，实现super.startPage(pagedRequest);前对SQL进行预处理，添加数据权限条件？

### 怎样操作在不影响正常分页，前提下动态添加Sql条件

**Comment by abel533** [comment]
目前不支持，后续版本会增加一些分页插件的拦截器用于特殊处理。

可以参考这里实现拦截器：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md

**Comment by lengjiaxin** [comment]
OK 感谢大佬
