### ISSUE TITLE
双数据库类型错误

### ISSUE THREAD

**Issue by sensuwang** [pagehelper/Mybatis-PageHelper#465]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.
### 使用环境
* PageHelper 版本: 
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.5</version>
        </dependency>
* 数据库类型和版本: 
sqlserver 2008
greenplum
* JDBC_URL: 
jdbc:sqlserver://******
jdbc:postgresql://******

###错误描述
项目中使用到sqlserver 数据 以及gp数据库，
部署项目后 ，假如先做对于sqlserver部分的查询操作，
则gp部分的查询会使用错误的分页（报错： top不可用（gp中）），
但是此时sqlserver是好用的。
假如先做对于gp的查询操作，
则sqlserver部分的查询会使用错误的分页（报错：limit不可用（sqlserver中））。

###猜测
猜测是由于pagehelper只检测一次数据库类型。

**Comment by sensuwang** [comment]
由于某些原因不能写两个mybatis-config.xml 只能使用同一个

**Comment by abel533** [comment]
开启动态监测，看文档中的 autoRuntimeDialect

**Comment by moxuandeng** [comment]
碰到了同样的问题, 配置autoRuntimeDialect为true确实解决了

文档在https://pagehelper.github.io/docs/howtouse/
