### ISSUE TITLE
fulltext search

### ISSUE THREAD

**Issue by yl1935** [pagehelper/Mybatis-PageHelper#47]
在使用mysql5.7版本的fulltext查询时 count语句变成了
select count(0) from (select * from table WHERE MATCH (`text`) AGAINST (? IN BOOLEAN MODE)) tmp_count
未使用fulltext全文检索查询时count语句为
SELECT count(0) FROM table

为什么fulltext全文检索的count语句不能直接是
SELECT count(0) FROM table WHERE MATCH (`text`) AGAINST (? IN BOOLEAN MODE)) 感觉这样效率更高

**Comment by abel533** [comment]
这是由于 jsqlparser 无法解析 fulltext 导致的。

**Comment by yl1935** [comment]
不过好像也没啥影响，测试后发现两个语句执行时间差不多好像没什么区别，估计mysql对语句进行了优化。谢谢你的解答！

**Comment by abel533** [comment]
没影响最好。
