### ISSUE TITLE
support impala？how to config and use？

### ISSUE THREAD

**Issue by FrankWang307** [pagehelper/Mybatis-PageHelper#478]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
和 mysql 一样就用 mysql 就行。

如果想要自动根据jdbcurl识别，可以配置: https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#513---2018-04-07

增加 dialectAlias 参数，允许配置自定义实现的 别名，可以用于根据 JDBCURL 自动获取对应实现，允许通过此种方式覆盖已有的实现，配置示例如（多个时分号隔开）：
```xml
<property name="dialectAlias" value="oracle=com.github.pagehelper.dialect.helper.OracleDialect"/>
```
根据你自己的情况修改具体值。
