### ISSUE TITLE
与TypeHandler协作时的问题

### ISSUE THREAD

**Issue by chunzhenzyd** [pagehelper/Mybatis-PageHelper#479]
[-] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板

Bug：当ResultMap中包含带有sql语句的TypeHandler的Result时，total返回有误（返回的是TypeHandler中sql count）

### 使用环境

* PageHelper 版本: com.github.pagehelper:pagehelper-spring-boot-starter:1.2.13
* 数据库类型和版本: mysql8
* JDBC_URL:

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
@Select("SELECT * FROM audit")
    @Results(id = "AuditResultMap", value = { @Result(property = "auditee", column = "auditee_id", one = @One(select = Mybatis.USER_SIMPLE)),
            @Result(property = "object", javaType = Object.class, column = "object_id", jdbcType = JdbcType.INTEGER, typeHandler = ObjectTypeHandler.class),
            @Result(property = "path", column = "{type=object_type,auditeeId=auditee_id}", one = @One(select = Mybatis.AUDITEE_AUDIT_PATH)),
            @Result(property = "records", column = "id", many = @Many(select = Mybatis.AUDIT_RECORDS)),
            @Result(property = "objectType", column = "object_type", jdbcType = JdbcType.NVARCHAR, id = false),
            @Result(property = "objectId", column = "object_id", jdbcType = JdbcType.INTEGER, id = false),
            @Result(property = "id", column = "id", jdbcType = JdbcType.INTEGER, id = true) })
    List<Audit> search();

@Slf4j
@MappedTypes(Object.class)
@MappedJdbcTypes(JdbcType.INTEGER)
public class ObjectTypeHandler extends BaseTypeHandler<Object> {

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, Object object, JdbcType jdbcType) throws SQLException {
        ps.setString(i, "");
    }

    @Override
    public Object getNullableResult(ResultSet rs, String columnName) throws SQLException {
        return convert(rs.getString("object_type"), rs.getInt("object_id"));
    }

    @Override
    public Object getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
        return convert(rs.getString("object_type"), rs.getInt("object_id"));
    }

    @Override
    public Object getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {
        return convert(cs.getString("object_type"), cs.getInt("object_id"));
    }

    private Object convert(String objectType, Integer objectId) {
        try {
            Object service = FieldUtils.readField(ServiceContainer.serviceContainer, objectType + "Service", true);
            return MethodUtils.invokeMethod(service, "getProfileById", objectId);
        } catch (IllegalAccessException | NoSuchMethodException | InvocationTargetException exception) {
            log.error("get audit object error!", exception);
            return null;
        }
    }

}

```

#### 期望的结果：

返回Audit的数量（假设有100条Audit记录，每条Audit包含一个Object）
但是返回的是ObjectTypeHandler中的含有的sql语句的count
ObjectTypeHandler中的含有的sql语句： SELECT * FROM materiial WHERE id=#{id} LIMIT 1
观察到countSql会生成两条，一条是count Audit（=100），一条count Material （=1）
total返回为1，即第二条count Material覆盖了第一条count Audit

### 完整异常信息

```
无
```

## 功能建议

public JSONObject getProfileById(Integer id) throws JsonProcessingException {
        Material material = materialRepository.searchProfileById(id);
        String string = new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE).writeValueAsString(material);
        JSONObject data = JSON.parseObject(string);
        JSONObject extra = new JSONObject();
        List<Terminal> terminals = terminalService.getByMaterial(id);
        JSONArray extraTerminals = new JSONArray();
        for (Terminal terminal : terminals)
            extraTerminals.add(
                    new JSONObject().fluentPut("id", terminal.getId()).fluentPut("name", terminal.getName()).fluentPut("mac", terminal.getMac()));
        extra.fluentPut("url", material.getUrl()).fluentPut("terminals", extraTerminals);
        data.put("extra", extra);
        return data;
    }

getProfileById 包含多条sql语句。

## 结论

PageHelper对TypeHandler支持有Bug

**Comment by chunzhenzyd** [comment]
Anybody ？

**Comment by abel533** [comment]
不支持嵌套SQL。
