### ISSUE TITLE
可否支持国产数据库人大金仓kes？

### ISSUE THREAD

**Issue by shpunishment** [pagehelper/Mybatis-PageHelper#484]

**Comment by shpunishment** [comment]
人大金仓kes地址
https://kes.kingbase.com.cn/

**Comment by fangjinuo** [comment]
Sqlhelper 早已支持了。https://github.com/fangjinuo/sqlhelper

**Comment by shpunishment** [comment]
> Sqlhelper 早已支持了。https://github.com/fangjinuo/sqlhelper

非常感谢~
