### ISSUE TITLE
对接postgresql，分页查询怎么返回数组

### ISSUE THREAD

**Issue by jianxw** [pagehelper/Mybatis-PageHelper#488]
PageHelper.startPage(page, pageSize);
QueryWrapper queryWrapper = new QueryWrapper<>().eq("is_delete", 0);
List<CourseEntity> list = baseMapper.selectList(queryWrapper);

CourseEntity里面有字段是数组，分页查询出来的数据不是数组,保存的时候数组能够正常保存。

@TableField(typeHandler = ArrayTypeHandler.class)
    private String[] coursePicUrl;

**Comment by abel533** [comment]
加不加分页对该列的返回结果没影响。
