### ISSUE TITLE
在分页的情况下，使用的ResultHandler，导致统计总数执行异常

### ISSUE THREAD

**Issue by rockingGitHub** [pagehelper/Mybatis-PageHelper#499]
com.github.pagehelper.util.ExecutorUtil#executeAutoCount
![image](https://user-images.githubusercontent.com/21156751/76695449-79b3d400-66ba-11ea-8087-4697921aea0e.png)
返回的countResultList 是空集合的，后面get(0) 抛出越界异常

**Comment by abel533** [comment]
什么原因导致的？
