### ISSUE TITLE
Page class doesn't implements Serializable

### ISSUE THREAD

**Issue by ettingshausen** [pagehelper/Mybatis-PageHelper#502]
https://github.com/pagehelper/Mybatis-PageHelper/blob/5fcbb90b61f5cf6eb63013103a73977bea19fe9b/src/main/java/com/github/pagehelper/Page.java#L39

**Comment by abel533** [comment]
`ArrayList implements Serializable`

**Comment by ettingshausen** [comment]
> `ArrayList implements Serializable`  

Thanks for the correction. It seems I had a problem when I use `Page` as a result type of Dubbo remote method and I mixed the exception in console output.
I'll close it :joy:.
