### ISSUE TITLE
total = 1 但是 集合size = 0

### ISSUE THREAD

**Issue by Jhsrk** [pagehelper/Mybatis-PageHelper#504]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境
springboot+mybatisplus+shardingjdbc+pagehelper
* PageHelper 版本: 5.1.6
* 数据库类型和版本: mysql 5.7
* JDBC_URL: 

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL
SELECT id, third_order_no, pay_sn, bill_amount, service_fee, bill_time, bill_type, pay_channel_id, pay_type, receipt_company_id, receipt_company_code, merchant_no, rans_summary_bill_id, reconciliation_status, create_time, update_time, yn 
FROM third_bill_detail_2020_4 WHERE yn = 1 AND reconciliation_status = 0 AND rans_summary_bill_id = 16841 
AND bill_time >= '2020-04-09T00:00:00.000+0800' AND bill_time < '2020-04-10T00:00:00.000+0800' LIMIT 1000
```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：
total=1 集合里面不是空而是有一条数据
```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by fangjinuo** [comment]
看看[sqlhelper](https://github.com/fangjinuo/sqlhelper)能否解决你这个问题

**Comment by abel533** [comment]
重复问题。total 是返回行数，返回1行，需要看实际返回的值是不是0.
