### ISSUE TITLE
PageHelper.afterAll()空指针异常

### ISSUE THREAD

**Issue by jameshang** [pagehelper/Mybatis-PageHelper#505]
pagehelper Version 5.1.11

PageHelper.afterAll()方法在多线程时会报空指针异常，原因是private PageAutoDialect autoDialect这个属性对象为null

测试场景：
多线程情况下，针对同一个SqlSession对象实例调用SqlSession.getMapper()方法获取Mapper对象，所有线程获取的是同一个Mapper对象，然后调用Mapper.getXXX()方法获取一条记录，sql语句形式如下：
select * from table_xxx where id=?
这个场景只是根据主键获取一条记录，Mapper.getXXX()返回的是单一的实体对象，没有翻页需求

Page加载方式：
Configuration.addInterceptor(com.github.pagehelper.PageInterceptor)

除了Page加载方式以外，代码中再没有其他任何地方直接或间接引用pagehelper的任何类，Mapper.getXXX()方法的输入参数和返回对象也都与pagehelper的类无关。

**Comment by abel533** [comment]
是否调用了 `setProperties` 方法？

**Comment by abel533** [comment]
@master-hzz 能否提供完整异常堆栈信息？

**Comment by master-hzz** [comment]
@abel533 
![image](https://user-images.githubusercontent.com/16395812/139630443-f025a64c-0db0-4ddf-8da6-711f8b658a0f.png)

**Comment by master-hzz** [comment]
@abel533 版本5.1.8

**Comment by abel533** [comment]
从堆栈看不出任何问题。。

可以先升级到最新版本试试。。如果还有问题，可以给个demo看看。

**Comment by master-hzz** [comment]
> 从堆栈看不出任何问题。。
> 
> 可以先升级到最新版本试试。。如果还有问题，可以给个demo看看。

上面第一行报的npe，但是看代码逻辑应该是不存在这个问题吧，当前issues发起人看也是这个错，我引用的版本里有checkDialectExists这个单例方法，麻烦问下有这种已知的问题吗，对比了下高版本，没发现有针对这个报错太多的改变

**Comment by abel533** [comment]
这个问题通过debug可以轻松找到原因。

在报错这行和下面 new 初始化的地方断点。。看看先进那里。。进来的时候是不是同一个实例。

**Comment by WJah** [comment]
`public void setProperties(Properties properties) {
    this.msCountMap = CacheFactory.createCache(properties.getProperty("msCountCache"), "ms", properties);
    String dialectClass = properties.getProperty("dialect");
    if (StringUtil.isEmpty(dialectClass)) {
      dialectClass = this.default_dialect_class;
    }

    try {
      Class<?> aClass = Class.forName(dialectClass);
      this.dialect = (Dialect)aClass.newInstance();
    } catch (Exception var4) {
      throw new PageException(var4);
    }

    this.dialect.setProperties(properties);  //在代码块2处初始化autoDialect
    String countSuffix = properties.getProperty("countSuffix");
    if (StringUtil.isNotEmpty(countSuffix)) {
      this.countSuffix = countSuffix;
    }

  }

//代码块2
public void setProperties(Properties properties) {
    setStaticProperties(properties);
    this.pageParams = new PageParams();
    this.autoDialect = new PageAutoDialect(); //autoDialect在此初始化
    this.pageParams.setProperties(properties);
    this.autoDialect.setProperties(properties);
    CountSqlParser.addAggregateFunctions(properties.getProperty("aggregateFunctions"));
  }


 private void checkDialectExists() {
    if (this.dialect == null) { //即使this.dialect不为null，autoDialect在多线程情况下有可能还没有初始化
      synchronized(this.default_dialect_class) {
        if (this.dialect == null) {
          this.setProperties(new Properties());
        }
      }
    }

  }


  public void afterAll() {
    AbstractHelperDialect delegate = this.autoDialect.getDelegate(); //当某个线程初始化dialect但是还没初始化autoDialect时，另一个线程有可能先执行到此，造成npe。
    if (delegate != null) {
      delegate.afterAll();
      this.autoDialect.clearDelegate();
    }

    clearPage();
  }
`

**Comment by wenlinzou** [comment]
> ```
>   public void setProperties(Properties properties) {
>     this.msCountMap = CacheFactory.createCache(properties.getProperty("msCountCache"), "ms", properties);
>     String dialectClass = properties.getProperty("dialect");
>     if (StringUtil.isEmpty(dialectClass)) {
>       dialectClass = this.default_dialect_class;
>     }
> 
>     try {
>       Class<?> aClass = Class.forName(dialectClass);
>       this.dialect = (Dialect)aClass.newInstance();
>     } catch (Exception var4) {
>       throw new PageException(var4);
>     }
> 
>     //在代码块2处初始化autoDialect
>     this.dialect.setProperties(properties);  
>     String countSuffix = properties.getProperty("countSuffix");
>     if (StringUtil.isNotEmpty(countSuffix)) {
>       this.countSuffix = countSuffix;
>     }
> 
>   }
> 
>  public void setProperties(Properties properties) { //代码块2
>     setStaticProperties(properties);
>     this.pageParams = new PageParams();
>     this.autoDialect = new PageAutoDialect(); //autoDialect在此初始化
>     this.pageParams.setProperties(properties);
>     this.autoDialect.setProperties(properties);
>     CountSqlParser.addAggregateFunctions(properties.getProperty("aggregateFunctions"));
>   }
> 
> 
>  private void checkDialectExists() {
>     if (this.dialect == null) { //即使this.dialect不为null，autoDialect在多线程情况下有可能还没有初始化
>       synchronized(this.default_dialect_class) {
>         if (this.dialect == null) {
>           this.setProperties(new Properties());
>         }
>       }
>     }
> 
>   }
> 
>   public void afterAll() {
>     //当某个线程初始化dialect但是还没初始化autoDialect时，另一个线程有可能先执行到此，造成npe。
>     AbstractHelperDialect delegate = this.autoDialect.getDelegate(); 
>     if (delegate != null) {
>       delegate.afterAll();
>       this.autoDialect.clearDelegate();
>     }
> 
>     clearPage();
>   }
> ```
> 
> @abel533 autoDialect npe的问题分析见以上代码。只要是初始化的时候遇到多线程就有很大概率出现npe，最近我的项目里经常出现。

有什么解决方法吗？
