### ISSUE TITLE
pageSizeZero 设置无效，无论如何设置或者使用默认值，pageSize = 0就会查全部数据

### ISSUE THREAD

**Issue by 734839030** [pagehelper/Mybatis-PageHelper#506]
按文档说明测试这个参数，发现不符合预期

**Comment by fangjinuo** [comment]
查了代码，这个 pageSizeZero 代码里的注释，和官方文档的说明自身都不一致

看了代码后，其逻辑是这样的，pageSizeZero 不会影响到查询，只会影响 到 结果中的  total 的值而已

**Comment by f981545521** [comment]
确实是这样

**Comment by Nick-The-Uncharted** [comment]
这个问题依旧存在呀。
pageSizeZero：默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
但是如果使用offsetPage(0, 0)。pageNum依旧是0 会有bug。
