### ISSUE TITLE
'ROW_NUMBER' 不是可以识别的 函数名。

### ISSUE THREAD

**Issue by xiuqiang1995** [pagehelper/Mybatis-PageHelper#510]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 'ROW_NUMBER' 不是可以识别的 函数名。
### 使用环境

* PageHelper 版本: 5.1.9
* 数据库类型和版本: sqlserver2000
* JDBC_URL: jdbc:sqlserver://host:1433;DatabaseName=xxx;SelectMethod=cursor

### 完整异常信息
java代码
```
        com.github.pagehelper.PageHelper.startPage(page,limit);
        List<OOXX> OOXX= OOXXMapper.selectByExample(example);
```

```
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 'ROW_NUMBER' 不是可以识别的 函数名。
; uncategorized SQLException for SQL []; SQL state [S00010]; error code [195]; 'ROW_NUMBER' 不是可以识别的 函数名。; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 'ROW_NUMBER' 不是可以识别的 函数名。
```

## 功能建议

是我使用姿势不对么?有老铁是用 sqlserver2000 的么 ？

**Comment by abel533** [comment]
看看选择的方言对不对。

**Comment by zhangfan822** [comment]
我也有这问题，sqlserver2000 没有ROW_NUMBER函数，pagehelper无法使用。
请问如何解决了吗？

**Comment by abel533** [comment]
@zhangfan822 可以自己提供扩展实现。

**Comment by zhangfan822** [comment]
> @zhangfan822 可以自己提供扩展实现。

您好，有相关扩展实现的文档可以学习吗？

**Comment by abel533** [comment]
@zhangfan822 https://github.com/pagehelper/Mybatis-PageHelper/tree/master/src/main/java/com/github/pagehelper/dialect/helper 这个目录下面都是扩展。
