### ISSUE TITLE
目前PageHelper支持delete语句么？试了startPage和offsetPage都不work

### ISSUE THREAD

**Issue by sirs05** [pagehelper/Mybatis-PageHelper#511]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 4.1.0
* 数据库类型和版本: mySql 5.8
* JDBC_URL: useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useSSL=false
          

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.deleteByExample(model);
```

#### 原 SQL

```sql
delete from xxx where xxx = xxx
```

#### 期望的结果：

```sql
delete from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
不支持
