### ISSUE TITLE
Oracle分页效率低下问题

### ISSUE THREAD

**Issue by breakenknife** [pagehelper/Mybatis-PageHelper#514]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

* PageHelper 版本: 5.1.11
* 数据库类型和版本: Orale11G
* JDBC_URL: 

*当前的分页方式为: WHERE ROW_ID <= ? AND ROW_ID > ?
* 经查询分析和执行测试,效率远低于: 
() TMP_PAGE WHERE ROWNUM <= ?  ) WHERE ROW_ID > ?

因此,我暂时放弃了PageHelper.
* 请问一下作者调整的原因是? 如确实有必要能否提供一个配置选项?

**Comment by abel533** [comment]
增加了 Oracle9iDialect 可选，参考: #476
