### ISSUE TITLE
自定义Interceptor处理特殊字符（例如%），结果异常，请问如何处理

### ISSUE THREAD

**Issue by liangli13** [pagehelper/Mybatis-PageHelper#515]
## 异常模板
在处理特殊字符%，自定义Interceptor。

### 使用环境

* PageHelper 版本: 
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper-spring-boot-starter</artifactId>
			<version>1.2.13</version>
* 数据库类型和版本: mysql5.6
* JDBC_URL: xxx

### 完整异常信息
{"result":{"pageCount":1,"total":1,"pageSize":100,"currentPage":1,"list":[]},"code":0,"success":true,"message":"success"}

total已经有值，但是结果没值
请问什么原因

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by fangjinuo** [comment]
看看[sqlhelper](https://github.com/fangjinuo/sqlhelper)能否解决你这个问题
