### ISSUE TITLE
sharding按月分表，PageHepler跨月查询时列表记录数和total不一致

### ISSUE THREAD

**Issue by hexland8** [pagehelper/Mybatis-PageHelper#516]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.10
* 数据库类型和版本: 5.7.25

### SQL 解析错误
使用sharding按月做了分表，假如一个用户在2月和3月分别有一笔资金流水，使用pageHelper跨月group查询用户资金合计时，pagehelper的list中只一条记录，但是total=2，也就是说总记录条数total是两个表的count相加的，望作者关注下这个问题，谢谢！

**Comment by abel533** [comment]
分表就别用分页插件了，只有中间件聚合才有效。
