### ISSUE TITLE
5.1.4的pagehelper的com.github.pagehelper.dialect.helper.OracleDialect类下的public String getPageSql(String sql, Page page, CacheKey pageKey)方法是不是有BUG？

### ISSUE THREAD

**Issue by shiersong** [pagehelper/Mybatis-PageHelper#517]
您好！
我们想请教一下：
我们集成的是：
<dependency>
	<groupId>com.github.pagehelper</groupId>
	<artifactId>pagehelper-spring-boot-starter</artifactId>
	<version>1.2.5</version>
</dependency>
**那么maven会自动下载pagehelper-5.1.4.jar，这个jar包中的com.github.pagehelper.dialect.helper.OracleDialect类下的public String getPageSql(String sql, Page page, CacheKey pageKey)方法逻辑如下：
@Override
    public String getPageSql(String sql, Page page, CacheKey pageKey) {
        StringBuilder sqlBuilder = new StringBuilder(sql.length() + 120);
        sqlBuilder.append("SELECT * FROM ( ");
        sqlBuilder.append(" SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( ");
        sqlBuilder.append(sql);
        sqlBuilder.append(" ) TMP_PAGE WHERE ROWNUM <= ? ");
        sqlBuilder.append(" ) WHERE ROW_ID > ? ");
        return sqlBuilder.toString();
    }
在66行-75行之间。
这个方法是用来针对Oracle数据库生成具体的分页SQL的。
这个方法是不是有BUG？
因为我们发现在使用Oracle的实际业务程序中如果使用了ORDER BY字句，并且在分页边界处有多条记录的ORDER BY的字段的值是相同的时候，有的记录在每一页的结果集中都找不到，就是说这种情况下记录有一定几率的丢失。**

我打个比方：
每页记录数是10，原业务程序的SQL ORDER BY a，按照原业务程序的SQL查询出来的不分页的结果集中第9条、第10条、第11条的的a字段的值都是1，在实际应用的情况是有一定记录会发生这样的情况：
第10条记录在第一页的结果集中没有，在第二页的结果集中也没有。

**个人建议是：
在以后的版本中是不是应该将那个方法改成这样？
@Override
public String getPageSql(String sql, Page page, CacheKey pageKey) {
        StringBuilder sqlBuilder = new StringBuilder(sql.length() + 120);
        sqlBuilder.append("SELECT * FROM ( ");
        sqlBuilder.append(" SELECT TMP_PAGE.*, ROWNUM rownum_ FROM ( ");
        sqlBuilder.append(sql);
        sqlBuilder.append(" ) TMP_PAGE ");
        sqlBuilder.append(" ) WHERE rownum_ > ? AND rownum_ <= ? ");
        return sqlBuilder.toString();
    }**
即在第一次子查询的时候只给原业务SQL的结果集的每一行的ROWNUM起一个别名（rownum_），而不对ROWNUM限制条件了，在第二次子查询针对这个别名（rownum_），也就是行号，限制上分页边界条件。

**而对于我们现有项目的情况，是否可以这样解决实际问题？
1、写一个自定义的Dialect类，继承OracleDialect，并重写public String getPageSql(String sql, Page page, CacheKey pageKey) 方法，
2、并在配置文件中配置pagehelper:dialectAlias:oracle=自定义的Dialect类（基于yml文件方式的配置）**

**Comment by 18629434073** [comment]
这种情况在你order by 后面再加一个唯一的排序字段就行了，这种应该属于代码本身的写法问题，而不是插件问题，所以不应该依赖插件解决

**Comment by shiersong** [comment]
那样也可以。

**Comment by shiersong** [comment]
不好意思，还得请教一下：
刚才我又看了一下你们的pageHelper最新版的程序，最新版是5.1.11已经将那个地方改了，而且改后的逻辑和我说的一样，只不过我的comment中的sql对于行号使用的别名是rownum_，而你们最新版的5.1.11的pageHelper对应的程序中所使用的别名是ROW_ID。
5.1.11版的对应程序的截图如下：
![最新版OracleDialect](https://user-images.githubusercontent.com/25313479/81790138-8e380f80-9537-11ea-948f-8b6b025b2429.png)

**那是不是说
一、我直接用5.1.11版的pageHelper就可以了？我们现在用的是5.1.4版本的。
二、或者是说按照我的comment中提到的：
1、写一个自定义的Dialect类，继承OracleDialect，并重写public String getPageSql(String sql, Page page, CacheKey pageKey) 方法，
2、并在配置文件中配置pagehelper:dialectAlias:oracle=自定义的Dialect类（基于yml文件方式的配置）**

**此致：
         敬礼！**

**Comment by shiersong** [comment]
Sorry；附件打不开：
最新版5.1.11的OracleDialect.java的相关程序如下：
@Override
    public String getPageSql(String sql, Page page, CacheKey pageKey) {
        StringBuilder sqlBuilder = new StringBuilder(sql.length() + 120);
        sqlBuilder.append("SELECT * FROM ( ");
        sqlBuilder.append(" SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( ");
        sqlBuilder.append(sql);
        sqlBuilder.append(" ) TMP_PAGE)");
        sqlBuilder.append(" WHERE ROW_ID <= ? AND ROW_ID > ?");
        return sqlBuilder.toString();
    }

**Comment by abel533** [comment]
更新的两种方式都提供了。。。Oracle9iDialect 是另一种。
