### ISSUE TITLE
count还是使用子查询方式查询,sql并没有聚合函数和group by,怀疑是like原因

### ISSUE THREAD

**Issue by JavaEdison** [pagehelper/Mybatis-PageHelper#519]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本:5.1.9
* 数据库类型和版本: mysql,8.0.11
* JDBC_URL: jdbc:mysql://xxxxxx:3306/xxxx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&rewriteBatchedStatments=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select count(0) from (select        xx,xx,xx         from xx1 left join xx2 on xx1.id=xx2.user_id         where 1=1                                 and xx1.`name` like "%"?"%"                                                 and  xx1.status = 1 and (xx2.`type` = 1)         order by xx1.number asc) tmp_count

```

#### 期望的结果：

```sql
select        count(0)         from xx1 left join xx2 on xx1.id=xx2.user_id         where 1=1                                 and xx1.`name` like "%"?"%"                                                 and  xx1.status = 1 and (xx2.`type` = 1)  tmp_count

```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议
项目是基于sharding-jdbc做的分表，并不支持这个样的方式Cannot support multiple schemas in one SQL，建议不走子查询去掉order by 
详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
jsqlparser 升级到了 3.2 版本。

原sql修改：
```sql
select xx,xx,xx from xx1 left join xx2 on xx1.id=xx2.user_id where 1=1 and xx1.`name` like "%ll%" and  xx1.status = 1 and (xx2.`type` = 1) order by xx1.number asc
```

countsql：
```sql
SELECT count(0) FROM xx1 LEFT JOIN xx2 ON xx1.id = xx2.user_id WHERE 1 = 1 AND xx1.`name` LIKE "%ll%" AND xx1.status = 1 AND (xx2.`type` = 1)
```

区别在 like 后面的双引号。。你提供的例子会解析失败，失败后会直接套一层。
