### ISSUE TITLE
DB2分页时必须要指定子查询的别名,不然会发生异常

### ISSUE THREAD

**Issue by hejinguo** [pagehelper/Mybatis-PageHelper#52]
![1](https://cloud.githubusercontent.com/assets/19966301/25885495/3e4bc160-358b-11e7-8ca1-005c348ee765.png)

## # _**如图所示，目前我是克隆项目程序在本地添加别名后能正常使用，烦请下个版本修复此问题，谢谢。**_

**Comment by abel533** [comment]
今天会发布一个5.0.2-beta版本，如果方便可以帮忙测试这个版本。

**Comment by hejinguo** [comment]
@abel533 刚刚使用5.0.2-beta版本测试，问题已经修复，谢谢啦。
