### ISSUE TITLE
4.x版本在一个方法里有多个长sql时很慢

### ISSUE THREAD

**Issue by tangfanggang** [pagehelper/Mybatis-PageHelper#522]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
我用pagehelper的4.2.1，调用一个方法（此方法里面有两个比较长的sql，但是数据量很小）需要45秒（在第二个sql处卡45秒），换个版本，用5.1.11只需要85毫秒，是什么原因？这个sql虽然长，但是直接执行只要20毫秒，而且数据量也很小。4.x版本有bug吗？

**Comment by abel533** [comment]
优化的最终SQL不一样。推荐用最新版本。
