### ISSUE TITLE
批量分页查询中执行update操作导致数据缺失

### ISSUE THREAD

**Issue by Datartvinci** [pagehelper/Mybatis-PageHelper#53]
在一个循环中，从第一页查询到最后一页，在这个过程中，将查询出来的结果执行update操作，导致分页查询的记录数不准确。如果不执行update操作，就能准确查出所有记录，请问这种情况只能手动写分页了吗？

**Comment by IrvingZhao** [comment]
我觉得你这个跟用什么工具没关系了，你这样肯定会出问题的，因为你更新了排序字段，导致数据排序顺序变更，肯定会影响分页结果，你可以把排序字段换成你这次更新不会修改的字段，比如说ID

**Comment by abel533** [comment]
楼上说的对，如果不能固定排序，你手写分页也是错的！
