### ISSUE TITLE
page对象int类型值太小了，数据量大的情况存储不下，是否考虑使用long类型

### ISSUE THREAD

**Issue by fallsea** [pagehelper/Mybatis-PageHelper#530]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 涉及属性

```java
/**
     * 页码，从1开始
     */
    private int pageNum;
    /**
     * 起始行
     */
    private int startRow;
    /**
     * 末行
     */
    private int endRow;
    /**
     * 总数
     */
    private long total;
    /**
     * 总页数
     */
    private int pages;
```

**Comment by llsi4275** [comment]
是的，至少startRowl,endRow,total这3个参数应该使用long。
calculateStartAndEndRow方法计算出来的值可能是负数。

**Comment by llsi4275** [comment]
Caused by: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-20, 10' at line 1

**Comment by llsi4275** [comment]
@abel533

**Comment by fallsea** [comment]
@abel533 总页数`pages`，页码`pageNum`也会超出int最大限制

**Comment by fallsea** [comment]
@abel533 主要是有些非关系数据库（数据库很大），也可以使用插件分页，

**Comment by abel533** [comment]
@fallsea 目前改动的两个值不会影响任何使用的地方。。如果修改 pages 和 pageNum，会有很多不兼容的情况出现。

**Comment by llsi4275** [comment]
> @fallsea 目前改动的两个值不会影响任何使用的地方。。如果修改 pages 和 pageNum，会有很多不兼容的情况出现。

@abel533 可否考虑使用重构方法的形式来解决，内部处理；把int方法标识过时？
