### ISSUE TITLE
使用自定义_COUNT查询，同一个mapper下，我一个查询使用了自定义COUNT，另一个没有使用自定义_COUNT。没有使用的查询会卡在查询的sql好久，很慢

### ISSUE THREAD

**Issue by zhangtongxing** [pagehelper/Mybatis-PageHelper#531]
### 使用环境

* PageHelper 版本: 5.1.11
* 数据库类型和版本: mysql 5.6

#### 分页参数
java
PageHelper.startPage(orderCharge.getPageNum(),orderCharge.getPageSize());
List<OrderCharge> list = balanceAccountMapper.selectPayCostList(orderCharge);
这个是使用了自定义COUNT

PageHelper.startPage(orderCharge.getPageNum(),orderCharge.getPageSize());
 List<OrderCharge> list = balanceAccountMapper.selectReceivableCostList(orderCharge);
这个是没有使用自定义COUNT   查询就很慢  把这个加上自定义COUNT查询之后就很快了
```
这两个查询的接口跟xml sql都在同一个文件
啥原因导致了 只要在同一个namespace下 必须都要使用自定义count的查询 否则就会很慢

**Comment by abel533** [comment]
慢的原因应该是自动生成的count sql慢。。手写的能优化到最好。

**Comment by zhangtongxing** [comment]
不是啊，没有使用自定义分页的时候非常快的，加完一个之后另一个变得非常慢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pagehelper/Mybatis-PageHelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 晚上10:52
收件人:&nbsp;"pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com&gt;;
抄送:&nbsp;"张同兴"<642023763@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pagehelper/Mybatis-PageHelper] 使用自定义_COUNT查询，同一个mapper下，我一个查询使用了自定义COUNT，另一个没有使用自定义_COUNT。没有使用的查询会卡在查询的sql好久，很慢 (#531)





 
慢的原因应该是自动生成的count sql慢。。手写的能优化到最好。

**Comment by abel533** [comment]
现在直接执行countsql慢吗？

**Comment by zhangtongxing** [comment]
直接执行是不慢的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pagehelper/Mybatis-PageHelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上9:20
收件人:&nbsp;"pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com&gt;;
抄送:&nbsp;"张同兴"<642023763@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pagehelper/Mybatis-PageHelper] 使用自定义_COUNT查询，同一个mapper下，我一个查询使用了自定义COUNT，另一个没有使用自定义_COUNT。没有使用的查询会卡在查询的sql好久，很慢 (#531)





 
现在直接执行countsql慢吗？

**Comment by zhangtongxing** [comment]
还是慢，除非我都改成自定义查询count




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liuzh"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上9:20
收件人: "pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com&gt;; 
抄送: "张同兴"<642023763@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pagehelper/Mybatis-PageHelper] 使用自定义_COUNT查询，同一个mapper下，我一个查询使用了自定义COUNT，另一个没有使用自定义_COUNT。没有使用的查询会卡在查询的sql好久，很慢 (#531)





 
现在直接执行countsql慢吗？

**Comment by abel533** [comment]
打开详细日志，看看是count慢，还是java代码慢。

**Comment by zhangtongxing** [comment]
详细信息都看了，就是mybatis拼接count sql的时候特别慢，不过源码我没有跟，拼接完之后立马就查询出来了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liuzh"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 晚上10:17
收件人: "pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com&gt;; 
抄送: "张同兴"<642023763@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pagehelper/Mybatis-PageHelper] 使用自定义_COUNT查询，同一个mapper下，我一个查询使用了自定义COUNT，另一个没有使用自定义_COUNT。没有使用的查询会卡在查询的sql好久，很慢 (#531)





 
打开详细日志，看看是count慢，还是java代码慢。
