### ISSUE TITLE
RowBounds分页结果不准确

### ISSUE THREAD

**Issue by gitYupan** [pagehelper/Mybatis-PageHelper#534]
数据库总条数8条，new RowBounds(7,2)；预期结果为第8条数据；实际结果一条数据没有

分析源码发现，RowBounds转pageNum为：

this.pageNum = rowBounds[1] != 0 ? (int) (Math.ceil(((double) rowBounds[0] + rowBounds[1]) / rowBounds[1])) : 0;

将pageNum转为了5

### 使用环境
* PageHelper 版本: 5.1.9
* 数据库类型和版本: oracle

**Comment by abel533** [comment]
0,1 | 2,3 | 4,5 | 6,7 | 8,9 | 10,11
-- | -- | -- | -- | -- | -- 


offset 是包含的，7，2意味着要包含7的那一页。。从上面表格来看应该是第4页，这里返回5确实有问题。。

第4页的情况下，返回的是6，7。也不是这里说的8。

因此这里从 ceil 改为 floor：

```java
this.pageNum = rowBounds[1] != 0 ? (int) (Math.floor(((double) rowBounds[0] + rowBounds[1]) / rowBounds[1])) : 0;
```

**Comment by abel533** [comment]
上面逻辑说错了。

0|1,2 | 3,4 | 5,6 | 7,8 | 9 ,10
-- | -- | -- | -- | -- | -- 

原来的逻辑是没有问题的。

**Comment by abel533** [comment]
再次发现问题。。offset7时，下一个确实是8.。和 #423 一样。

已经处理，能够按照预想的结果返回。
