### ISSUE TITLE
系统集成 ShardingSphere  分页不起作用

### ISSUE THREAD

**Issue by Codefans-fan** [pagehelper/Mybatis-PageHelper#535]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.11
* 数据库类型和版本: mysql
<shardingsphere.version>4.1.1</shardingsphere.version>

#### 分页参数

```java
PageHelper.startPage(pageNum, pageSize, false);
		return productMapper.selectByExample(example);
```

日志 sql
 from product
     
       
     WHERE (  delete_status = ?
                
            
              
                  and publish_status = ?
                
            
              
                  and verify_status = ?
                
            
              
                  and group_purchase_type_id = ? )
没有进行分页查询

**Comment by abel533** [comment]
可以断点看看shardingsphere是否有特殊处理。

**Comment by shanjl** [comment]
用RowBounds试试，我的可以，shardingsphere版本:4.0.1,PageHelper 版本: 5.1.10
