### ISSUE TITLE
现在还不支持 clickhouse 数据库，可否加人对clickhouse的支持，自己修改了源码，使用mysql的方言是可以正常使用，但是自动化部署是个问题，需要安装到指定的maven仓库

### ISSUE THREAD

**Issue by mg166** [pagehelper/Mybatis-PageHelper#536]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
参照这里配置即可：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#513---2018-04-07

能否提供 clickhouse 的 jdbcurl 示例？

**Comment by mg166** [comment]
@abel533 谢谢，参照提供的示例又去读了源码，已解决，配置方法如下：
    @Bean
    public PageHelper pageHelper(){
        PageHelper pageHelper = new PageHelper();
        Properties properties = new Properties();
        properties.setProperty("offsetAsPageNum","true");
        properties.setProperty("rowBoundsWithCount","true");
        properties.setProperty("reasonable","true");
        **properties.setProperty("helperDialect","clickhouse");
        properties.setProperty("dialectAlias","clickhouse=com.github.pagehelper.dialect.helper.MySqlDialect");**
        pageHelper.setProperties(properties);
        return pageHelper;

    }

**Comment by abel533** [comment]
这周计划发布5.2.0，自带上面的关系。
