### ISSUE TITLE
责任链模式下PageInterceptor执行完intercept方法后直接返回而不触发下一个拦截器的调用是否会有问题？

### ISSUE THREAD

**Issue by sswwtao** [pagehelper/Mybatis-PageHelper#539]
责任链模式下PageInterceptor执行完intercept方法后直接返回而不触发下一个拦截器的调用是否会有问题？

**Comment by abel533** [comment]
有问题，这里有详细介绍：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md

简单说就是会跳过 4 个参数的方法。。6个参数的方法会继续链的调用。

**Comment by abel533** [comment]
结合分页插件使用拦截器时，可以参考最简单的 https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/BoundSqlInterceptor.java

最新 5.2.0 版本的更新日志有介绍。
