### ISSUE TITLE
mybaties-查询语句优化

### ISSUE THREAD

**Issue by tuyawen** [pagehelper/Mybatis-PageHelper#540]
![image](https://user-images.githubusercontent.com/60734665/89607149-66d9b000-d8a4-11ea-847b-c4f8aff37683.png)
如图：图片的右下角能够看到总条数，但是不能单独获取到这多条数据中某一个字段的`最大值`，`最小值`和`求和`。因为业务需要，希望能够在分页插件中，不仅仅能计算总条数，也能计算这N条数据中的某个字段的最大值，最小值，求和。
目前在分页查询的时候可以看到有n条数据，但是不知道这些数据的金额总和(n条数据的金额总各)，如果能看到是不是方便一点。
如图是没月金额总和的
产品浏览地址
##### 需求
**做为一个商城后台的用户，如果能看到查询条件对应的金额总和那么就方便很多了，对信息掌握更加全面。**

where:建议每个分页组件都加一个sum min max等功能，如果情况允许的话。

自己对mybaties分页插件SQL查询语句的优化
1. 原语句
```
select count(1) from (select a from table where a==1)
```
2. 新语句
```
select count(1) as count, min(a) as min,max(a) as max sum(a) as sum from (select a from table where a==1)
```
3. 进阶语句
```
select count(1) as count, min(a1) as min1,max(a1) as max1 sum(a1) as sum1 from (select a from table where a==1)
```
**当前使用的mybaties插件：**
```
<groupId>com.github.pagehelper</groupId>  
       <artifactId>pagehelper</artifactId>  
       <version>4.1.6</version>  
</dependency>  
```
#### 问题解决的要求：
1. 提供一个demo完成在求总条数的时候同时够计算某个字段的最大值最小值，求和等操作
1. 修改过后对性能的影响有多大（整体耗时不大于25%可以接受）
1. 如果min和sum是否支持多个
1. 支持多个的话是否会影响性能

**Comment by abel533** [comment]
你提的已经不只是分页了，不会做分页之外的事。

**Comment by tuyawen** [comment]
我只是想 有这样一个demo就好了
