### ISSUE TITLE
pagehelper offset相关问题

### ISSUE THREAD

**Issue by kangyu06** [pagehelper/Mybatis-PageHelper#541]
我想要打印出来的sql是  select * from table limit pageSize offset pageNum 这种，支持吗？

**Comment by abel533** [comment]
支持，hsqldb 就是这种：https://github.com/pagehelper/Mybatis-PageHelper/blob/ed5549c2adf23c34972f42e0109d06200d9440a9/src/main/java/com/github/pagehelper/dialect/helper/HsqldbDialect.java#L72
