### ISSUE TITLE
sql 自动增加order by 字段

### ISSUE THREAD

**Issue by DearBo7** [pagehelper/Mybatis-PageHelper#542]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.1,5.2.0
* 数据库类型和版本: mysql 5.7

#### 分页参数

```java
int pageIndex = 1;
int pageSize = 20;
Map<String, Object> mapValue = new HashMap<>(6);
mapValue.put("orderBy", "Id Desc");
mapValue.put("pageIndex", ((pageIndex - 1) * pageSize));
mapValue.put("pageSize", pageSize);
```

#### 原 SQL

```sql
//获取总行数
select COUNT(0) from aaa  WHERE DeleteFlag = 0

//获取数据
SELECT * FROM  aaa 
        <if test="orderBy != null">
            ORDER BY ${orderBy}
        </if>
        <if test="pageIndex !=null and pageSize != null">
            LIMIT #{pageIndex},#{pageSize}
        </if>
```

### 完整异常信息(解析sql异常)

```
//获取总行数
select COUNT(0) from aaa  WHERE DeleteFlag = 0 Order By Id Desc;
//获取数据
SELECT * FROM  aaa  temp Limit 0,20 Order By Id Desc;
```

使用Map传递参数,排序字段变量orderBy,获取总行数原sql里面没有写order by 信息，解析后自动增加；
获取数据sql，order by信息解析到 limit 后面去了;
不使用orderBy 这个字段传递正常；

**Comment by abel533** [comment]
看文档：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
>params：为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
