### ISSUE TITLE
神通V7.0 分页bug

### ISSUE THREAD

**Issue by miniministar** [pagehelper/Mybatis-PageHelper#543]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.2.0
* 数据库类型和版本: 神通V7.0
* JDBC_URL: xxx

### SQL 解析错误
错误描述：parser: syntax error at or near "," at character 41
#### 分页参数

```java
PageHelper.startPage(10, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from test.user limit 10 , 10;
```

#### 期望的结果：

```sql
select * from test.user limit 10 offset 10;
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
新版本已经使用 offset
