### ISSUE TITLE
一个不算问题的问题，在 select * from aaa /*! xxx */ 这种情况下，生成的 count 语句会把/*! xxx */ 给过滤掉

### ISSUE THREAD

**Issue by tanhao-github** [pagehelper/Mybatis-PageHelper#546]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.11
* 数据库类型和版本: MySQL 5.5x

#### 原 SQL

```sql
 select * from aaa /*! xxx */ 
```

#### 期望的结果：

```sql
 select count(0) from aaa /*! xxx */ 
```

## 功能建议

希望可以保留特有的注释，在一些场景下后面的注释有特殊作用

**Comment by abel533** [comment]
目前没有针对性的方式，在SQL中出现注释 `/*keep orderby*/` 时不会解析SQL，可以尽可能保留原样。
