### ISSUE TITLE
mysql 方言 SQL_CALC_FOUND_ROWS,found_rows 的分页可以考虑支持吗

### ISSUE THREAD

**Issue by weisanju** [pagehelper/Mybatis-PageHelper#549]
## 功能建议
mysql 方言 SQL_CALC_FOUND_ROWS,found_rows 的分页可以考虑支持吗

**Comment by pagehelper** [comment]
该功能在mysql 8中已弃用，不考虑支持。

参考：https://dev.mysql.com/worklog/task/?id=12615#:~:text=MySQL%20has%20a%20nonstandard%20query%20modifier%20called%20SQL_CALC_FOUND_ROWS.,store%20that%20for%20later%20retrieval%20in%20FOUND_ROWS%20%28%29.
