### ISSUE TITLE
根据时间排序，分页数据有重复

### ISSUE THREAD

**Issue by cenxi** [pagehelper/Mybatis-PageHelper#554]
### 使用环境

* PageHelper 版本: 5.1.11
* 数据库类型和版本: postgres
* JDBC_URL: xxx

sql根据时间排序，使用pageHelper分页，出现部分数据重复。
用根据时间排序的sql在postgres查询，它的序列是固定的，不知道为什么用pageHelper后，会出现数据重复

**Comment by Cyuchuan** [comment]
如果是流水表，时间会大概率生成相同，每次分页查到的数据是可能一样的

**Comment by cenxi** [comment]
是的，就是同一时间产生大批相同数据。但是用sql直接查数据库(也是按时间排序)，每次查询，相同时间的数据返回的次序总是一样的，不知道为啥PageHelper分布，它的次序会打乱，从而导致这个问题出现

**Comment by abel533** [comment]
最新版本试试，有新的postgres实现。
