### ISSUE TITLE
升级到5.2.0版本之后，mapper查询返回空结果

### ISSUE THREAD

**Issue by cxfly** [pagehelper/Mybatis-PageHelper#556]
升级到5.2.0版本之后，之前的查询代码都查不到数据了，跟踪了下代码，发现是5.2.0之后改了com.github.pagehelper.dialect.AbstractHelperDialect.afterCount(long, Object, RowBounds)这个方法中的第95行代码：
之前版本为：  return count > 0;
5.2.0改成了 ： return count > ((page.getPageNum() - 1) * page.getPageSize());

之前的逻辑是有总记录数大于0时，继续分页查询， 现在呢，是判断了总记录数是否大于当前查询页的偏移量，结果返回false
而上层调用的地方判断逻辑：
                   //处理查询总数，返回 true 时继续分页查询，false 时直接返回
                    if (!dialect.afterCount(count, parameter, rowBounds)) {
                        //当查询总数为 0 时，直接返回空的结果
                        return dialect.afterPage(new ArrayList(), parameter, rowBounds);
                    }

结果就返回空结果了。
测试代码：  testMapper.selectByParam(param, new RowBounds(0, 0)) 在5.2.0之前是可以返回数据的。

希望能修复下，保持跟之前版本兼容， 谢谢！

**Comment by mathcoder23** [comment]
5.1.11 95行 ` return count > ((page.getPageNum() - 1) * page.getPageSize());`
5.2.0 105行 `page.getPageNum() > 0 && count > page.getStartRow()`

不同版本判断是这样的。5.2.0版本对参数检查更加严格了。我遇到的问题就是pageNum为0，在5.1.11能查，5.2.0不能查，因为pageNum是从1开始的。

**Comment by abel533** [comment]
原来是bug。。解决之后才是对的逻辑。

**Comment by a1156698162** [comment]
有什么推荐的修改方法吗？
