### ISSUE TITLE
PageInfo判断是否是第一页和最后一页的方法是不是有问题啊

### ISSUE THREAD

**Issue by caochenlei** [pagehelper/Mybatis-PageHelper#559]
pageInfo.isIsFirstPage()
pageInfo.isIsLastPage()
两个is是不是重复了

**Comment by leowy** [comment]
这个应该不算重复吧，参数名是isFirstPage和isLastPage，对应getter会加上is。只是看起来比较别扭，好像阿里巴巴开发手册上是不推荐这么用，但是一般来说大佬都有自己的一套编码规范。

**Comment by CaoChenLei** [comment]
好像是的，确实太别扭了，还不兼容，你那个开发文档都没更新，我觉得还是去掉的好，不过你是大佬，跟着你混哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Leowy Zhuang"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 下午5:53
收件人: "pagehelper/Mybatis-PageHelper"<Mybatis-PageHelper@noreply.github.com&gt;; 
抄送: "轻松的小希"<774908833@QQ.COM&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pagehelper/Mybatis-PageHelper] PageInfo判断是否是第一页和最后一页的方法是不是有问题啊 (#559)





 
这个应该不算重复吧，参数名是isFirstPage和isLastPage，对应getter会加上is。只是看起来比较别扭，好像阿里巴巴开发手册上是不推荐这么用，但是一般来说大佬都有自己的一套编码规范。
