### ISSUE TITLE
不使用插件的时候sql语句可以正常运行

### ISSUE THREAD

**Issue by Chenshengshu** [pagehelper/Mybatis-PageHelper#561]
### 问题描述

不使用插件的时候可以执行，使用插件会产生错误
#### 错误提示
ERROR jdbc.sqltiming Line:130 - 3. PreparedStatement.setInt(1, 10)
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='Second_PageHelper', mode=IN, javaType=class java.lang.Integer, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

* PageHelper 版本: 1.2.5
* 数据库类型和版本: mysql 5.8

#### 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

详细说明，尽可能提供(伪)代码示例。

**Comment by lexiaobei** [comment]
你好，我也遇到了这个问题，请问怎么解决的？

**Comment by Chenshengshu** [comment]
> 你好，我也遇到了这个问题，请问怎么解决的？
好像是因为xml中配置的问题，你有可以复现的案例吗？

**Comment by lexiaobei** [comment]
> > 你好，我也遇到了这个问题，请问怎么解决的？
> > 好像是因为xml中配置的问题，你有可以复现的案例吗？

我解决了，是PageHelper.orderBy("");忘记设置默认参数了。。。

**Comment by andotorg** [comment]
xml sql中也不可以设置 -- 注释，去掉解决了该问题
