### ISSUE TITLE
[功能建议]-允许自定义的分页sql查询语句

### ISSUE THREAD

**Issue by 2374637379** [pagehelper/Mybatis-PageHelper#563]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议
在一般情况下，PageHelper是可以直接使用的，不用开发者多做额外的工作。

但是有时候，开发者需要自己控制分页查询语句，根据情况来优化查询语句。这个时候，就只能完全放弃PageHelper了，感觉有点可惜。所以希望PageHelper能给予开发者这个能力，让其自己实现分页的逻辑，PageHelper不处理sql代码，只需要准备offset、limit对应的参数值即可。

具体实现也不复杂，有两种实现思路。
1、设置一个标志位，根据这个标志位来判断是否要自动处理原始sql来实现分页，开发者可以视情况来关闭自动处理的过程，从而实现优化查询的目的。
2、PageHelper自动检测sql原始代码，若在代码中发现了分页相关的关键字或者其它，那么可判定为开发者自己实现了分页逻辑，不处理这段sql，这样也可以实现查询优化的目的。

在这种情况下，PageHelper只需要计算好offset，limit，然后将值代入到sql中。当然，这就需要提前定义好对应的参数名，这样开者可以在sql代码中使用它，比如${offset}，${limit}这样的参数名。

#### 现在的 SQL

```sql
-- 针对有些复杂的sql，希望可以由程序员自定义limit出现在sql代码中的位置
-- 这种情况下，不处理sql代码内容，直接传分页参数即可，可以提前约定好默认的分页参数
SELECT
 oor.*, oi.xxx
FROM
order_relation_record oor
LEFT JOIN order_info oi ON orr.orderId = oi.orderid
AND oi.deleteflag = 0
WHERE
.....
LIMIT ${offset}，${limit}
```

#### 期望的结果：

```sql
SELECT
 oor.*, oi.xxx
FROM
	(
		SELECT orderId FROM order_relation_record orr
		WHERE 
			......
		 ORDER BY
			 orr.updatetime DESC 
		LIMIT ${offset}，${limit}	-- 此时希望limit出现在这里，offset,limit参数值由PageHelper自动提供
	) orr2 
	INNER JOIN order_relation_record orr ON orr2.orderId = orr.orderId
	
LEFT JOIN order_info oi ON orr.orderId = oi.orderid
AND oi.deleteflag = 0
-- sql最后面不追加limit
```

**Comment by fangdengfu** [comment]
面对这种情况，我一般将代码拆分一下：
1、先查询orr2,
2、根据关联关系关联出另外2个join的数据
3、数据整理，关联

以上尽量用java代码操作

**Comment by Bean-yang** [comment]
能自己解决优先自己解决，赞成二楼的做法
