### ISSUE TITLE
PostgreSQL下ERROR: LIMIT #,# syntax is not supported

### ISSUE THREAD

**Issue by WhaleFall22** [pagehelper/Mybatis-PageHelper#564]
### 使用环境
* PageHelper 版本: 1.2.13
* PostgreSQL: 42.2.14
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

### 完整异常信息

```
Cause: org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
```
### 说明
我的项目中存在 Mysql和PostgreSQL，如果PostgreSQL的查询语句使用startPage就会存在`ERROR: LIMIT #,# syntax is not supported`的问题，请问是应该指定`offsetPage()`还是配置`autoRuntimeDialect `为`true`

**Comment by abel533** [comment]
已经有人PR了postgresql的实现，最新版本会有。
