### ISSUE TITLE
有空指针异常

### ISSUE THREAD

**Issue by javamanlxf** [pagehelper/Mybatis-PageHelper#565]
https://github.com/pagehelper/Mybatis-PageHelper/blob/ed5549c2adf23c34972f42e0109d06200d9440a9/src/main/java/com/github/pagehelper/PageSerializable.java#L48

**Comment by abel533** [comment]
list不能为空，能否提供完整异常堆栈信息？如果是分页插件内部使用出现NPE就是BUG。
