### ISSUE TITLE
[功能建议] PageInfo返回的字段太多，有没有优雅的裁剪方案。

### ISSUE THREAD

**Issue by uniquejava** [pagehelper/Mybatis-PageHelper#566]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议

怎么方便的裁剪PageInfo中的字段。 

或者我想把大部分不用的字段从swagger或spring的响应中去掉。

我自定义了PageInfo的子类， 加了 `@ApiIgnore` 和 `@JsonIgnore` 都不好用， 我好想直接修改PageInfo类， 加上这两个注解啊。

能不能直接在 `application.yaml` 中配置不想返回的字段， 谢谢！

难道你们不想让返回的结果看起来更清爽一点?  快要疯了我， 求提供较为干净的解决方案。 谢谢！

以下我试图屏蔽 `end_row`， 失败了， 我心有不甘。

```java
public class PageResult<T> extends PageInfo<T> {
    public PageResult() {
    }

    public PageResult(List<T> list) {
        super(list);
    }

    @Override
    @JsonIgnore
    @ApiIgnore
    public int getEndRow() {
        return super.getEndRow();
    }
}
```

**Comment by liwei2015cd** [comment]
直接使用page对象就可以了吧，现在都是前后端分离，这对象中的字段完全够用了。

**Comment by abel533** [comment]
我很多次都推荐自己封装Page，`PageInfo` 是一个不得已提供的示例。

**Comment by uniquejava** [comment]
> 我很多次都推荐自己封装Page，`PageInfo` 是一个不得已提供的示例。

我发现使用PageSerializable这个类就可以。。。之前没认真看代码。 自己封装以后再说，我懒
