### ISSUE TITLE
pageHelper能否在分页执行前，动态设置helperDialect

### ISSUE THREAD

**Issue by StarSky1** [pagehelper/Mybatis-PageHelper#569]
能不能像pageHelper.startPage方法一样,setHelperDialect，实现aop切换多数据源时，可以动态切换分页语句的方言

**Comment by abel533** [comment]
目前能自动识别，后续会增加调用时指定数据库类型。

**Comment by StarSky1** [comment]
好的，谢谢！

**Comment by hejinguo** [comment]
请问多久能支持呢

**Comment by hejinguo** [comment]
请问是否可以先提供下思路,我们先自行修改也好。

**Comment by abel533** [comment]
## 使用方法

增加下面的设置方式：
```java
//可以指定别名
PageHelper.startPage(1, 10).using("oracle");
List<User> list = userMapper.selectAll();

//可以直接指定类名
PageHelper.startPage(2, 10).using("org.exmaple.CustomDialect");
list = userMapper.selectAll();
```

## 为什么没有给 startPage 方法增加参数？

已经加不过来了。。第三个参数有 `orderBy`，如果为了这个增加个枚举就会对自定义实现不够友好。

## 使用建议

建议自己封装，例如 `MyPageHelper.mysql(start,page,...)`
