### ISSUE TITLE
比较复杂的SQL查询自己写了分页和统计,有没有办法封装到PageInfo保证返回统一呢、

### ISSUE THREAD

**Issue by hejinguo** [pagehelper/Mybatis-PageHelper#57]
![image](https://cloud.githubusercontent.com/assets/19966301/26336641/3c3c69d6-3fa6-11e7-86fd-e763537ba1c5.png)

**Comment by abel533** [comment]
建议用自己的PageInfo类，自己实现更符合实际需要。
