### ISSUE TITLE
最后一页的数据。

### ISSUE THREAD

**Issue by wengyanbin** [pagehelper/Mybatis-PageHelper#575]
我使用PageHelper分页的时候，当请求的页数超过总页数的时候，返回最后一页数据。
目标是希望超过总页数时返回空数据。

**Comment by wengyanbin** [comment]
版本是5.1.4

**Comment by wengyanbin** [comment]
public void setTotal(long total) {
        this.total = total;
        if (total == -1) {
            pages = 1;
            return;
        }
        if (pageSize > 0) {
            pages = (int) (total / pageSize + ((total % pageSize == 0) ? 0 : 1));
        } else {
            pages = 0;
        }
        //分页合理化，针对不合理的页码自动处理
        if ((reasonable != null && reasonable) && pageNum > pages) {
            if (pages != 0) {
                pageNum = pages;
            }
            calculateStartAndEndRow();
        }
    }
这里对分页合理化处理的时候，当请求的页数超过分页的最大数时，会将请求的页数设置为最大分页数。这导致请求的页数超过总页数的时候，返回最后一页数据。一般这种情况，期望返回的数据应该是返回空数组。

**Comment by boyonger** [comment]
哎 真的是画蛇添足

**Comment by boyonger** [comment]
你不要传入reasonable不就好了
