### ISSUE TITLE
自定义分表拦截器失效问题

### ISSUE THREAD

**Issue by vancefantasy** [pagehelper/Mybatis-PageHelper#582]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.8
* 数据库类型和版本: mysql 5.7.24
* JDBC_URL:
 jdbc:mysql://ip:port/test_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true&useSSL=false

### 问题描述
自己写了一个分表的mybatis 拦截器，大体原理和pagehelper相同

    ShardingTableHelper.markSharding(xxx);

在拦截器中拿到线程变量的值，然后根据分表策略，用分片的表名替换 原来的表名
现在遇到一个问题，和pagehelper一起使用的话，在执行分页查询时，count sql可以正常替换表名，分页query就不行了，问题应该出在，PageInterceptor 先执行了count query，再执行page query，count query把分表的线程变量消耗掉了，执行page query的时候就没线程变量了，有解决办法么？

**Comment by vancefantasy** [comment]
大概debug了下，PageInterceptor拦截的是Executor的query，我自定义的分表拦截器 拦截的是StatementHandler的prepare
mybatis执行拦截器是先执行executor，然后再执行StatementHandler
代码的执行过程大概是这样的

```
PageInterceptor_before

TableShardingInterceptor_before
count_query
TableShardingInterceptor_after(分表线程变量被清理了)

TableShardingInterceptor_before
page_query
TableShardingInterceptor_after

PageInterceptor_after
```

目前的思路是：TableShardingInterceptor_after 清理时，增加判断，如果同时满足
1，originSql包含 count(0)
2，LOCAL_PAGE有数据
就先不清理分表的线程变量

但还是有另外一个问题，count query有可能返回的是0，这种情况就直接返回了。

所以看起来只能定制下PageInterceptor的代码了

**Comment by DIscord010** [comment]
遇到相同的问题，pagehelper是否可以在PageInterceptor增加排除指定MappedStatement的属性配置。

**Comment by abel533** [comment]
@DIscord010
