### ISSUE TITLE
Offset+Limit的参数组合offset必须为limit的整数倍

### ISSUE THREAD

**Issue by MemoryAndDream** [pagehelper/Mybatis-PageHelper#583]
由于列表可能改动，比如本来一页10条数据，然后在第一页删除了一条记录，那我下一页想传offset=9.但是实际测试发现默认的pagehelper对offset不是整数倍时候的判断有问题。比如我有12条数据，我想传offset=1，limit=20就会返回空列表，因为pagehelper以为我现在在第二页了。

目前我的解决方法是自定义了自己的一个PageHelper，然后重写afterCount方法返回true

**Comment by abel533** [comment]
测试用例: src/test/java/com/github/pagehelper/test/basic/OffsetTest.java

执行如下：

![image](https://user-images.githubusercontent.com/1787798/120925250-54b9df80-c70a-11eb-807d-ef4c29ade231.png)

![image](https://user-images.githubusercontent.com/1787798/120925269-67341900-c70a-11eb-9170-8e24a7d7e415.png)

offset直接用提供的，不会重新计算。

**Comment by abel533** [comment]
我怀疑你调用的不是 `offset` 方法，你用的 `startPage` 吧？
