### ISSUE TITLE
Spring+pagehelper分页报错！使用PageHelper得到分页后的数据放到PageInfo中GetList（）得到的空。为什么？求大神讲解

### ISSUE THREAD

**Issue by syz-1998** [pagehelper/Mybatis-PageHelper#586]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.17
* 数据库类型和版本: mysql5.5
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by l-i-h-e** [comment]
是提示了一个数组越界的异常吗？

**Comment by crazyii** [comment]
你是第一次用。。。测试呢吧。 表里没数据对不对？ 
因为没数据， pageSize 会被page#setTotal方法中调用 calculateStartAndEndRow方法优化为0
pageSize = 0 的时候，还需要执行后续查询，但是不会分页

AbstractHelperDialect#afterCount
`@Override
    public boolean afterCount(long count, Object parameterObject, RowBounds rowBounds) {
        Page page = getLocalPage();
        page.setTotal(count);//此处会对分页参数做优化
        if (rowBounds instanceof PageRowBounds) {
            ((PageRowBounds) rowBounds).setTotal(count);
        }
        //pageSize < 0 的时候，不执行分页查询
        //pageSize = 0 的时候，还需要执行后续查询，但是不会分页
        if (page.getPageSize() < 0) {
            return false;
        }
        return count > ((page.getPageNum() - 1) * page.getPageSize());
    }`
`/**
     * 计算起止行号
     */
    private void calculateStartAndEndRow() {
        this.startRow = this.pageNum > 0 ? (this.pageNum - 1) * this.pageSize : 0;
        this.endRow = this.startRow + this.pageSize * (this.pageNum > 0 ? 1 : 0);
    }`
