### ISSUE TITLE
SQLServer 在调用数据库链接的查询时，分页查询报错

### ISSUE THREAD

**Issue by richwxd** [pagehelper/Mybatis-PageHelper#589]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.
SQLServer 在调用数据库链接的查询时，分页查询报错
### 使用环境
Windows 10, 在bDB里新建一个本地别名的aDB的链接数据库，查询时带上一些前缀

* PageHelper 版本: xxx
* 数据库类型和版本: SQLServer2012 Enterprise
* JDBC_URL: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=bDB

### SQL 解析错误
select count(0) from (  select ID,  field1,  field2,  field3,  field4 from [aDB].[atable].[dbo].[aTable]  order by field1) tmp_count

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select ID,  field1,  field2,  field3,  field4 from [adb].[atable].[dbo].[aTable]  order by field1
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
`com.microsoft.sqlserver.jdbc.SQLServerException: 除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效``

### 其他类型的错误

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by onlyas** [comment]
JSqlParser从3.0开始默认不支持SQLServer字段带"[]"或者表名带"[]",解决办法1：把[]改成双引号"",比如把select [name] from [name],改成select "name" from "name".解决方案2，使用JSqlParser的另外一个方法，CCJSqlParserUtil.parse("select * from [mytable]", parser -> parser.withSquareBracketQuotation(true));   方法2需要作者改一下，或者自己打包一个jar。

**Comment by richwxd** [comment]
可是这个不是pagehelper发布的时候应该考虑的吗，不能依赖库有问题，这个包也有问题。那不是砸牌子了。作者来帮忙看看吧，感觉大佬能解决的

**Comment by abel533** [comment]
按照 @onlyas 的方式可以。。等整体升级到jdk8+的时候才能用方法2.

**Comment by Hanwen196** [comment]
@abel533 你是不是用的方法一，就是把 [] 换成 “”， 例如 select "name" from "student" ? 如果是的话，能不能把你的sql贴一下，我这边有类似的问题。

我需要加入，where like 这类条件，但是不太行

![image](https://user-images.githubusercontent.com/10524800/128033138-1b8af40a-9aa8-486b-b957-154bc2bf8e10.png)
![image](https://user-images.githubusercontent.com/10524800/128033190-8134bc36-d60f-4a36-885e-ffcbabb66457.png)

**Comment by richwxd** [comment]
已经放弃很久了，直接从数据库里写存储过程了。虽然那个跨库查询分页不优雅，也很慢。但是要比不能实现的好。建议你也从数据库里实现吧。外部可以直接spring-jdbc调用。需要那个存储过程的话，我可以贴给你。
