### ISSUE TITLE
pageHelper 查询报NPE

### ISSUE THREAD

**Issue by AndyReturn** [pagehelper/Mybatis-PageHelper#591]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

`          <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>1.3.0</version>
            </dependency>
`

* PageHelper 版本: 5.2.0
* 数据库类型和版本: mysql 
* MyBatis-3.4.0

### SQL 解析错误
![image](https://user-images.githubusercontent.com/28351434/105706200-35d16280-5f4c-11eb-805a-0badfeb09ba3.png)

resultHandler 为 null时， pagehHelper的拦截器依旧解析resultHandler 导致报空指针错误，详情见截图图

#### 分页参数

```java
PageHelper.startPage(0,10);
xxMapper.select(model);
```

### 完整异常信息
![image](https://user-images.githubusercontent.com/28351434/105706200-35d16280-5f4c-11eb-805a-0badfeb09ba3.png)

```
异常信息放在这里
![image](https://user-images.githubusercontent.com/28351434/105706200-35d16280-5f4c-11eb-805a-0badfeb09ba3.png)

```

### 其他类型的错误
![image](https://user-images.githubusercontent.com/28351434/105706190-310cae80-5f4c-11eb-8fd1-5dc812fd0eed.png)

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
jdk 版本是什么？强转null不应该出错。
