### ISSUE TITLE
存在重复分页？

### ISSUE THREAD

**Issue by lbings** [pagehelper/Mybatis-PageHelper#593]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.2.0
* 数据库类型和版本: mysql 5.7
* JDBC_URL: xxx
* mybatis-plus
* linux
* 
#### 分页参数
limit 10
```java
PageHelper.startPage(1, 10);
return list(new LambdaQueryWrapper<UserCreditDetailRecord>().eq(UserCreditDetailRecord::getUserId,userId.longValue()).eq(UserCreditDetailRecord::getDataStatus,0).orderByDesc(UserCreditDetailRecord::getCreateTime));
```

#### 原 SQL

```sql
SELECT credit_detail_id,user_id,order_number,credit_name,credit_number,change_credit_number,type,credit_desc,create_time,data_status FROM hjy_ft_user_credit_detail_record WHERE (user_id = ? AND data_status = ?) ORDER BY create_time DESC LIMIT 10
```

#### 期望的结果：

```sql
SELECT credit_detail_id,user_id,order_number,credit_name,credit_number,change_credit_number,type,credit_desc,create_time,data_status FROM hjy_ft_user_credit_detail_record WHERE (user_id = ? AND data_status = ?) ORDER BY create_time DESC LIMIT 20,10
```

### 完整异常信息
发布环境上：每一页10条数据，刚好表里有10条数据，pageNum为1的时候返回的是10条数据，pageNum为2的时候还是第一页的10条数据，不是null

生产环境是能正确返回的

异常信息放在这里
```

### 其他类型的错误

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by crazyii** [comment]
嗯……关于这个问题，之前自己接口测试的时候出现过。之前跟过源码，发现有一段优化分页参数的地方。
大概意思就是，如果你的查询参数不合理，查询的页码根本不存在（一般出现在 接口自测情况下）。 他会给你优化成最后一页。

pagehelper有一个分页参数优化的方法。
你可以断点看一下 Page#setTotal

举例如下： 
**总条数21， 每页10条， 最多有三页， 如果你查询第四页，返回的不会是空。而是第三页的内容。**
pageSize  |  pageNum  | result
     1           |        10        |   limit 10
     2          |        10        |   limit 10,10
     3           |       10        |   limit 20,10
     4          |        10        |   limit 20,10

针对你的问题，
    1. 列出的sql 没有建表 跟insert 语句。
    2. 查询条件未列出参数。
    3. 针对以上两点，无法复现。
建议：

因为你的SQL带有条件，我猜测你的第一页返回的不是10条，所以根本没有第二页， 因此被优化成了 limit 10, 而不是你期望的 limit 10,10
建议重新确认下sql条件参数。

**Comment by abel533** [comment]
看看你是否配置了分页合理化参数：
>5. `reasonable`：分页合理化参数，默认值为`false`。当该参数设置为 `true` 时，`pageNum<=0` 时会查询第一页，
`pageNum>pages`（超过总数时），会查询最后一页。默认`false` 时，直接根据参数进行查询。
