### ISSUE TITLE
pageHelper支持虚谷数据库吗

### ISSUE THREAD

**Issue by Roger0917** [pagehelper/Mybatis-PageHelper#599]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
虚谷数据库的 sql 语句符合 sql92 标准，一个简单 SELECT 语句的语法结构为：
```sql
SELECT [DISTINCT] target_list
[[BULK COLLECT]INTO vars]
FROM table_name
WHERE condition_expr
[GROUP BY column_name[,...] [HAVING bool_expr]]
[ORDER BY column_name[,...] [ASC][DESC]]
[LIMIT limit_value OFFSET offset_value]
[LIMIT ALL [OFFSET offset_value]];
[parallel n]
```

jdbcurl: `jdbc:xugu://IP:port/system`

下个版本支持自动识别。
