### ISSUE TITLE
关于SQL SERVER左关联丢失on及关联条件的问题

### ISSUE THREAD

**Issue by IceWee** [pagehelper/Mybatis-PageHelper#60]
数据库：SQLSERVER2008
Pagehelper版本：4和5
SQL：select a.id from table1 a with(nolock) left join table2 b  with(nolock)  on a.id = b.rid where a.name = 'xxx'
执行问题：
执行SQL会解析成：select count(0) from table1 a with(nolock) left join table2 b with(nolock)  where a.name = 'xxx'
报错信息：where附近语法错误
补充，解析后的SQL中丢失了on 及后面的关联条件

请问如何解决该bug，谢谢！万分感谢！

**Comment by yujie8409** [comment]
你好，这个问题解决了吗？

**Comment by abel533** [comment]
5.1.0 版本会解决这个问题，增加了一个针对 sqlserver 的参数 `replaceSql`，默认还是以前的处理方式，修改成 `regex` 后会使用新的方式处理。。还可以自己实现 `ReplaceSql` 接口。

**Comment by abel533** [comment]
希望能得到5.1.0-beta2版本的反馈！
