### ISSUE TITLE
建议加上PageHelper.startPage(int page ,int size,String bdType)

### ISSUE THREAD

**Issue by wh-19970312** [pagehelper/Mybatis-PageHelper#600]
在动态数据源切换的时候，如果开启auto-runtime-dialect的话，会得到大量的connection造成连接池资源的浪费，经常发生连接池超过最大连接的数量，当设置close-conn: false时候，关闭的连接，但不能够确定这个连接是否被其他的线程在使用，这样会经常发生异常。如果开始就指定那种类型的数据库分页可以很轻松的避免这个问题。

**Comment by wh-19970312** [comment]
有没有方法从开始分页的时候，自己确定数据库的类型

**Comment by abel533** [comment]
考虑在链式调用中增加db类型的设置。

**Comment by abel533** [comment]
关联 #569
