### ISSUE TITLE
查询列表也走分页导致无法查询到数据

### ISSUE THREAD

**Issue by jiangxiaoqiang** [pagehelper/Mybatis-PageHelper#602]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.2.0
* 数据库类型和版本: PostgreSQL 13
* JDBC_URL: jdbc:postgresql://postgres.dolphin.com:5432/dolphin

#### 分页参数

无分页

```
@Override
    public List<Users> list(UserLoginRequest request) {
        UsersExample example = new UsersExample();
        UsersExample.Criteria criteria = example.createCriteria();
        criteria.andPhoneEqualTo(request.getPhone());
        List<Users> users = userMapper.selectByExample(example);
        return users;
    }
```

#### 原 SQL

```sql
select count(1) from users where phone = xxx
```

#### 期望的结果：

```sql
select * from users where phone = xxx
```

### 完整异常信息

无异常信息

## 功能建议

查询列表时，不需要走分页查询。跟踪了源代码，从ThreadLocal中取出的Page对象为0。而判断时只判断了null的情况。后来排查是确实取到了Page对象。但是此对象是其他线程设置的，请问下threadlocal是在哪里清理的？多线程情况下A线程能获取到B线程设置的数据。我用的是JDK 11, 现在的情况看起来处理请求是用的线程池（不是用完即关闭的线程，可能会重用，A线程处理后，没有关闭，B请求重用A线程，读取到了A线程设置的分页数据），A线程中获取到B线程设置的分页数据。下图是文章的分页信息，但是用户查询的时候读取到了。

`    protected static final ThreadLocal<Page> LOCAL_PAGE = new ThreadLocal<Page>();
`

![multithread](https://user-images.githubusercontent.com/4521375/119259376-0bab4c80-bb9c-11eb-9cd0-3bf0db74e3b8.png)

**Comment by jiangxiaoqiang** [comment]
网上已经有分析了，是否可以考虑下这个问题：https://ningyu1.github.io/20190402/114-mybatis-pagehelper-pit.html

**Comment by jiangxiaoqiang** [comment]
好吧。 有没有清理threadlocal的情况，手工获取了分页对象没有执行查询。

**Comment by abel533** [comment]
文档中有一块安全调用，可以看看。
