### ISSUE TITLE
调用toPageInfo(Function<E, T> function)这个方法会导致原 Page 的 total 属性没有赋值到新的 PageInfo里面

### ISSUE THREAD

**Issue by lisonglin** [pagehelper/Mybatis-PageHelper#604]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
  public <T> PageInfo<T> toPageInfo(Function<E, T> function) {
        List<T> list = new ArrayList<T>(this.size());
        for (E e : this) {
            list.add(function.apply(e));
        }
        PageInfo<T> pageInfo = new PageInfo<T>(list);
        pageInfo.setPageNum(this.getPageNum());
        pageInfo.setPageSize(this.getPageSize());
        pageInfo.setPages(this.getPages());
        pageInfo.setStartRow(this.getStartRow());
        pageInfo.setEndRow(this.getEndRow());
        pageInfo.setTotal(this.getTotal); //理应增加本行代码
        pageInfo.calcByNavigatePages(PageInfo.DEFAULT_NAVIGATE_PAGES);
        return pageInfo;
    }
### 使用环境

* PageHelper 版本: 5.2
* 数据库类型和版本: mysql 8.0
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
一共有两处问题，一起改了。

**Comment by abel533** [comment]
周末发布新版本。
