### ISSUE TITLE
使用 Having 查询报错 

### ISSUE THREAD

**Issue by SyStrangers** [pagehelper/Mybatis-PageHelper#606]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select success_count as successCount ,num as Total  from test Having successCount = Total  
```

#### 期望的结果：

```sql
select success_count as successCount ,num as Total  from test Having successCount = Total   limit 10
```

### 完整异常信息
successCount 不存在 
```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by SyStrangers** [comment]
补充一下 
select 
  (SELECT COUNT(1) FROM test1 WHERE test1.id = test.test1_id )as successCount ,
  (SELECT COUNT(1) FROM test1 ) as Total  
from test 
Having successCount = Total

**Comment by chenhao2323** [comment]
这里是不是得再加个如果包含having也不算 com.github.pagehelper.parser.CountSqlParser
 
    `public boolean isSimpleCount(PlainSelect select) {
        //包含group by的时候不可以
        if (select.getGroupBy() != null) {
            return false;
        }
        //包含distinct的时候不可以
        if (select.getDistinct() != null) {
            return false;
        }
        for (SelectItem item : select.getSelectItems()) {
            //select列中包含参数的时候不可以，否则会引起参数个数错误
            if (item.toString().contains("?")) {
                return false;
            }
            //如果查询列中包含函数，也不可以，函数可能会聚合列
            if (item instanceof SelectExpressionItem) {
                Expression expression = ((SelectExpressionItem) item).getExpression();
                if (expression instanceof Function) {
                    String name = ((Function) expression).getName();
                    if (name != null) {
                        String NAME = name.toUpperCase();
                        if(skipFunctions.contains(NAME)){
                            //go on
                        } else if(falseFunctions.contains(NAME)){
                            return false;
                        } else {
                            for (String aggregateFunction : AGGREGATE_FUNCTIONS) {
                                if(NAME.startsWith(aggregateFunction)){
                                    falseFunctions.add(NAME);
                                    return false;
                                }
                            }
                            skipFunctions.add(NAME);
                        }
                    }
                }
            }
        }
        return true;
    }`
@abel533
