### ISSUE TITLE
是否考虑支持OceanBase

### ISSUE THREAD

**Issue by it-linnan** [pagehelper/Mybatis-PageHelper#607]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议

是否考虑支持OceanBase数据库的分页？
OceanBase数据库有两种租户：MySQL、Oracle，不同租户的分页关键字不同，不能通过注册方言(registerDialectAlias)实现分页

PageAutoDialect中自动选择方言考虑新增一种选择器模式，解决这种方言不能静态注册的问题，支持在运行时获取方言类型，与dialectAlias相似，也支持用户扩展

如OB，可以在运行时获取数据库的ProductName，从而获得租户类型

**Comment by PC-Chiu** [comment]
为什么直接关闭了？

**Comment by it-linnan** [comment]
> 为什么直接关闭了？

你也遇到这个问题了吗？我用其他方式规避掉了。

**Comment by PC-Chiu** [comment]
增加了一个配置

```
mybatis:
  configuration-properties:
    "dialectAlias": "oceanbase=com.github.pagehelper.dialect.helper.OracleDialect"
```

准备测试一下试试

**Comment by it-linnan** [comment]
> 增加了一个配置
> 
> ```
> mybatis:
>   configuration-properties:
>     "dialectAlias": "oceanbase=com.github.pagehelper.dialect.helper.OracleDialect"
> ```
> 
> 准备测试一下试试

你的url可以配置成`jdbc:oceanbase:oracle://`，就会直接使用`Oracle`方言
如果是mysql租户，url配置成`jdbc:oceanbase://`，然后加上你那个配置：`oceanbase=MySQLDialect`

**Comment by PC-Chiu** [comment]
好的，谢谢

**Comment by luoqiren** [comment]
> > 增加了一个配置
> > ```
> > mybatis:
> >   configuration-properties:
> >     "dialectAlias": "oceanbase=com.github.pagehelper.dialect.helper.OracleDialect"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 准备测试一下试试
> 
> 你的url可以配置成`jdbc:oceanbase:oracle://`，就会直接使用`Oracle`方言 如果是mysql租户，url配置成`jdbc:oceanbase://`，然后加上你那个配置：`oceanbase=MySQLDialect`

感谢， 成功了
