### ISSUE TITLE
dobbu调用服务，分页无效

### ISSUE THREAD

**Issue by Xiaxinyi** [pagehelper/Mybatis-PageHelper#611]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.2

使用 dobbu 调用服务
有 mapper.xml的服务 可以分页 ，没有的 无法分页 返回了 全部数据

**Comment by chenhao2323** [comment]
这个记录分页使用threadlocal实现的,要实现dubbo传递,可以考虑在dubbo filter里写

**Comment by abel533** [comment]
用了好多年dubbo，没有发现问题。

注意调用分页方法必须放在Mapper查询前，一定不能在service外调用`PageHelper`的方法。
