### ISSUE TITLE
拦截器应该先判断是否需要 skip，这样在不需要分页时可以提升性能，避免了不必要的代码执行

### ISSUE THREAD

**Issue by aqier** [pagehelper/Mybatis-PageHelper#613]
https://github.com/pagehelper/Mybatis-PageHelper/blob/9ea1fb091478d78f3713465961dd0a6c14ae249d/src/main/java/com/github/pagehelper/PageInterceptor.java#L96

**Comment by abel533** [comment]
不清除你指的判断是否在下面方法：
```java
default Object plugin(Object target) {
   return Plugin.wrap(target, this);
}
```
如果是这里，和 #614 类似，这里不能完全实现，只有当完全通过 `PageHelper.startPage` 等静态方法时，能提前判断是否拦截。。当使用参数或RowBounds时不能判断。
