### ISSUE TITLE
建议增加 是否使用内存分页的开关，某些场景就是不用分页，但需要执行其他拦截器，此处就跳过了所有拦截器。

### ISSUE THREAD

**Issue by aqier** [pagehelper/Mybatis-PageHelper#614]
https://github.com/pagehelper/Mybatis-PageHelper/blob/9ea1fb091478d78f3713465961dd0a6c14ae249d/src/main/java/com/github/pagehelper/PageInterceptor.java#L111

**Comment by abel533** [comment]
可以实现跳过，但是这会让其他拦截器更难处理。分页时一套，不分页时一套。

所以建议如果能重写的情况下，可以参考：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md 这里进行调整。
