### ISSUE TITLE
Sqlserver使用分页时，JSqlParser无法解析中括号问题

### ISSUE THREAD

**Issue by Fourcks** [pagehelper/Mybatis-PageHelper#617]
- [√ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: pagehelper-spring-boot-starter 1.3.1
* 数据库类型和版本: SQL Server 2016 (SP1)
* JDBC_URL: jdbc:sqlserver://localhost:1433;DatabaseName=myDbName

### SQL 解析错误
`### SQL: select count(0) from (  SELECT [1],[2t]  FROM rpt_count  ) tmp_count`
`### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!`
`      at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:106)`
`......`
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "[" "["`

#### 分页参数

```java
`PageHelper.startPage(1,10);`
`Object rs = rptCountMapper.selectAll();`
```

#### 原 SQL

```sql
SELECT [1],[2t] FROM rpt_count
```

###  其他Issue参考
该问题可能与Jsqlparser的版本更新有关。
other JSQLParser Issue : [net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "\[" "\["](https://github.com/JSQLParser/JSqlParser/issues/1281)
other PageHelp Issue : [无法解析中括号的问题](https://github.com/pagehelper/Mybatis-PageHelper/issues/568)

### 修改建议
JSQLParser的Issue建议在解析包含中括号的sqlserver 的 sql 语句 时使用 withSquareBracketQuotation 设置中括号解析规则。
希望PageHelper也能提供类似的选择条件并实现方括号解析。

例:PageHelper.withSquareBracketQuotation.startPage(1,10) 或 PageHelper.startPage(1,10,(boolean)withSquareBracketQuotation)

由于目前我生产环境这票人经常用些匪夷所思的字段命名，把保留字和数字命名这种玩意基本用的差不多了。改字段是没得改了。

**Comment by Fourcks** [comment]
update:
尝试了覆盖SqlServerParser类，以非lambda的方式添加了withSquareBracketQuotation来修饰parser。
`CCJSqlParserUtil.parse(sql,`
`new Consumer<CCJSqlParser>() {`
`@Override`
`public void accept(CCJSqlParser ccjSqlParser) {`
`ccjSqlParser.withSquareBracketQuotation(true);`
`}`
'});'
但是依然会抛出 Encountered unexpected token: "[" "["
进一步测试发现 SELECT [id],[t2n] FROM rpt_count 这条语句不会发生问题。
多次验证认为JSQLParser可能将以数字开头的[]认为是数组下标选择的语法。[2t]不行，但是[t2n] 又可以。
我可能得去JSQLParser那里也提一个Issue了……

**Comment by Fourcks** [comment]
update:
尝试了覆盖SqlServerParser类，以非lambda的方式添加了withSquareBracketQuotation来修饰parser。
`CCJSqlParserUtil.parse(sql,`
`new Consumer<CCJSqlParser>() {`
`@Override`
`public void accept(CCJSqlParser ccjSqlParser) {`
`ccjSqlParser.withSquareBracketQuotation(true);`
`}`
'});'
但是依然会抛出 Encountered unexpected token: "[" "["
进一步测试发现 SELECT [id],[t2n] FROM rpt_count 这条语句不会发生问题。
多次验证认为JSQLParser可能将以数字开头的[]认为是数组下标选择的语法。[2t]不行，但是[t2n] 又可以。
我可能得去JSQLParser那里也提一个Issue了……

**Comment by Fourcks** [comment]
JSQLParser组关于无法支持方括号内表名或列名以数字开头或纯数字的问题回复如下
[无法支持SQL Server方括号数字列名表名的问题](https://github.com/JSQLParser/JSqlParser/issues/1304)

简答来说，对面没打算完全实现SQL Server方括号兼容方案，现有的withSquareBracketQuotation估计就是最终方案了。对于至少以字母开头的字段和表来说是可以接受的。
双引号兼容方案 `"2"` 代替 `[2]` 可行的，而且理论上也该这么做。主要SQLServer支持这么离谱的命名本身就很离谱。
现在看来我得自己收拾这坨X山代码了……

大佬不知道后续又没处理兼容`[2]`这种命名的打算?

**Comment by abel533** [comment]
没有处理兼容`[2]`这种命名的打算。
