### ISSUE TITLE
分页查询注入错误结果

### ISSUE THREAD

**Issue by SongTing0711** [pagehelper/Mybatis-PageHelper#619]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境
jdk1.8
* PageHelper 版本: pagehelper-spring-boot-starter
* 数据库类型和版本: mysql
* 
#### 原 代码
```java
Page<BatteryCompensateDTO> page = PageHelper.startPage(request.getPageIndex(), request.getPageSize()).
                doSelectPage(() -> batteryOperationService.selectWaitApplySn(request.getModel()));
public List<BatteryCompensateDTO> selectWaitApplySn(WaitApplySnRequestDTO requestDTO) {
        BatteryCompensateApply batteryCompensateApply = 
                                  batteryCompensateApplyMapper.selectByApplyNo(requestDTO.getApplyNo());
        if (Objects.isNull(batteryCompensateApply)) {
            throw new BusinessException(BatteryOperationErrorCodeEnum.MISS_COMPENSATE_APPLY);
        }
        requestDTO.setIsExempt(BooleanEnum.FALSE.getCode());
        return batteryCompensateMapper.selectWaitApplySn(requestDTO);
 }
```
#### 期望的结果：

返回batteryCompensateMapper.selectWaitApplySn(requestDTO);的分页结果

#### 最终的结果：
返回 batteryCompensateApplyMapper.selectByApplyNo(requestDTO.getApplyNo());分页结果

#### 原因分析
在lamda表达式结合PageHelper的时候，PageHelper只对于其中存放的第一个sql查询起作用，在PageInterceptor中调用dialect.afterAll();对LOCAL_PAGE进行清空，后面真正要返回的sql查询不会进行分页。
当然也可以认为PageHelper的API只能用于单个sql方法查询，但是个人认为这对于不了解的同学是不友好的。
同时将分页的结果赋值给返回参数，忽略了真正需要返回的数据也是不合理的。

## 功能建议
通过服务前端编译器-语义分析与字节码生成-数据及控制流分析，检测方法的返回值，只有触发返回值的sql查询才能触动PageHelper分页，而不是单纯的在拦截器中判断线程缓存是否存在。

**Comment by abel533** [comment]
doSelectPage中必须是 Mapper 方法，不能是 Service 方法。
