### ISSUE TITLE
5.3.0的PageHelper中只要默认给定pageSize=0，配置的supportMethodsArguments=true就不生效，不默认查所有

### ISSUE THREAD

**Issue by Yikeji** [pagehelper/Mybatis-PageHelper#627]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.3.0
* 数据库类型和版本: MysqL
* JDBC_URL: com.alibaba.druid.pool.DruidDataSource

#### 分页参数

```java
PageHelper.startPage(0, 0);
xxMapper.select(model);
```
pagehelper:
 supportMethodsArguments: true

在5.3.0的版本中，配置的supportMethodsArguments=true 默认如果pageSize=0时，查询所有的数据，但是如果在实体类中出现pageSize属性，本身不想分页的内容，结果不继续执行查询语句，在select count（0） 后就不再进行继续执行了

**Comment by ykfs** [comment]
我也出现类似问题，supportMethodsArguments没有配置，5.1.9版本，PageHelper.startPage(0, 0)会查所有数据；
5.3.0不查数据；
我想知道是否是有意为之，从哪个版本开始的？为什么这么改？

**Comment by abel533** [comment]
@ykfs 你和上面发的应该不是一回事。你的 `pageSizeZero` 配置的是什么？如果是 `true`结果就是对的。

另外`startPage` 第一页是 1，不是0.。。如果没有配置 `reasonable` 合理化，超出范围时，查询是没有数据的。

**Comment by ykfs** [comment]
> 
pageSizeZero和reasonable都没有配置，默认的；
现象是5.1.9版本是查询所有数据的，5.3.0是不查数据，

**Comment by ykfs** [comment]
> @ykfs 你和上面发的应该不是一回事。你的 `pageSizeZero` 配置的是什么？如果是 `true`结果就是对的。
> 
> 另外`startPage` 第一页是 1，不是0.。。如果没有配置 `reasonable` 合理化，超出范围时，查询是没有数据的。

pageSizeZero和reasonable都没配置，都是默认值；
但是5.1.9是可以查询出所有数据，5.3.0是没有数据的；
我知道第一页是1，这个PageHelper.startPage(0, 0)是不规范的用法，但是现在是新的版本行为和老版本不一致了，问题影响面比较大

**Comment by abel533** [comment]
可以看看更新日志，不一样是低版本的逻辑有bug。。解决后的高版本看着就不一样了。

**Comment by ykfs** [comment]
@abel533 那也应该开通一些参数，能够兼容低版本的原有形式，这种不兼容的改造，就没法升级了，这种也不是bug，就是固定0，0返回的形式，可以固定是有结果返回，也可以固定没结果，但是应该是要向下兼容的，至少也要有参数支持兼容

**Comment by ykfs** [comment]
@abel533 另外更新日志中的内容太多了，能具体说下是哪块逻辑的改造，影响了0，0的表现形式吗

**Comment by aixiaolife** [comment]
刚遇到这问题，最终结果是reasonable: true 配置加上pageSizeZero: true才起作用能查询到所有数据，reasonable是false的话pageSize传0新版本是不查询数据的. 版本是5.3.3

**Comment by aixiaolife** [comment]
但是reasonable: true 会使得请求超出最大页数的时候 返回最后一页的数据 也会影响原有的逻辑，综上所述 就不应该把pageSizeZero: true 和 reasonable: true的关系绑定  ，pageSizeZero: true 应该认为0是合法参数并进行查询 不应该受到reasonable参数的影响

**Comment by aixiaolife** [comment]
pagehelper-spring-boot-starter 版本升到2.0.0  可以解决 reasonable: false时 pageSize=0 查询所有数据，但是pageNum需要传>=1  不然会认为非法数据
pagehelper 里面的代码版本对应为6.0.0
pagehelper-spring-boot-starter 从1.4.0到1.4.7都有这个问题 对应pagehelper 问题版本为5.3.0左右
