### ISSUE TITLE
使用pagehelper分页时出现java.lang.NoSuchMethodError异常

### ISSUE THREAD

**Issue by wuyoushan** [pagehelper/Mybatis-PageHelper#63]
java.lang.NoSuchMethodError: org.apache.ibatis.reflection.MetaObject.forObject(Ljava/lang/Object;Lorg/apache/ibatis/reflection/factory/ObjectFactory;Lorg/apache/ibatis/reflection/wrapper/ObjectWrapperFactory;)Lorg/apache/ibatis/reflection/MetaObject;

**Comment by abel533** [comment]
分页插件版本是多少？MyBatis的接口变过几次，比较新的版本都能兼容。

**Comment by asknico** [comment]
isSupportedSql方法在5.0.3中是不是去掉了？有替代方法没？

**Comment by abel533** [comment]
没有替代方法。
