### ISSUE TITLE
PSQLException: ERROR: LIMIT #,# syntax is not supported Hint

### ISSUE THREAD

**Issue by fanfanfufu** [pagehelper/Mybatis-PageHelper#633]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
分页导致语法错误

### 使用环境

* PageHelper 版本: 5.2.1
* 数据库类型和版本: greenplum
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10).doSelectPageInfo(() -> xxxxx);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx 
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10 offset 20
```

### 完整异常信息
期望使用PostgreSQL的分页语法，结果添加了MySQL的分页语法，导致报错。

```
Error querying database. Cause: org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported Hint: Use separate LIMIT and OFFSET clauses.
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by cqu2014** [comment]
您的邮件王振已收到 。

**Comment by abel533** [comment]
jdbcurl格式是什么？如果和默认的不一样，指定PostgreSQL方言试试。

**Comment by fanfanfufu** [comment]
> 

jdbc:postgresql:xxxxxx
我一开始随便找了个博客，照着它说的在配置文件中增加了一个配置项pagehelper.dialect-alias=postgresql=com.github.pagehelper.dialect.helper.PostgreSqlDialect，但是并没有用；
因为我们的服务三个数据源MySQL，GreenPlum，ClickHouse，都支持 `limit m offset n` 这种写法，所以后来我直接增加了一个配置：pagehelper.helperDialect=postgresql，才解决这个问题。

但是比较奇怪的在我增加配置前，服务在测试环境并没有这种问题，反而在生产环境有这个问题，一直没搞明白怎么回事。
我们的服务是三个数据源：MySQL，GreenPlum，ClickHouse，配置的多数据源的名称分别是mysql, gp, ck。
测试环境只部署了一个节点，生产环境是两个节点。

**Comment by fanfanfufu** [comment]
> jdbcurl格式是什么？如果和默认的不一样，指定PostgreSQL方言试试。

jdbc:postgresql:xxxxxx
我一开始随便找了个博客，照着它说的在配置文件中增加了一个配置项pagehelper.dialect-alias=postgresql=com.github.pagehelper.dialect.helper.PostgreSqlDialect，但是并没有用；
因为我们的服务三个数据源MySQL，GreenPlum，ClickHouse，都支持 limit m offset n 这种写法，所以后来我直接增加了一个配置：pagehelper.helperDialect=postgresql，才解决这个问题。

但是比较奇怪的在我增加配置前，服务在测试环境并没有这种问题，反而在生产环境有这个问题，一直没搞明白怎么回事。
我们的服务是三个数据源：MySQL，GreenPlum，ClickHouse，配置的多数据源的名称分别是mysql, gp, ck。
测试环境只部署了一个节点，生产环境是两个节点。

**Comment by abel533** [comment]
默认不支持的可以通过 `dialect-alias` 进行配置，想替换实现的也可以配置。
