### ISSUE TITLE
在QueryInterceptor 中怎么判断是count，还是最终执行的查询呢

### ISSUE THREAD

**Issue by wangxuexi** [pagehelper/Mybatis-PageHelper#634]

**Comment by abel533** [comment]
如果是自动生成的count查询，所有的 msId都是 `_COUNT` 后缀。
https://github.com/pagehelper/Mybatis-PageHelper/blob/2532a1d8a5323683d6562b77fcbd428641cd561c/src/main/java/com/github/pagehelper/PageInterceptor.java#L160
