### ISSUE TITLE
postgresql的分页语法问题

### ISSUE THREAD

**Issue by fanfanfufu** [pagehelper/Mybatis-PageHelper#642]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.2.1
* 数据库类型和版本: greenPlum
* JDBC_URL: jdbc:postgresql

### SQL 解析错误

我看源码中，postgresql添加的分页语法是 offset ? limit ? 。
但是晚上普遍搜索到的postgresql的分页语法是limit ? offset ?，并且在mybatis-plus的分页dialect中，postgresql的dialect也是limit ？ offset ？，
所以对于postgresql的分页语法是否有一个正确的使用方式？

**Comment by outian** [comment]
请问这个问题解决了吗，目前我也发现了这个问题，这个问题导致使用Mybatis Plus的租户拦截器时会出现分页问题。
