### ISSUE TITLE
"static" base class members should not be accessed via derived types

### ISSUE THREAD

**Issue by zhangchengfa** [pagehelper/Mybatis-PageHelper#643]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.11

### 使用sonarlint做代码检查

提示：
Use static access with "com.github.pagehelper.page.PageMehod" for "startPage"

"static" base class members should not be accessed via derived types

In the interest of code clarity, static members of a base class should never be accessed using a derived type's name. 
Doing so is confusing and could create the illusion that two different static members exist.

分析：
 PageHelper继承了PageMehod，并未重写PageMethod的静态方法startPage，使用时直接使用了子类PageHelper去调用startPage是否不太规范？

**Comment by abel533** [comment]
按照静态方法的某些规范，这里确实会检查出来。

不影响使用。

**Comment by fyyCode** [comment]
有什么方法规避吗
