### ISSUE TITLE
主从库切换失败

### ISSUE THREAD

**Issue by rookiedev-z** [pagehelper/Mybatis-PageHelper#649]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 问题描述

通过继承 DataSourceRoutingManager 来实现主从数据源切换，在 Mapper 层进行 Aop 拦截判断是查询还是更新，查询走从库，更新走主库。目前使用 PageHelper.startPage 进行分页查询，结果每次分页查询，先进入到了 Aop 设置数据源为从库，但最终查询还是走主库，请问是什么原因导致

### 使用环境

* PageHelper 版本: 5.1.8
* 数据库类型:  MySQL

#### 期望的结果：

期望分页查询走从库查询

**Comment by abel533** [comment]
分页插件不会影响数据源。
