### ISSUE TITLE
5.0.2分页是默认使用Limit OFFSET 方法的吗?

### ISSUE THREAD

**Issue by smembers** [pagehelper/Mybatis-PageHelper#65]
如题,不想使用offset方法的, 想使用limit 0,10 这种方式的, 在哪里配置?

**Comment by smembers** [comment]
`JDBC Connection [jdbc:mysql://221.208.170.174:3306/yundongguanjia_new?useUnicode=true&characterEncoding=UTF-8, UserName=ydgjlt@113.4.12.14, MySQL Connector Java] will be managed by Spring
==>  Preparing: SELECT count(0) FROM TM_MEMBER_SYS_NOTICE t WHERE 1 = 1 AND t.USER_ID = ? AND t.NEWS_TO_TABLE = ? AND t.NEWS_TO_ID = ? LIMIT ? OFFSET ? 
==> Parameters: 147(String), CLUB(String), e5cde6a915e248f09641d0b15d9dd7af(String), 0(Integer), 10(Integer)
<==      Total: 0
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e726b9c]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e726b9c]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e726b9c]`

**Comment by smembers** [comment]
`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
### The error may exist in com/longti/ydgj/mapping/TM_MEMBER_SYS_NOTICE.xml
### The error may involve com.longti.ydgj.entity.TM_MEMBER_SYS_NOTICE.selectTM_MEMBER_SYS_NOTICEList_COUNT
### The error occurred while handling results
### SQL: SELECT count(0) FROM TM_MEMBER_SYS_NOTICE t WHERE 1 = 1 AND t.USER_ID = ? AND t.NEWS_TO_TABLE = ? AND t.NEWS_TO_ID = ? LIMIT ? OFFSET ?
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`

**Comment by smembers** [comment]
我看到在count(0) 的时候发现在sql的后面加上了  LIMIT ? OFFSET ?   但是我的另外一个项目就不会, 一样的配置

**Comment by abel533** [comment]
@smembers 很有可能是你配置了两个分页插件导致的，或者你被分页的SQL本身自带分页。

**Comment by smembers** [comment]
@abel533  OK,多谢,  找到原因了, 因为参数实体对象中有分页字段, 实体不是我写的, 我纠结了好久......

**Comment by abel533** [comment]
记得换到最新版本，5.0.3+.
