### ISSUE TITLE
能新增默认对TDengine的支持吗？或者有人知道怎么配置不支持的数据库吗？我按照文档试了没成功。

### ISSUE THREAD

**Issue by Chenchen123456789** [pagehelper/Mybatis-PageHelper#650]
springboot工程pagehelper版本5.1.11
我在application.yml里这样配置pagehelper:
dialect-alias: taos=com.github.pagehelper.dialect.helper.MySqlDialect
报错说不能自动识别 taos。换成大写的TAO就报错初始化TAO失败。
tdengine 的jdbcurl是这样的 jdbc:TAOS://test:6030/**?timezone=GMT%2B8&charset=UTF-8&locale=en_US.UTF-8

**Comment by abel533** [comment]
有可能是starter对dialect-alias的配置没有生效，可以试试最新版本的starter。
