### ISSUE TITLE
pageHelper使用using动态设置helperDialect导致默认写法异常

### ISSUE THREAD

**Issue by hejinguo** [pagehelper/Mybatis-PageHelper#652]
yml文件配置：
pagehelper:
  helper-dialect: mysql

Service中方法A：
PageHelper.startPage(1, 10).using("oracle");
List<User> list = userMapper.selectAll();

Service中方法B：
PageHelper.startPage(1, 10);
List<User> list = userMapper.selectAll();

1.访问controller接口调用A方法 正常
2.访问controller接口调用B方法 正常
3.访问controller接口调用A方法 异常,语法错误

目前对于B方法也全都加上了using("mysql")来处理的。

**Comment by abel533** [comment]
com.github.pagehelper.test.features.dialectclass.UsingDialectClassTest

这个测试类中没有发现问题。。能在类似单元测试复现吗？
