### ISSUE TITLE
使用 PageHelper 分页插件时，必须设置 helper 属性

### ISSUE THREAD

**Issue by archyly** [pagehelper/Mybatis-PageHelper#657]
### 使用环境

* PageHelper 版本: pagehelper-spring-boot-starter:1.4.2
* 数据库类型和版本: kingbase8
* JDBC_URL: jdbc:kingbase8://

我想强制使用postgresql，但是配置文件好像没有起作用
pagehelper:
  dialect-alias: postgresql
  auto-dialect: false

好像仍然去 jdbc url 中解析去了。
![image](https://user-images.githubusercontent.com/4350270/162654965-29941c3d-5d81-4252-a541-bf63c97ea675.png)

![image](https://user-images.githubusercontent.com/4350270/162654651-729d715c-a170-4470-a110-6257bbac2136.png)

**Comment by ohsweetbaby** [comment]
请问解决了吗

**Comment by archyly** [comment]
> 请问解决了吗

我直接代码中动态指定的 ,可以使用
```
        PageHelper.startPage(page, limit).using("postgresql");
        List list= mapper.list();
        PageInfo<FormVO> pageInfo = new PageInfo<>(list);
```

**Comment by abel533** [comment]
使用最新版本 starter，或者参数名使用 `dialectAlias`
