### ISSUE TITLE
Upgrade jsqlparser

### ISSUE THREAD

**Issue by bedla** [pagehelper/Mybatis-PageHelper#662]
Hi,
I found that currently you use jsqlparser v4.2, but newer version is v4.4 (which we want to use in our project). It also fails at SqlServerTest.testSql377.
Do you have plans to upgrade it, or at least shade that library?
Also I found that it is regression of jsqlparser between v4.3 and v4.4 and I have created issue https://github.com/JSQLParser/JSqlParser/issues/1520
What do you think?
Thx
Ivos

**Comment by abel533** [comment]
升级到 4.2 类。
