### ISSUE TITLE
查询数据返回类型为Page

### ISSUE THREAD

**Issue by stjyc** [pagehelper/Mybatis-PageHelper#666]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，有类似的问题但不能解决我的问题！

### 使用环境

* pagehelper-spring-boot-starter版本: 1.4.2
* 数据库类型和版本: MySQL 5.7.36

#### 代码 

```java
        Page<Object> page = PageHelper.startPage(pageNum, pageSize);
        Page<TbContent> tbContents = (Page<TbContent>) tbContentMapper.selectByExample(example);
        System.out.println(tbContents.getClass().getName()); //com.github.pagehelper.Page
        System.out.println(tbContents.getResult().getClass().getName()); //com.github.pagehelper.Page
        System.out.println(tbContents.getResult().size()); //0
        System.out.println(tbContents.getResult().get(0)); //java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

#### 问题：
代码中获取的类名不应该是两个不同的吗？为什么都是Page？
我要怎么获取结果？
还请大佬们多多指教

**Comment by abel533** [comment]
[    public List<E> getResult() {](https://github.com/pagehelper/Mybatis-PageHelper/blob/ab7f661233ebb1f5676fe3be9b7f6505c4cabf51/src/main/java/com/github/pagehelper/Page.java#L144-L146)

方法返回的 `this`，肯定一样。。这个 `Page` 继承了 `ArrayList`，你当成集合用。
