### ISSUE TITLE
多数据源分页，分页语法不对

### ISSUE THREAD

**Issue by dearMOMO** [pagehelper/Mybatis-PageHelper#668]
pagehelper会以第一次的数据源为基础，进行分页语法。如果我调用的是mysql，那么我后面切换成Oracle的数据源，分页语法还是mysql。没法切换成Oracle的

**Comment by dearMOMO** [comment]
pagehelper:
  auto-runtime-dialect: true
  auto-dialect: true
  reasonable: true

**Comment by dearMOMO** [comment]
设置了不行
pagehelper:
  auto-runtime-dialect: true
  auto-dialect: true
  reasonable: true

**Comment by abel533** [comment]
有可能是无法从连接获取数据库类型，你用的什么数据源连接池？

**Comment by wtjperi2003** [comment]
@pagehelper +1,   @abel533 druid datasource

**Comment by wtjperi2003** [comment]
> 设置了不行
> 
> ```yaml
> pagehelper:
>   auto-runtime-dialect: true
>   auto-dialect: true
>   reasonable: true
> ```

通过看源码，我找到原因了，配置不能横线分割：autoRuntimeDialect
