### ISSUE TITLE
请问pagehelper怎么处理select for update的分页？

### ISSUE THREAD

**Issue by tiger822** [pagehelper/Mybatis-PageHelper#671]
Raw sql:
select * from stock_tbl st where commodity_code >='c002' order by commodity_code for update

我期望得到的分布sql:
select * from stock_tbl st where commodity_code >='c002' order by commodity_code limit ? offset ? for update
但是pagehelper转换得到的sql:
select id, commodity_code, count from stock_tbl
   order by commodity_code for update
 LIMIT ?  offset ?

PageHelper 版本： 5.3.0

**Comment by abel533** [comment]
建议手写。
