### ISSUE TITLE
分页时，如果返回的集合字段包含聚合函数max时，查询值与原始值，不一致

### ISSUE THREAD

**Issue by zhonghang1993** [pagehelper/Mybatis-PageHelper#676]
版本：
`        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.3.1</version>
        </dependency>
`

数据库mysql8.0

sql：

` select sl.assets_id , ai.assents_img,ai.assets_name ,ai.assets_status,ai.assets_status_color
             ,sl.episode_id , max(sl.addition) as 'addition' ,pe.episode_name,pe.english_name
        from adms_assets_shot_link sl
        LEFT JOIN adms_project_episode pe on pe.id = sl.episode_id
        left join adms_assets_info ai on ai.id = sl.assets_id
`

分页时，如果返回的集合字段包含**addition**字段时，查询出来的数据库原始值会被覆盖成其他的值，是使用了聚合函数max的原因？

**Comment by abel533** [comment]
是。

数据量小了，max值有影响。
