### ISSUE TITLE
[建议]目前在使用Mybatis plus，期望在项目中同时用 pagehelper 和 mybatis plus，烦请解决依赖冲突

### ISSUE THREAD

**Issue by thlws** [pagehelper/Mybatis-PageHelper#678]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 建议，非bug

项目中同时使用 mybatis plus, pagehelper ，但 pagehelper 依赖引用的 jsqlparse & mybatis 版本低于mybatis plus, 忘能采纳建议，升级 pagehelper 中的依赖，解决依赖冲突，方便大家使用，感谢。

#### maven坐标及版本
```xml
<dependency>
    <groupId>com.github.pagehelper</groupId>
    <artifactId>pagehelper-spring-boot-starter</artifactId>
    <version>1.4.3</version>
</dependency>
```
```xml
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <version>3.5.2</version>
    </dependency>
```

依赖冲突附图
![jsqlparse-冲突](https://user-images.githubusercontent.com/10988652/175817420-4e81c5a9-7554-44ba-9f06-cca00c4b2538.jpg)
![mybatis-冲突](https://user-images.githubusercontent.com/10988652/175817424-a80ab8a2-7392-42cd-a7c3-c84d79d80501.jpg)

@leaves615 @lihongzheshuai @moonfruit @mallim @abel533

**Comment by thlws** [comment]
@leaves615 @lihongzheshuai @moonfruit @mallim

**Comment by abel533** [comment]
已升级到 4.5
