### ISSUE TITLE
分页后tkmybatis的Eample.selectProperties 和excludeProperties不生效

### ISSUE THREAD

**Issue by sunl888** [pagehelper/Mybatis-PageHelper#679]
- [√] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: mysql8
* JDBC_URL: xxx
* pagehelper-spring-boot-starter 版本：1.2.13

#### 分页参数

```java
Example example = new Example(UserLike.class).excludeProperties("bizId");
PageHelper.startPage(1,2);
userLikeMapper.selectByExample(example);
```

#### 原 SQL

```sql
select id,user_id,biz_type,biz_id from user_like 
```

#### 期望的结果：

```sql
select biz_id from user_like 
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
excludeProperties 是排除，和你期望的SQL不一样。
