### ISSUE TITLE
6.x 移除Order by 功能

### ISSUE THREAD

**Issue by abel533** [pagehelper/Mybatis-PageHelper#680]
去掉排序功能，有需要的自己实现。

**Comment by ryphnyuan** [comment]
排序功能是个很有用的功能，建议保留，只删除setUnsafeOrderBy方法

**Comment by baofeidyz** [comment]
可以多描述一点为什么想要去掉这个order by的feature么？个人认为这还是一个很好的feature，希望不要移除
