### ISSUE TITLE
使用动态数据源时，会在一个业务里面动态切换mysql与sqlserver，因为PageAutoDialect只初始化一次delegate，在新版中不通过page传参时无法自动识别

### ISSUE THREAD

**Issue by piscesdc** [pagehelper/Mybatis-PageHelper#687]
由于我在一个业务类中使用spring的动态数据源AbstractRoutingDataSource，我是用的比较特殊，此查询没有事物的，所以是在dao执行前进行数据源切换的

第一次切换到mysql正常执行，第二次请求切换到sqlserver时，由于PageAutoDialect只会有初始化一次delegate，导致使用的分页的实现类还是mysql的报错，新版中虽然有page入参，但是需要改动大量业务代码
5.1.2版本PageAutoDialect中
    //多数据动态获取时，每次需要初始化
    public void initDelegateDialect(MappedStatement ms) {
        if (delegate == null) {
            if (autoDialect) {
                this.delegate = getDialect(ms);
            } else {
                dialectThreadLocal.set(getDialect(ms));
            }
        }
    }
由于拦截插件是全局唯一的，所以初始化一次后delegate 始终不会变

**Comment by abel533** [comment]
试试最新版本
