### ISSUE TITLE
QueryInterceptor执行链路问题

### ISSUE THREAD

**Issue by wkclz** [pagehelper/Mybatis-PageHelper#688]
- [OK ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 已经完成
1. 已经阅读 QueryInterceptor 相关的 issues
2. 已经阅读 wikis/zh/Interceptor.md
3. 已经明白，需要拦截6个参数的 query 才能保证被调用

### 疑问
为什么 QueryInterceptor  没有 proceed() 过程，调用链不会断，还是继续往下执行，而不被重复执行 query 呢

**Comment by abel533** [comment]
很神奇啊
