### ISSUE TITLE
pageSizeZero设置为true时，相当于没有执行分页查询，但是执行了count查询？？？

### ISSUE THREAD

**Issue by xjzrc** [pagehelper/Mybatis-PageHelper#69]
查看原码发现，在PageInterceptor类的93行是先判断是否需要count查询，再在122行判断是否分页查询，是并列的关系。个人觉得这应该不是并列的关系，是包含关系，应该只有需要分页的情况下才需要做count查询。没分页，查询出来的list集合的size不就是是total吗？如果做count查询仅仅是为了计算total，是不是不太合理？希望博主解答。

**Comment by abel533** [comment]
在第88行判断的是否分页
`if (!dialect.skip(ms, parameter, rowBounds)) {`

**Comment by xjzrc** [comment]
122行又判断了一次，是根据pageSizeZero进行判断的，既然我设置pageSizeZero为true.当pageSize=0时，就不想进行分页查询，而是查全部，也就不应该再执行cunt查询。

**Comment by abel533** [comment]
分页插件还有个`PageHelper.count`方法，可以将任意查询转换为count查询。

**Comment by xjzrc** [comment]
个人认为当pageSizeZero设置为true时，分页参数pageSize=0时，就不应该再执行cunt查询，因为这样毫无意义，还损耗性能。

**Comment by windyyong** [comment]
同意楼主的说法,返回全部数据,进行count查询意义就不大了

**Comment by abel533** [comment]
后续考虑特殊情况下的优化。
