### ISSUE TITLE
selectByExample无法命中mappedStatement

### ISSUE THREAD

**Issue by forzjing** [pagehelper/Mybatis-PageHelper#691]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
        Example example = Example.of(entity);
        PageHelper.startPage(request.getPageNum(), request.getPageSize());
        List<Entity> res= tableBaseInfoMapper.selectByExample(example);
        return res;
```

#### 原 SQL

```sql
 超时
```

#### 期望的结果：

```sql
 不超时
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

修复count函数

    private Long count(Executor executor, MappedStatement ms, Object parameter,
                       RowBounds rowBounds, ResultHandler resultHandler,
                       BoundSql boundSql) throws SQLException {
        String countMsId = ms.getId() ;
        // fix:  手写sql对应_COUNT 保持不变
        // fix:  selectByExamle对应selectCountByExample
        if (countMsId.endsWith("selectByExample")){
            countMsId = ms.getId().replaceAll("selectByExample$", "selectCountByExample");
        }else{
            countMsId = ms.getId() + countSuffix;
        }
        Long count;
        // 先判断是否存在手写的 count 查询
        MappedStatement countMs = ExecutorUtil.getExistedMappedStatement(ms.getConfiguration(), countMsId);
        if (countMs != null) {
            count = ExecutorUtil.executeManualCount(executor, countMs, parameter, boundSql, resultHandler);
        } else {
            if (msCountMap != null) {
                countMs = msCountMap.get(countMsId);
            }
            // 自动创建
            if (countMs == null) {
                // 根据当前的 ms 创建一个返回值为 Long 类型的 ms
                countMs = MSUtils.newCountMappedStatement(ms, countMsId);
                if (msCountMap != null) {
                    msCountMap.put(countMsId, countMs);
                }
            }
            count = ExecutorUtil.executeAutoCount(this.dialect, executor, countMs, parameter, boundSql, rowBounds, resultHandler);
        }
        return count;
    }

**Comment by forzjing** [comment]
在PageInterceptor.java里

**Comment by bestwxc** [comment]
目测是数据表过大， 分页查询逻辑未走到索引。
可显示指定排序键（需要索引）

建议关闭。

**Comment by abel533** [comment]
4. `countMsIdGen`（5.3.2+）：count 方法的 msId 生成方式，默认是 查询的 msId +
   countSuffix，想要自己定义时，可以实现 `com.github.pagehelper.CountMsIdGen` 接口，将该参数配置为实现的全限定类名即可。
   **一个常见的用途：** 在有Example查询的情况，`selectByExample` 可以使用对应的 `selectCountByExample` 方法进行 count 查询。

**Comment by forzjing** [comment]
> 

你说的和我的目的不一致呀。
结果就是pagehelper对selectByExample查询生成的count语句是多余的，你生成的时候应该对应上 selectCountByExample作为count语句，如果有什么线程问题，你解决线程问题呀。
还能不能提高了？

还是5.3.2+已经可以让selectByExample对应上selectCountByExample了？我康康。。
你现在selectByExample会重新生成一个重复的count查询缓存。

正常使用当然没有问题。
还能不能提高了？@
