### ISSUE TITLE
使用stream分页总条数不对如何解决

### ISSUE THREAD

**Issue by xiaoqiqiya** [pagehelper/Mybatis-PageHelper#694]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
stream分页是什么意思？

**Comment by xiaoqiqiya** [comment]
> stream分页是什么意思？

可能是返回一个list失去了page结构导致分页总条数不正确，请问如果必须要使用stream流需要怎么返回结构

**Comment by lijing0221** [comment]
给个 demo，要不然你这样描述谁知道你怎么用的

**Comment by chaiyuyi** [comment]
stream流的.collect(Collectors.toList()) 返回的数据类型是 List ,而计算total 的 PageSerializable 会判断 (list instanceof Page) Page 继承了 ArrayList 导致 判断为否 导致数据出问题

**Comment by chaiyuyi** [comment]
stream.collect() 返回值 Instanceof Page 会 false , PageSerializable的构造器会判断 这个条件 if(list instanceof Page) ,导致total计算错误

**Comment by xiaoqiqiya** [comment]
如何可以解决呢

**Comment by abel533** [comment]
提前取出总条数。
