### ISSUE TITLE
在分页查询时,传入页面为1，无查出记录时，返回值有误

### ISSUE THREAD

**Issue by relsol** [pagehelper/Mybatis-PageHelper#7]
![image](https://cloud.githubusercontent.com/assets/19529001/21455734/b8bfee7a-c95d-11e6-9b41-ad5054754805.png)
返回的pageNum为0，isFirstPage为false;
使用方式：
![image](https://cloud.githubusercontent.com/assets/19529001/21455772/fa79cdf4-c95d-11e6-94b0-b97194abb641.png)

**Comment by abel533** [comment]
你的参数pageNo是几？第一页应该传1，不是0。

**Comment by relsol** [comment]
@abel533 pageNo传递的是1

**Comment by relsol** [comment]
@abel533 
![image](https://cloud.githubusercontent.com/assets/19529001/21756045/fd77fbb0-d656-11e6-989f-e2a82b54d90f.png)

查询集合的没了，然后我添加个数据，在看看
![image](https://cloud.githubusercontent.com/assets/19529001/21756071/40f780ae-d657-11e6-92e9-11767ade53f1.png)

传入的参数：
![image](https://cloud.githubusercontent.com/assets/19529001/21756074/50f28954-d657-11e6-8e25-52cd2878226a.png)

**Comment by abel533** [comment]
晕，这不是对的吗？？count 结果是 0 的时候，还分页查询干什么？

**Comment by relsol** [comment]
@abel533  那不应该返回的是第一页么？

**Comment by abel533** [comment]
没有数据哪儿来的第一页，直接返回空集合。

**Comment by yanzhuan051** [comment]
想问一下这个是只针对单表分页么？如果多表分页有用么？

**Comment by IrvingZhao** [comment]
@yanzhuan051 这个是针对所有查询的吧。 startPage 之后的 第一个查询 会执行分页查询，并将查询结果放入startPage的返回值对象中

**Comment by abel533** [comment]
@yanzhuan051 和几个表没关系。。是查询就行。
