### ISSUE TITLE
用了pagehelper 自定义mybatis 拦截器失效的bug

### ISSUE THREAD

**Issue by xiaopingGitHub** [pagehelper/Mybatis-PageHelper#708]
你们自己的mybatis 拦截器中 处理了 拦截 query 相关的逻辑之后 没有执行 invocation.proceed() ，mybatis 的拦截器是责任链模式 你们不执行 此动作 导致自定义的拦截器无法生效。望尽快 修正。

**Comment by abel533** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md

你可以调整插件顺序解决。。也可以参考上面的实现。
