### ISSUE TITLE
mysql 创建临时表后，基于临时表关联查询分页支持吗

### ISSUE THREAD

**Issue by qq2429979710** [pagehelper/Mybatis-PageHelper#709]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

先创建临时表，然后根据临时表做关联查询， 目前分页插件会把创建临时表也包含进去，造成sql异常

### 使用环境

* PageHelper 版本: 5.0.0
* 数据库类型和版本: 8.0.23

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
 CREATE
        TEMPORARY TABLE xxx
    select * from xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

**Comment by abel533** [comment]
不支持含DDL的sql
