### ISSUE TITLE
建议支持从url中解析Kingbase8的dialect

### ISSUE THREAD

**Issue by jssgsy** [pagehelper/Mybatis-PageHelper#710]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 背景及建议
国产数据库金仓已升级到kingbase8，jdbc连接地址前缀为jdbc:kingbase8，低版本连接地址为jdbc:kingbase，PageHelper(PageAutoDialect.java)目前只支持解析kingbase的dialect，建议加入对kingbase8 dialect解析的支持；

### 使用环境

* PageHelper 版本: 5.3.2
* 数据库类型和版本: kingbase8 V8R6
* JDBC_URL: jdbc:kingbase8://ip:port/database_name

**Comment by abel533** [comment]
来个PR
