### ISSUE TITLE
你可以把捐款的地址二维码用外链的形式展示

### ISSUE THREAD

**Issue by ahgaoyong** [pagehelper/Mybatis-PageHelper#717]
你可以把捐款的地址二维码用外链的形式展示, 比如在gitee里面搞一个二维码的外链, 或者其它方式搞一个, 在GitHub里面已链接的形式展示就行, 我看别人的二维码都是 这么做的

**Comment by abel533** [comment]
![image](https://user-images.githubusercontent.com/1787798/202878477-c07eed82-56b4-47e3-8fce-2992506e991f.png)
页面上是有的，后面再加到readme中。
