### ISSUE TITLE
在service之前分页查询后返回结果类型问题

### ISSUE THREAD

**Issue by 1061235166** [pagehelper/Mybatis-PageHelper#72]
pageHelper.start(1,10);
Map<String,Object>result = service.doSomething();
发现result的类型是Page。。而不是Map，很疑惑

**Comment by abel533** [comment]
为什么是Map?

**Comment by 1061235166** [comment]
@abel533 因为我的方法就是这样设计的，返回map类型对象。文档上不是说pagehelper.start了以后下一个sql会自动分页么，所以我调用doSomething也没什么问题啊，关键是有时候不会返回map类型对象而是page对象。

**Comment by abel533** [comment]
分页查询返回的结果不支持 Map。

**Comment by 1061235166** [comment]
但是我一直用的map。。。，都可以

**Comment by 1061235166** [comment]
是返回值类型为List<Map<String,Object>>就是mybatis resultType=map

**Comment by abel533** [comment]
经过分页后的类型是 Page<Map<String,Object>>，Page 就是继承的 ArrayList。
