### ISSUE TITLE
sqlserver offset 语法错误

### ISSUE THREAD

**Issue by JavaLionLi** [pagehelper/Mybatis-PageHelper#721]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 最新
* 数据库类型和版本: sqlserver 2017
* JDBC_URL: jdbc:sqlserver://192.168.31.165:1433;DatabaseName=tempdb;SelectMethod=cursor;encrypt=false;rewriteBatchedStatements=true
* jdbc driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

### SQL 解析错误
offset 语句如果前面没有 order by 语句会报错 这是必须的语法规定
![image](https://user-images.githubusercontent.com/31852897/209294955-3741c01b-aae8-46db-8dd4-d3ea8d5e24be.png)
![image](https://user-images.githubusercontent.com/31852897/209294978-16171b12-1320-401a-81f3-5e3ec30ce7b8.png)

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
select * from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by cqu2014** [comment]
您的邮件王振已收到 。

**Comment by abel533** [comment]
你分页的原始SQL是什么，分页SQL是什么，报了什么错？

**Comment by JavaLionLi** [comment]
> 你分页的原始SQL是什么，分页SQL是什么，报了什么错？

上面的图片里已经很详细了啊
原始sql select * form sys_user
分页之后 select * form sys_user offset 1 rows fetch next 10 rows only
报错 语法异常
改为如下语句后 查询正常:
select * form sys_user order by user_id offset 1 rows fetch next 10 rows only
百度的说法 offset 关键字前面必须跟着 order by

**Comment by abel533** [comment]
原始SQL带上order by就行了。

**Comment by JavaLionLi** [comment]
> 原始SQL带上order by就行了。

我觉得这应该数据分页插件的功能语法 如果没有order by的话应该默认拼接上 而不是让他报错

**Comment by abel533** [comment]
分页插件支持设置order by，仍然需要你调用。。你需要对你自己的SQL负责，自己控制排序。
