### ISSUE TITLE
接手前人代码，里面用了pageHelper，感觉不好用，不理解设计逻辑

### ISSUE THREAD

**Issue by yefeilang** [pagehelper/Mybatis-PageHelper#725]
SELECT * FROM flow_meter_weighing_detail WHERE  1=1 
        <if test="orderBy != null and orderBy != ''">
             ORDER BY ${orderBy}
			<if test="desc != null and desc == true">
				DESC
			</if>
        </if>
        <if test="startPos != null and pageSize != null">
             limit #{startPos},#{pageSize}
        </if>
-->
SELECT * FROM flow_meter_weighing_detail WHERE  1=1  LIMIT 0, 10 order by ID 

接手前人代码，新加了点功能。本来一个好好的简单的sql，跑起来突然发现的order by竟然乱序了，如上。
调试了一番才发现是pageHelper的问题，但我实际就没用PageHelper呀。
仔细调试才发现，核心原因竟然只是我自己的query对象里面有3个字段（“orderBy”，“pageIndex”，“pageSize”），bug来的莫名其妙，再说一遍，但我没用PageHelper呀。

前人用就用，我没意见，但我不用，你不可以影响到我！
1.不理解下面的代码，为什么要执行不满足"params instanceof IPage"部分的内容。这已经说明没有在使用你的插件，也不需要使用了，使用反而导致入侵了不属于插件范围的逻辑。

2.不理解，为什么写死“orderBy”，“pageNum”，“pageSize”这几个变量。如果我恰好数据库有类似字段，怎么办呢。

3.另外，如果sql本身已经有了limit相关sql内容，说明sql一定程度上是完善的，也不需要使用插件。我理解插件只要兜底就可以了，优先级实际是很低的。

public static <T> Page<T> getPageFromObject(Object params, boolean required) {
        if (params == null) {
            throw new PageException("无法获取分页查询参数!");
        }
        if(params instanceof IPage){
            IPage pageParams = (IPage) params;
            Page page = null;
            if(pageParams.getPageNum() != null && pageParams.getPageSize() != null){
                page = new Page(pageParams.getPageNum(), pageParams.getPageSize());
            }
            if (StringUtil.isNotEmpty(pageParams.getOrderBy())) {
                if(page != null){
                    page.setOrderBy(pageParams.getOrderBy());
                } else {
                    page = new Page();
                    page.setOrderBy(pageParams.getOrderBy());
                    page.setOrderByOnly(true);
                }
            }
            return page;
        }
        int pageNum;
        int pageSize;
        MetaObject paramsObject = null;
        if (hasRequest && requestClass.isAssignableFrom(params.getClass())) {
            try {
                paramsObject = MetaObjectUtil.forObject(getParameterMap.invoke(params, new Object[]{}));
            } catch (Exception e) {
                //忽略
            }
        } else {
            paramsObject = MetaObjectUtil.forObject(params);
        }
        if (paramsObject == null) {
            throw new PageException("分页查询参数处理失败!");
        }
        Object orderBy = getParamValue(paramsObject, "orderBy", false);
        boolean hasOrderBy = false;
        if (orderBy != null && orderBy.toString().length() > 0) {
            hasOrderBy = true;
        }
        try {
            Object _pageNum = getParamValue(paramsObject, "pageNum", required);
            Object _pageSize = getParamValue(paramsObject, "pageSize", required);
            if (_pageNum == null || _pageSize == null) {
                if(hasOrderBy){
                    Page page = new Page();
                    page.setOrderBy(orderBy.toString());
                    page.setOrderByOnly(true);
                    return page;
                }
                return null;
            }
            pageNum = Integer.parseInt(String.valueOf(_pageNum));
            pageSize = Integer.parseInt(String.valueOf(_pageSize));
        } catch (NumberFormatException e) {
            throw new PageException("分页参数不是合法的数字类型!", e);
        }
        Page page = new Page(pageNum, pageSize);
        //count查询
        Object _count = getParamValue(paramsObject, "count", false);
        if (_count != null) {
            page.setCount(Boolean.valueOf(String.valueOf(_count)));
        }
        //排序
        if (hasOrderBy) {
            page.setOrderBy(orderBy.toString());
        }
        //分页合理化
        Object reasonable = getParamValue(paramsObject, "reasonable", false);
        if (reasonable != null) {
            page.setReasonable(Boolean.valueOf(String.valueOf(reasonable)));
        }
        //查询全部
        Object pageSizeZero = getParamValue(paramsObject, "pageSizeZero", false);
        if (pageSizeZero != null) {
            page.setPageSizeZero(Boolean.valueOf(String.valueOf(pageSizeZero)));
        }
        return page;
    }

**Comment by abel533** [comment]
文档搜索 params，改成别的关键字即可。
