### ISSUE TITLE
如何指定分页范围

### ISSUE THREAD

**Issue by GreenCypress** [pagehelper/Mybatis-PageHelper#728]
- [] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

例如一张表有1000条数据，但是我喜欢只分页前100条记录；
假如pageSize设置为10，则最多只有10页，total也最高为100。
没找到相应的用法，望解答

**Comment by abel533** [comment]
没有这样的方法，你可以对返回结果封装，限制为100条。

**Comment by GreenCypress** [comment]
> 没有这样的方法，你可以对返回结果封装，限制为100条。

好的 谢谢。
