### ISSUE TITLE
how to set the pager not work even though pagesize and pagenum included in parameters

### ISSUE THREAD

**Issue by JohnyDuan** [pagehelper/Mybatis-PageHelper#73]
sometimes i have put pagesize and pagenum into mybatis' parameters. in fact i do not want to page the result. but the interceptor recognizes it needs to page. of course i do not invoke pagehelper.start method

**Comment by abel533** [comment]
This bug has been resolved, you can upgrade to 5.0.3.

**Comment by a601942905git** [comment]
如果是spring-boot,1.1.1版本的好像还是有改bug

**Comment by abel533** [comment]
@a601942905git 需要用对应的starter.

**Comment by a601942905git** [comment]
我用的是1.1.1版本的starter，我没有调用startPage的查询也会被拦截。导致count查询被执行2次。
发自我的 iPhone

**Comment by abel533** [comment]
升级到最新版本。。低版本有个bug会导致符合条件的被自动分页。

**Comment by a601942905git** [comment]
好的谢谢,starter升级到1.1.3就可以了。感谢
