### ISSUE TITLE
请教个问题，Mapper请求后 new PageInfo 是如何把total值设置进去的

### ISSUE THREAD

**Issue by wxz0107** [pagehelper/Mybatis-PageHelper#730]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议

PageHelper.startPage(1, 10);
List<User> list = userMapper.selectAll();
//用PageInfo对结果进行包装
PageInfo page = new PageInfo(list);

看到PageInfo是新创建的 应该total是list的长度，但是total 能设置成数据库的真实总数

**Comment by abel533** [comment]
直接看源码，还可以加断点。

**Comment by tvzr** [comment]
```java
Page page = PageHelper.startPage(start,end);
...
...
...
result.setTotal(page.getTotal());
```
