### ISSUE TITLE
presto的connection.getMetaData.getUrl 返回的url不带[jdbc:]前缀...

### ISSUE THREAD

**Issue by fengyaocheng** [pagehelper/Mybatis-PageHelper#735]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.3.2
* 数据库类型和版本: presto 0.272
* JDBC_URL: jdbc:presto://xxxx:xxxx/hive/user?SSL=false)

## 功能建议

详细说明，尽可能提供(伪)代码示例。
目前presto的connection.getMetaData.getUrl 返回的url不带[jdbc:]前缀,导致报错,提示找不到对应的方言.请问我该如何处理?

**Comment by cqu2014** [comment]
您的邮件王振已收到 。

**Comment by abel533** [comment]
把异常堆栈提供一下。

**Comment by fengyaocheng** [comment]
宝贝,我更正下,我pagehelper version is 5.2.1.我改成最新版之后已经没问题了. 我看你之前是datasource.getconnection.getUrl,现在改成了直接从datasource.getUrl了.强的.
