### ISSUE TITLE
new PageInfo(null)会报空指针异常

### ISSUE THREAD

**Issue by 7colorlotus** [pagehelper/Mybatis-PageHelper#737]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.3.1

#### 分页参数

```java
new PageInfo(null);
```

### 完整异常信息

```
Exception in thread "main" java.lang.NullPointerException
	at com.github.pagehelper.PageSerializable.<init>(PageSerializable.java:48)
	at com.github.pagehelper.PageInfo.<init>(PageInfo.java:100)
	at com.github.pagehelper.PageInfo.<init>(PageInfo.java:90)
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
这算什么bug？

**Comment by 7colorlotus** [comment]
不好意思，没说清楚。
先说一下背景，项目中有一个代码对PageInfo做了一层封装
`
public PageResult(List<T> list) {
		PageInfo<T> pageInfo = new PageInfo<>(list);
		this.list = pageInfo.getList();
		this.total = pageInfo.getTotal();
	}
`

以前的版本直接调用new PageResult(null)，是可以正常成功的。
但是自从升级了版本为：5.3.1后，就一直报空指针的错误。就是上面截图的错误。

理论上，PageHelper插件不该这么用。但是之前的版本可以正常，新的版本就不正常，不知道什么原因，所以就好奇发上来问一下。目前我改了一下代码，项目上可以正常使用了！
`
public PageResult(List<T> list) {
		if(null == list){
			list = Collections.emptyList();
		}
		PageInfo<T> pageInfo = new PageInfo<>(list);
		this.list = pageInfo.getList();
		this.total = pageInfo.getTotal();
	}
`

谢谢回复！

**Comment by abel533** [comment]
使用 `Collections.emptyList()` 替代 null 就行。
