### ISSUE TITLE
当通过代码设置分页配置的时候，统计总条数的sql会被拦截，导致出错 “在系统中发现了多个分页插件，请检查系统配置!”

### ISSUE THREAD

**Issue by renjh2011** [pagehelper/Mybatis-PageHelper#74]
@Bean
    @ConditionalOnMissingBean
    public SqlSessionFactory sqlSessionFactory() throws Exception {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(roundRobinDataSouceProxy());

        PageInterceptor interceptor = new PageInterceptor();
        Properties props = new Properties();
        props.setProperty("reasonable", "true");
        props.setProperty("supportMethodsArguments", "true");
        props.setProperty("autoRuntimeDialect", "true");
        props.setProperty("params", "count=countSql");
        interceptor.setProperties(props);
        sqlSessionFactoryBean.setPlugins(new Interceptor[]{interceptor});

        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        sqlSessionFactoryBean.setMapperLocations(resolver.getResources("classpath:mapper/*.xml"));
        sqlSessionFactoryBean.getObject().getConfiguration().setMapUnderscoreToCamelCase(true);
        return sqlSessionFactoryBean.getObject();
    }

**Comment by abel533** [comment]
没有同时自己配置和spring boot 配置方式吧？

**Comment by renjh2011** [comment]
开始没注意配置文件也配置了，非常感谢。
