### ISSUE TITLE
怎么不让 pagehelper 通过 RowBounds 进行分页

### ISSUE THREAD

**Issue by tanyaofei** [pagehelper/Mybatis-PageHelper#743]
由于历史问题，我司大量项目在Executor用了统一定义了，RowBounds 也就是所有 sql 在 PageHelper.skip 时都会通过 RowBounds 创建分页，导致所有 sql 都走了分页，有什么办法可以解决吗？可以通过自定义 Dialect?

**Comment by abel533** [comment]
你们所有查询都用了 RowBounds参数？这个参数不是用来分页的？有没有例子？

**Comment by tanyaofei** [comment]
感谢回复。
历史原因以前公司的人弄了一个 RowBounds 限制所有 selectList 查询最大为 10000 条，还涉及到了其他地方暂时不敢动，已经找到了别的解决方法，通过继承 PageHelper 重写 skip() 方法，再通过配置文件指定即可
