### ISSUE TITLE
配置postgresql方言分页失败

### ISSUE THREAD

**Issue by wzkris** [pagehelper/Mybatis-PageHelper#746]
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/90759163/2b478c45-87c5-4385-973d-03cd5ca4cf43)
配置如图
执行结果
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/90759163/3a53d8a2-e959-42dd-a8b9-558e14dd0e2e)
断点发现根本就不走分页，如图
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/90759163/b2ea6318-f82e-4f89-a602-dfd25b078e58)
----------------------------------------------------------------------
离谱的来了，当我刷新页面重新获取菜单路由时，分页的数据竟然被插入到路由列表里面去了，导致直接报错
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/90759163/a345d5cc-22a8-4f0a-9881-970cf243af98)
怀疑是线程污染，但是我除了上面给的配置之外没有再做其他的操作。。。

**Comment by abel533** [comment]
看文档：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#5-%E5%88%86%E9%A1%B5%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D

应该配置 helperDialect：分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值： oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby （完整内容看 [PageAutoDialect](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/src/main/java/com/github/pagehelper/page/PageAutoDialect.java)） 特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页，还可以设置 useSqlserver2012=true 将2012改为sqlserver的默认方式。 你也可以实现 AbstractHelperDialect，然后配置该属性为实现类的全限定名称即可使用自定义的实现方法。

可以开启 debug 模式，如果有不安全的调用，可以通过设置分页参数的堆栈和执行分页的堆栈来分析出错的调用位置。

**Comment by wzkris** [comment]
> helperDialect



> 看文档：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#5-%E5%88%86%E9%A1%B5%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D
> 
> 应该配置 helperDialect：分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值： oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby （完整内容看 [PageAutoDialect](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/src/main/java/com/github/pagehelper/page/PageAutoDialect.java)） 特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页，还可以设置 useSqlserver2012=true 将2012改为sqlserver的默认方式。 你也可以实现 AbstractHelperDialect，然后配置该属性为实现类的全限定名称即可使用自定义的实现方法。
> 
> 可以开启 debug 模式，如果有不安全的调用，可以通过设置分页参数的堆栈和执行分页的堆栈来分析出错的调用位置。

**Comment by wzkris** [comment]
我试过了，不起作用，分页的语法还是使用MySQL的limit ?, ?

**Comment by wzkris** [comment]
找到问题了，druid的sql解析器会将sql中的limit ? offset ?解析成limit ? , ?
