### ISSUE TITLE
springboot3.1.0引入pageHelper执行分页方法报类型转换异常

### ISSUE THREAD

**Issue by quccwang** [pagehelper/Mybatis-PageHelper#748]
![pageHelper报错](https://github.com/pagehelper/Mybatis-PageHelper/assets/135097482/6dd84a83-f10d-4440-865b-0e479ee369dd)

**Comment by quccwang** [comment]
![1685623074208(1)](https://github.com/pagehelper/Mybatis-PageHelper/assets/135097482/9096654c-7bf1-48b7-900d-14a5504b5eed)

**Comment by quccwang** [comment]
我切换2.7.5版本的springboot后发现没问题了。感觉springboot3.*系列的版本依赖配置第三方jar包后要想使用功能还必须加配置才行（开启分页插件生效的配置？），分页插件不会自动生效。springboot2.*系列版本引入pageHelper插件后可以自动生效。

**Comment by LiquidElectronDZX** [comment]
same question.  Do i have to change springboot to 2.x?

**Comment by abel533** [comment]
是最新版本的pageheleper-starter吗？

**Comment by pagehelper** [comment]
上面的错应该是没有经过分页，但是强制转换为Page类型用导致的。

有可能是调用了PageHelper.start分页，但是在你想分页的方法前，被别的查询使用了，导致想分页的方法没被分页。
