### ISSUE TITLE
拦截器拦截sql问题

### ISSUE THREAD

**Issue by renjh2011** [pagehelper/Mybatis-PageHelper#75]
请问一下不拦截select count(0) from table在哪实现的，才开始用mybatis,不怎么熟悉。谢谢！

**Comment by abel533** [comment]
不拦截？哪儿拦截了？

**Comment by renjh2011** [comment]
你好，是我没说清楚，不好意思。是设置pagehelper.start(pageNum,pageSize)后，到拦截器里面会生成一个_COUNT的统计总数的查询sql，因为之前在配置文件和代码中配置了两次分页，发现运行到
 //执行 count 查询
                    Object countResultList = executor.query(countMs, parameter, RowBounds.DEFAULT, resultHandler, countKey, countBoundSql);
的时候被拦截了，只配置一次分页则没有拦截。这点没有理解。

**Comment by abel533** [comment]
配置一次就没问题。
