### ISSUE TITLE
建议给 PageInfo 加个 list<T>转换的方法；

### ISSUE THREAD

**Issue by 203579397** [pagehelper/Mybatis-PageHelper#751]
PageUtils.startPage();
        PageInfo<T1> mapPageInfo = PageInfo.of(actTaskMapper.findTodoList(vo));
        PageUtils.clearPage();
        //由于PageHelper的PageInfo没有类型转换方法，这里先草率的用 BeanUtils.copyProperties(); 转换一下
        PageInfo<T2> pageInfo = PageInfo.emptyPageInfo();
        BeanUtils.copyProperties(mapPageInfo, pageInfo);

希望有个 类似这种的：

    public <R>  PageInfo<R> map(Function<? super T, ? extends R> mapper) {
        List<R> collect = this.getRows().stream().map(mapper).collect(Collectors.toList());
        return new  PageInfo<>(collect, this.total);
    }

**Comment by abel533** [comment]
既然都有PageUtils封装了，建议先封装一个自己的PageInfo。

分页插件后续版本会基于jdk8，类似这种方法后续可以加进去。

**Comment by 203579397** [comment]
嗯好。非常期待您说的以后版本。其实我这样处理也不麻烦；

**Comment by pagehelper** [comment]
2020年7月的代码有下面的方法：
```
public <T> PageInfo<T> toPageInfo(Function<E, T> function) {
```
