### ISSUE TITLE
多查询汇总分页

### ISSUE THREAD

**Issue by Richerlv** [pagehelper/Mybatis-PageHelper#753]
建议给PageHelper增加一个可以对多个查询的结果进行汇总，然后分页的功能。
```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
xxMapper1.select(model1);
```

## 功能建议

大概意思就是startPage语句后面可能跟多个查询语句，如果前面的条数不足pageSize条可以继续作用于下面的查询语句，同时将pageSize减去已经查到的条数；这样做可以避免开发者手动分页。

**Comment by abel533** [comment]
不合适，建议SQL UNION
