### ISSUE TITLE
Page对象的dubbo反序列化问题

### ISSUE THREAD

**Issue by xiaoduanayu** [pagehelper/Mybatis-PageHelper#754]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.
A应用调用dubbo微服务，微服务使用分页插件操作数据库，同时微服务自己封装了一套公共分页返回对象，底层通过page.getResult方法将list结果设置到自定义的分页对象。A应用在dubbo响应反序列化时会出现警告。
Hessian/Burlap: 'com.github.pagehelper.Page' is an unknown class
java.lang.ClassNotFoundException: com.github.pagehelper.Page

通过排查得知，page.getResult返回的不是java.util.ArrayList，而是Page对象，但是A应用中并不操作数据库，所以我并不想在A应用中也引入分页插件（引入分页插件即可解决这个警告），请问还有更好的办法吗？

**Comment by pagehelper** [comment]
new ArrayList(page) 即可。
