### ISSUE TITLE
应该在使用说明中建议使用try resource写法

### ISSUE THREAD

**Issue by anda-ren** [pagehelper/Mybatis-PageHelper#775]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
我们在UT中发现`select count(*) from abc` 返回了null,这是不应该的。经过仔细排查发现，PageHelper拦截了一个SQL，这个SQL背后的mapper是我们在UT过程中mock的，没有触发PageHelper清理ThreadLocal的动作。这个Thread被后续的UT复用了。

## 功能建议
经过阅读源码我们发现，Page对象实现了`AutoClosable`。我们建议在使用说明文档中增加这样的使用建议，以保证无论什么情况thread local都被清理。
```java
try(Page=PageHelper.startPage(1, 10)){
    List<User> list = userMapper.selectIf(1);
}

```

**Comment by abel533** [comment]
文档中的安全调用有介绍。。

debug参数也能方便定位错误设置和使用的堆栈信息。
