### ISSUE TITLE
SpringBoot 在xml中有limit的时候会自动增加一个limit

### ISSUE THREAD

**Issue by devlopeLi** [pagehelper/Mybatis-PageHelper#78]
<dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper</artifactId>
            <version>4.1.6</version>
</dependency>

<dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.0</version>
</dependency>

select
  *
    from xxx
    where xxx = #{xxx,jdbcType=INTEGER} AND xxx > -2 ORDER BY xxx DESC limit 1

会在sql 执行的时候在最后面增加limit,

**Comment by abel533** [comment]
不要对已经分页的SQL使用分页插件。

**Comment by SERE026** [comment]
这个有点鸡肋，只要参数中带有和分页参数中的可以相同，就会自动触发分页查询

**Comment by abel533** [comment]
@SERE026 升级到最新版本。。低版本有个bug。。最新版本需要配置才会自动触发分页查询。
