### ISSUE TITLE
【功能请求】自定义 count sql 获取 PageInfo 对象请求

### ISSUE THREAD

**Issue by WangJincheng4869** [pagehelper/Mybatis-PageHelper#788]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 功能建议

目前在 `PageInfo` 存在一个 `of` 方法，这个方法在使用 `PageHelper.startPage(0, 10)` 时可以正常获取全部属性值，但是当使用 `PageHelper.startPage(0, 10, false)` 时会导致无法获取完整的属性值，有以下的功能请求：

1.  `of`  方法添加一个 `total` 参数，传入总数然后返回完整的属性值
```java
long total = userMapper.selectCount();
if (total == 0) {
  return new ArrayList<User>();
}
PageHelper.startPage(0, 10, false)
List<User> list = userMapper.select();
PageInfo<User> pageInfo = PageInfo.of(list);
```
2.  `of`  方法添加一个 `ISelect` 参数，可以将查询方法写在函数中，然后返回完整的属性值

```java
PageHelper.startPage(0, 10, () -> userMapper.selectCount());
List<User> list = userMapper.select();
PageInfo<User> pageInfo = PageInfo.of(list);
```

我比较喜欢第一种方式，因为正常来讲，当数据为 0 的时候，就不必继续执行查询语句了。

**Comment by abel533** [comment]
来个PR？

**Comment by yesAnd92** [comment]
我也有这个场景的需求，如果没人认领，我来提个PR?
