### ISSUE TITLE
PageHelper.startPage(pageNo,pageSize,count) , 在少量数据的情况下 count为true一直返回第一页

### ISSUE THREAD

**Issue by luzhiming** [pagehelper/Mybatis-PageHelper#79]
这个问题已知，是reasonable造成的，使用PageHelper.satrtPage(pageNo,pageSize,count,reasonable) , 将reasonable设置为false，也就是将合理化分页设置false即可解决这个问题。 在产品研发中，如果分页查询的话，有多少数据就展示多少数据。 这里的这个合理化设置对于我这种初次使用PageHelper的人来说还是稍微小坑了一把。 更多的人和更多的情况是 按照实际查询返回结果。

**Comment by abel533** [comment]
注意看 resonable 参数。
