### ISSUE TITLE
这个参数根本没用pagehelper.auto-dialect=false，代码里一直都是true，无法控制

### ISSUE THREAD

**Issue by yeeevip** [pagehelper/Mybatis-PageHelper#792]
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/3b5296ab-aeeb-4e5c-841b-827aeb29db52)

![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/61f8531a-7235-49ec-af47-6b05b27e3ffd)

**Comment by abel533** [comment]
使用的什么版本？

**Comment by yeeevip** [comment]
5.3

**Comment by yeeevip** [comment]
这个参数的变化达不到的我目的    具体我要解决的问题看一下 #793

**Comment by yeeevip** [comment]
auto-runtime-dialect: true  ， 升级到<pagehelper-spring-boot-starter.version>1.4.4</pagehelper-spring-boot-starter.version>  可以了，原来是我用的版本不支持kebab-base风格
