### ISSUE TITLE
多数据库方言就有问题，假如我第一次使用了mysql，然后使用sqlserver查询就还是用的limit分页；代码逻辑有问题具体看详情

### ISSUE THREAD

**Issue by yeeevip** [pagehelper/Mybatis-PageHelper#793]
### 使用环境
* PageHelper 版本: 5.3.0

### 问题
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/3270df8b-1b96-4940-80b9-cc7f9c109979)
这段代码硬是看不懂，第一次初始化了mysqldialect，之后我用sqlserver还是mysqldialect，即使调用了using("sqlserver")无作用，
作者可以自行测试：测试用例，不要用我自己实现的方言 https://github.com/yeeevip/yeee-memo/blob/master/learn-example/spring-boot-example/src/test/java/vip/yeee/memo/demo/springboot/PageHelperTests.java

### 自己解决了
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/4a238d65-5977-493a-8a3c-8a56a5a35e6f)
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/f2ca18df-8ac4-4f92-a5e2-9f4336692ca5)

自己改了一下代码临时用用，重写了PageHelper和PageAutoDialect这个类，修改了三处见下图
代码在：https://github.com/yeeevip/yeee-memo/tree/master/learn-example/spring-boot-example/src/main/java/vip/yeee/memo/demo/springboot/pagehelper

![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/3ca5e3e9-c9a2-4a6c-b27b-65d70056c0c0)
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/df174a4f-57d9-49b1-aec6-08f9e3a9c319)
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/2a829446-7b52-4afe-bbe6-05b109149b31)

**Comment by abel533** [comment]
有没有试过6.0版本？

**Comment by yeeevip** [comment]
> 有没有试过6.0版本？

没有  版本太高会不会不兼容，我们项目中都是5.3

**Comment by yeeevip** [comment]
> 有没有试过6.0版本？



> 有没有试过6.0版本？

我现在给你测一下6.0吧

**Comment by yeeevip** [comment]
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/70721d32-9727-4dfe-9014-b62adb042290)
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/27989bfa-64a1-413c-b7bb-2aaf10d8ffb4)
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/30142025/8d0ee827-73e2-4223-8f2a-0a174a892186)
大佬  6.0也是一个样子  只能按照我这个改一下了https://github.com/yeeevip/yeee-memo/tree/master/learn-example/spring-boot-example/src/main/java/vip/yeee/memo/demo/springboot/pagehelper @abel533

**Comment by yeeevip** [comment]
@abel533   大佬 我简单改了一下，第一次pr 希望合并留个名，谢谢`_`

**Comment by yeeevip** [comment]
@abel533  pr测试过了， 我的改动部分觉得合适帮我合一呗，我的改动大致这样：autoDialect=true就从上下文拿自动获取到的方言，否则就固定用this.delegate这个

**Comment by yeeevip** [comment]
搞了半天autoRuntimeDialect  配置参数只能这样啊，不能下划线方式啊

**Comment by abel533** [comment]
@yeeevip 你看看starter项目中的属性定义，应该有额外支持中线的（烤串）。。下划线不是标准方式，spring boot也不支持。

**Comment by abel533** [comment]
如果有qq，可以加群：912339468
