### ISSUE TITLE
Springboot3版本supportMethodsArguments参数失效

### ISSUE THREAD

**Issue by liukai237** [pagehelper/Mybatis-PageHelper#798]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 6.1.0

### 问题描述

PageObjectUtil中：
```java
requestClass = Class.forName("javax.servlet.ServletRequest");
```
实际已经变为`jakarta.servlet.ServletRequest`

## 功能建议

希望增加判断条件，兼容新的Servlet版本

**Comment by abel533** [comment]
可以同时判断这两种情况，有第一个就用，报错就尝试第二种。来个PR？

**Comment by abel533** [comment]
#804 已实现。
