### ISSUE TITLE
关于page实现closeable接口，实现清空分页的历史数据，防止参数污染问题

### ISSUE THREAD

**Issue by breaksilence** [pagehelper/Mybatis-PageHelper#81]
通过Closeable以try()的jdk新特性来清理Pagehelper的历史参数是比较好的一种做法，不过为为什么不在每次调用Pagehelper.startPage()方法时直接先清理一下数据呢？另外排序的插件抽离出来了，这样OrderbyHeper也将面临这样的问题，如果都需要try的方式来处理，代码不够简洁

**Comment by abel533** [comment]
排序会尽快加到分页中，startPage本身会覆盖。
