### ISSUE TITLE
版本由4.1.6 升级到5.3.2后，PageDynamicSqlSource被删除了有什么方案代替

### ISSUE THREAD

**Issue by ZMMWMY** [pagehelper/Mybatis-PageHelper#813]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 4.1.6 -> 5.3.2
* 数据库类型和版本: MySQL
![image](https://github.com/pagehelper/Mybatis-PageHelper/assets/19320021/401b125a-afc3-4bdb-9868-e820dace540a)

另外一个问题：版本升级后，有没有其他的潜在问题。更新文档里并没有给出详细的介绍

**Comment by abel533** [comment]
你自己的拦截器吗？先去掉instanceof的判断，然后在这里加个断点，进来后你看看 sqlSlource是什么类型。
