### ISSUE TITLE
查询返回结果慢

### ISSUE THREAD

**Issue by huangshanongfushan** [pagehelper/Mybatis-PageHelper#82]
SQL Server 查询，八百万数据量的时候，返回结果很慢，而用相同的语句在其它工具中运行返回结果速度很快
![qq 20170719113623](https://user-images.githubusercontent.com/10303104/28349633-98ae5452-6c76-11e7-98a9-c63957d2ed40.png)

**Comment by abel533** [comment]
可以手写查询用mybatis执行看看。

**Comment by huangshanongfushan** [comment]
之前我也怀疑过驱动包版本，换过正常，手写mybatis 分页语句也正常，目前只有使用pagehelper 的时候，大数据量的时候很慢。因为查询参数是Date 类型的，后来测试发现，如果将查询条件由Date 转成String 的时候，再使用pageHelper时查询正常
