### ISSUE TITLE
Wiki Example Correction Request - offsetPage Method in HowToUse.md

### ISSUE THREAD

**Issue by S00ahKim** [pagehelper/Mybatis-PageHelper#839]
> I used a translation tool to help draft this issue, and I apologize for any inaccuracies that might be present. Thank you for your understanding.

- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: xxx
* 数据库类型和版本: xxx
* JDBC_URL: xxx

#### 示例代码

```java
// 3. 使用静态方法 offsetPage
PageHelper.offsetPage(1, 10);
List<User> list = userMapper.selectIf(1);
```

Wiki 中 “3. 使用静态方法 offsetPage” 部分提供的示例似乎不正确。

为了实现与 “2. 使用静态方法 startPage” 示例相同的结果：
```java
PageHelper.startPage(1, 10);
List<User> list = userMapper.selectIf(1);
```

代码中的 `offsetPage(1, 10)` 应该修改为 `offsetPage(0, 10)`，以确保分页偏移正确工作。此更改将使索引从 0 开始，与 `startPage` 的行为保持一致。

---

```java
// 3. use static method offsetPage
PageHelper.offsetPage(1, 10);
List<User> list = userMapper.selectIf(1);
```

The example provided above in the Wiki under "3. use static method offsetPage" seems incorrect.

To produce the same result as in the example under "2. use static method startPage":
```java
PageHelper.startPage(1, 10);
List<User> list = userMapper.selectIf(1);
```

The line `offsetPage(1, 10)` should be modified to `offsetPage(0, 10)` to ensure the pagination offset works correctly. This change aligns the indexing to start from 0, similar to `startPage`.

### 期望的结果：

```java
// 修正后的版本
PageHelper.offsetPage(0, 10);
List<User> list = userMapper.selectIf(1);
```

### 相关信息

* Wiki 链接: [Mybatis-PageHelper HowToUse.md](https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/en/HowToUse.md)

**Comment by abel533** [comment]
文档中改为0更合适，可以来个PR，需要同时改中英文两个版本。
