### ISSUE TITLE
请问使用了你的分页插件，导致我其他拦截器都不生效了，怎么破?

### ISSUE THREAD

**Issue by frontng** [pagehelper/Mybatis-PageHelper#85]
我其他自己写的拦截器（拦截全部增删改查），但只有删除动作的时候会进去我自定义的拦截器，一般查询都不进来。怎么回事呢，请指教。

**Comment by frontng** [comment]
用的是Spring Boot 方式

**Comment by abel533** [comment]
这有一篇很详细的文档：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md

如果你需要控制顺序，就别用分页的stater，手动设置。
