### ISSUE TITLE
关于sqlserver2008的支持问题

### ISSUE THREAD

**Issue by yyhLogin** [pagehelper/Mybatis-PageHelper#87]
用5.0.0版本的pageHelper，3.3.0版本的mybatis, 4.2.5版本的spring
在配置完成之后运行项目出现:Could not initialize class com.github.pagehelper.parser.SqlServerParser错误

**Comment by abel533** [comment]
先检查这个类是否存在，还要看项目下有没有对应jar包。

都没问题的情况下，把上面的错误信息贴完整。

**Comment by a846487248** [comment]
![default](https://user-images.githubusercontent.com/19282994/28815481-1b6519aa-76d4-11e7-9740-670a55cd1a91.jpg)
错误代码太长了，就是不能创建sqlSessionFactory

**Comment by abel533** [comment]
关键的信息在后面。。直接发文本，别截图。

**Comment by a846487248** [comment]
作者大大，我回你邮件了。不知道是不是那个邮箱

**Comment by abel533** [comment]
没收到，abel533@gmail.com

**Comment by a846487248** [comment]
作者大大看到邮件了吗

**Comment by abel533** [comment]
你是不是直接下载的jar包？没有jsqlparser？

**Comment by a846487248** [comment]
有啊。maven配置的

**Comment by abel533** [comment]
`PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'properties' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.github.pagehelper.parser.SqlServerParser`

初始化失败的，一般原因都是依赖或者版本出的错。
