### ISSUE TITLE
未使用分页时，元素在数据库中的行号计算问题

### ISSUE THREAD

**Issue by ruknow** [pagehelper/Mybatis-PageHelper#89]
com.github.pagehelper.PageInfo

        if (list instanceof Page) {
            Page page = (Page) list;
            this.pageNum = page.getPageNum();
            this.pageSize = page.getPageSize();

            this.pages = page.getPages();
            this.list = page;
            this.size = page.size();
            this.total = page.getTotal();
            //由于结果是>startRow的，所以实际的需要+1
            if (this.size == 0) {
                this.startRow = 0;
                this.endRow = 0;
            } else {
                this.startRow = page.getStartRow() + 1;  //120
                //计算实际的endRow（最后一页的时候特殊）
                this.endRow = this.startRow - 1 + this.size; //122
            }
        } else if (list instanceof Collection) {
            this.pageNum = 1;
            this.pageSize = list.size();

            this.pages = this.pageSize > 0 ? 1 : 0;
            this.list = list;
            this.size = list.size();
            this.total = list.size();
            this.startRow = 0; //132
           this.endRow = list.size() > 0 ? list.size() - 1 : 0; //133
        }

这两处计算方式不一至，Line:120上面为以1开始，Line:132下面为0开始。
132,133处改为以下是否更好(符合前端页面显示内容)：

    this.startRow = list.size() > 0 ? 1 : 0;
    this.endRow = list.size() > 0 ? list.size() : 0;

**Comment by abel533** [comment]
合适，你PR还是我直接改？

**Comment by zyong2004** [comment]
如果这样写，没有关系了吧
`public PageInfo(List<E> list, int navigatePages) {
		if (list instanceof Page) {
			Page<E> page = (Page<E>) list;

			this.pageNum = page.getPageNum();
			this.pageSize = page.getPageSize();
			this.pages = page.getPages();
			this.list = page;
			this.size = page.size();
			this.total = page.getTotal();
			if (this.size == 0) {
				this.startRow = 0;
				this.endRow = 0;
			} else {
				this.startRow = page.getStartRow() - 1;
				// 计算实际的endRow（最后一页的时候特殊）
				this.endRow = page.getEndRow() - 1 + this.size;
			}
		} else if (list instanceof Collection) {
			this.pageNum = 1;
			this.pageSize = list.size();

			this.pages = this.pageSize > 0 ? 1 : 0;
			this.list = list;
			this.size = list.size();
			this.total = list.size();
			this.startRow = 0;
			this.endRow = list.size() > 0 ? list.size() - 1 : 0;
		}
		if (list instanceof Collection) {
			this.navigatePages = navigatePages;

			calculateNavigate();
			calculatePage();
			judgePageBoudary();
		}
	}
`

**Comment by ruknow** [comment]
你直接改吧。（因事耽搁，回复晚了）
