### ISSUE TITLE
分页的查询和查询count的操作是不是分开的?

### ISSUE THREAD

**Issue by pengyonglei** [pagehelper/Mybatis-PageHelper#90]
`
//第二种，Mapper接口方式的调用，推荐这种使用方式。
PageHelper.startPage(1, 10);
List<Country> list = countryMapper.selectIf(1);
`

你好, 请问这个操作是只会执行一次数据库的分页查询, 还是说做这个操作的时候, 其实也执行了一遍count的查询, 总共执行了2次数据库的查询呢 ?

**Comment by abel533** [comment]
同时，一共2次。。可以控制是否执行count。

**Comment by pengyonglei** [comment]
那怎么控制是否执行count呢？我就是需要这个功能呢，请指教




发自网易邮箱大师
在2017年08月03日 21:05，Liuzh 写道：

同时，一共2次。。可以控制是否执行count。

**Comment by abel533** [comment]
startPage第三个参数，或者params参数中的count。

**Comment by pengyonglei** [comment]
好的，那我来试一下，非常感谢您的帮助




发自网易邮箱大师
在2017年08月03日 21:29，Liuzh 写道：

startPage第三个参数，或者params参数中的count。
