### ISSUE TITLE
Oracle带Orderby非主键字段分页查询有问题

### ISSUE THREAD

**Issue by lnj2050** [pagehelper/Mybatis-PageHelper#91]
Oracle数据库，分页时，order by字段是非主键字段，并且存在相同值情况，则分页会出现错乱，
http://www.2cto.com/database/201309/242801.html
http://blog.csdn.net/zgs_shmily/article/details/47833313
请问下这种问题是否之前解决过?

**Comment by abel533** [comment]
需要修改排序规则保证有序。
