### ISSUE TITLE
我用的 jersey 做RESTful，发现返回的 list 无法被序列化为json

### ISSUE THREAD

**Issue by pangguoming** [pagehelper/Mybatis-PageHelper#92]
![image](https://user-images.githubusercontent.com/7269202/29054944-061e2b88-7c2c-11e7-917d-5d38be32ea91.png)

![image](https://user-images.githubusercontent.com/7269202/29054939-ffe3d89e-7c2b-11e7-9656-3d681697e00e.png)
怎么回事？

**Comment by abel533** [comment]
list里面的是你自己的对象。。你的对象为什么不能被序列化？

**Comment by pangguoming** [comment]
是我用的 jersey RESTful框架的原因，不是你插件的原因，谢谢
