### ISSUE TITLE
pageInfo 中的navigatepageNums 属性返回的不是全部页码？

### ISSUE THREAD

**Issue by anchuang** [pagehelper/Mybatis-PageHelper#93]
数据库中有9条数据，在访问前5页数据时，navigatepageNums 的值为1-8，从第6页开始，navigatepageNums的值变为了2-9。

**Comment by abel533** [comment]
每页显示1条数据？navigatepageNums 是导航页显示页码数。可以自己定义。

**Comment by anchuang** [comment]
@abel533 项目开发过程中，每页显示一条是暂时的，navigatepageNums的自定义有文档吗？

**Comment by abel533** [comment]
PageInfo 这么简单个类，直接看源码。

**Comment by anchuang** [comment]
ok
