### ISSUE TITLE
SQL Server WITH(NOLOCK) 问题

### ISSUE THREAD

**Issue by pyzhaowei** [pagehelper/Mybatis-PageHelper#96]
`SELECT * FROM A  WITH(NOLOCK) INNER JOIN B WITH(NOLOCK) ON A.TypeId = B.Id` 中WITH(NOLOCK) 后面的 ON 条件会被去掉; 分析原因 SqlServerDialect 类中把 WITH(NOLOCK)  替换成, PAGEWITHNOLOCK 后解析SQL把 PAGEWITHNOLOCK 解析成一张表了, 建议替换WITH(NOLOCK) 为表名_PAGEWITHNOLOCK, 然后替换过来.例如: A  WITH(NOLOCK) ==> A_PAGEWITHNOLOCK

**Comment by abel533** [comment]
可以。你可以PR，或者我最近会改。

**Comment by abel533** [comment]
5.1.0 版本会解决这个问题，增加了一个针对 sqlserver 的参数 replaceSql，默认还是以前的处理方式，修改成 regex 后会使用新的方式处理。。还可以自己实现 ReplaceSql 接口。

`regex` 采用的就是你这里的思路。

**Comment by abel533** [comment]
```java
public class RegexWithNolockReplaceSql implements ReplaceSql {

    //with(nolock)
    protected String WITHNOLOCK = ", PAGEWITHNOLOCK";

    @Override
    public String replace(String sql) {
        return sql.replaceAll("((?i)\\s*(\\w?)\\s*with\\s*\\(nolock\\))", " $2_PAGEWITHNOLOCK");
    }

    @Override
    public String restore(String sql) {
        return sql.replaceAll("\\s*(\\w*?)_PAGEWITHNOLOCK", " $1 WITH(NOLOCK)");
    }

}
```

**Comment by abel533** [comment]
希望能得到5.1.0-beta2版本的反馈！

**Comment by pyzhaowei** [comment]
嗯, 我已经PR了,可以解决我们现在的问题,期待5.1.0
