### ISSUE TITLE
toString()方法中少了“=”连接符

### ISSUE THREAD

**Issue by hannawei** [pagehelper/Mybatis-PageHelper#98]
https://github.com/pagehelper/Mybatis-PageHelper/blob/2a90efd15aa3a4324d5dbce894fc7ad26fae4a2e/src/main/java/com/github/pagehelper/PageInfo.java#L392
https://github.com/pagehelper/Mybatis-PageHelper/blob/2a90efd15aa3a4324d5dbce894fc7ad26fae4a2e/src/main/java/com/github/pagehelper/PageInfo.java#L393

**Comment by abel533** [comment]
确实少了。

**Comment by abel533** [comment]
已经改了。
